const {assertAccountingWritable,accountingClosedYears,updateOpenAccountingRecord}=require('./accountingYearClosure');
const {createHash}=require('node:crypto');
const fields=['memberId','memberName','invoiceNumber','invoiceDate','amountCents','year','membershipType','salutation','firstName','lastName','department','street','country','postalCode','city','billingEmail','personalSalutation','taxNumber','contributionMonths','contributionFrom','contributionTo'];
const fingerprint=record=>createHash('sha256').update(JSON.stringify(fields.map(k=>String(record[k]??'').trim()))).digest('hex');
function resolvedInvoice(record,member={}){const values={firstName:member.firstName,lastName:member.lastName,department:member.department,street:[member.street,member.houseNumber].filter(Boolean).join(' '),country:member.countryCode||member.country,postalCode:member.postalCode,city:member.city,billingEmail:member.billingEmail||member.invoiceEmail||member.email||member.contactEmail,personalSalutation:member.personalSalutation};return {...record,...Object.fromEntries(Object.entries(values).filter(([,v])=>String(v||'').trim()))};}
module.exports={invoiceContentFields:fields,invoiceContentFingerprint:fingerprint,resolvedInvoice};

function createInvoiceRevisionTracker({db}){return async event=>{if(!event.data?.before.exists||!event.data?.after.exists)return;const before=event.data.before.data(),after=event.data.after.data();if(fingerprint(before)===fingerprint(after)||after.invoiceNeedsRegeneration&&Number(after.invoiceRevision||0)>Number(before.invoiceRevision||0))return;await db.runTransaction(async tx=>{const ref=event.data.after.ref;const snapshot=await tx.get(ref);if(!snapshot.exists)return;const current=snapshot.data();if((await accountingClosedYears(db,[current],tx)).length)return;if(fingerprint(current)!==fingerprint(after)||current.invoiceNeedsRegeneration)return;tx.update(ref,{invoiceRevision:Number(current.invoiceRevision||0)+1,invoiceNeedsRegeneration:true,invoiceNeedsRedispatch:true,invoiceChangedAt:new Date().toISOString(),reviewStatus:'needs_review'});});};}
module.exports.createInvoiceRevisionTracker=createInvoiceRevisionTracker;
