const {assertAccountingWritable,accountingClosedYears,updateOpenAccountingRecord}=require('./accountingYearClosure');
const {createHash}=require('node:crypto');
const sha=value=>createHash('sha256').update(value).digest('hex');
const normalized=value=>String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]/g,'');
const text=row=>[row.description,row.details].join(' ');
const feeText=row=>/bankgeb[uü]hr|bankspesen|geb[uü]hren|entgelt|spesen|preis\s*f[uü]r\s*sepa/i.test(text(row));
const explicitFee=row=>{const matches=[...text(row).matchAll(/(?:bankgeb[uü]hr(?:en)?|geb[uü]hr(?:en)?|entgelt|spesen)\s*[:=-]?\s*(?:EUR\s*)?([\d.]+,\d{2})\s*(?:EUR|€)?/gi)];const amounts=[...new Set(matches.map(m=>Math.round(Number(m[1].replaceAll('.','').replace(',','.'))*100)))];return amounts.length===1?amounts[0]:0;};
const related=(invoice,row)=>{const reference=normalized(invoice.invoiceNumber);const content=normalized(text(row));return reference.length>=6&&content.includes(reference)||[invoice.memberName,[invoice.firstName,invoice.lastName].filter(Boolean).join(' ')].some(name=>normalized(name).length>=6&&content.includes(normalized(name)));};
const receiptId=(statementId,index)=>sha('internal-bank-fee:'+statementId+':'+index);
function bankFeePlan(statements,outgoing,incoming=[],incomingClaims=[],outgoingClaims=[],rules={}){
 const statementUpdates=[],fees=[],outgoingUpdates=[];const used=new Map([...outgoing.filter(i=>i.paymentMatch).map(i=>[i.paymentMatch.bookingKey||i.paymentMatch.statementId+'_'+i.paymentMatch.rowIndex,i.id]),...outgoingClaims.map(c=>[c.id,c.invoiceId])]);
 for(const statement of statements.filter(s=>!s.warnings?.length)){
  const rows=statement.rows.map(r=>({...r}));let changed=false;const sum=rows.reduce((n,r)=>n+r.amountCents,statement.openingCents);if(sum!==statement.closingCents)continue;
  for(let index=0;index<rows.length;index++){
   const row=rows[index];if(row.amountCents<=0||row.bankFeeCents||row.splitOriginalAmountCents)continue;let feeCents=explicitFee(row),ruleEvidence='Kontoauszug weist Bankgebühr ausdrücklich aus';if(!feeCents){const approved=outgoing.filter(i=>!i.archived&&i.paymentStatus!=='cancelled'&&(rules.netDeductionPartners||[]).some(p=>p.accountingPartnerId&&p.accountingPartnerId===i.accountingPartnerId||normalized(p.memberName)===normalized(i.memberName))&&i.amountCents>row.amountCents&&i.amountCents-row.amountCents<=(rules.maxInferredFeeCents||5000)&&(i.amountCents-row.amountCents)*10000<=i.amountCents*(rules.maxInferredRateBasisPoints||500)&&(!i.invoiceDate||i.invoiceDate<=row.date)&&(i.paymentMatch?.statementId===statement.id&&i.paymentMatch.rowIndex===index||related(i,row)));if(approved.length===1){feeCents=approved[0].amountCents-row.amountCents;ruleEvidence='Vom Nutzer bestätigte Gebührenregel für '+approved[0].memberName;}}if(!feeCents||feeCents<=0)continue;
   const candidates=outgoing.filter(i=>!i.archived&&i.paymentStatus!=='cancelled'&&i.amountCents===row.amountCents+feeCents&&(!i.invoiceDate||i.invoiceDate<=row.date)&&(related(i,row)||i.paymentMatch?.statementId===statement.id&&i.paymentMatch.rowIndex===index)&&(!used.has(statement.id+'_'+index)||used.get(statement.id+'_'+index)===i.id));if(candidates.length!==1)continue;
   const gross=row.amountCents+feeCents;rows[index]={...row,amountCents:gross,bankNetAmountCents:row.amountCents,bankFeeCents:feeCents,bankFeeRuleEvidence:ruleEvidence,postingOrder:index};rows.push({date:row.date,type:'BANKGEBÜHREN',description:'Bankgebühren · '+candidates[0].memberName,details:ruleEvidence+'. Nettogutschrift: '+(row.amountCents/100).toFixed(2)+' EUR. '+text(row),amountCents:-feeCents,accountNumber:'2703',bankFeeDerived:true,parentRowIndex:index,postingOrder:index+0.5,sourceOriginalAmountCents:row.amountCents,iban:''});changed=true;
  }
  const ordered=rows.map((row,index)=>({row,index})).sort((a,b)=>(a.row.postingOrder??a.index)-(b.row.postingOrder??b.index));let balance=statement.openingCents;for(const {row}of ordered){balance+=row.amountCents;row.balanceCents=balance;}if(balance!==statement.closingCents)throw Error('Gebührenaufteilung verändert den Banksaldo.');if(changed)statementUpdates.push({id:statement.id,rows});
  for(const [index,row]of rows.entries()){
   if(row.amountCents>=0||!(feeText(row)||row.accountNumber==='2703'))continue;const key=statement.id+'_'+index,existing=incoming.find(r=>r.internalFeeBookingKey===key);const occupied=incomingClaims.find(c=>c.id===key);if(occupied&&!existing)continue;
   const positives=rows.map((r,i)=>({row:r,index:i})).filter(({row:r,i})=>r.amountCents>0&&r.date===row.date);let associated=positives.filter(({row:r,index:i})=>row.parentRowIndex===i||row.sourceRowIndex!==undefined&&row.splitOriginalAmountCents&&row.sourceRowIndex===r.sourceRowIndex||related({memberName:r.description,invoiceNumber:''},row));
   if(!associated.length){const gross=text(row).match(/(?:Eingang|Überweisung)\s+(?:EUR\s*)?([\d.]+,\d{2})/i);if(gross){const amount=Math.round(Number(gross[1].replaceAll('.','').replace(',','.'))*100);associated=positives.filter(({row:r})=>r.amountCents===amount);}}
   let invoice=null,paymentRow=null,paymentIndex=null;if(associated.length===1){paymentRow=associated[0].row;paymentIndex=associated[0].index;const matched=outgoing.filter(i=>i.paymentMatch?.statementId===statement.id&&i.paymentMatch.rowIndex===paymentIndex||!i.paymentMatch&&i.amountCents===paymentRow.amountCents&&(!i.invoiceDate||i.invoiceDate<=paymentRow.date)&&related(i,paymentRow));if(matched.length===1)invoice=matched[0];}
   fees.push({id:existing?.id||receiptId(statement.id,index),existingId:existing?.id||'',statementId:statement.id,rowIndex:index,bookingKey:key,date:row.date,amountCents:-row.amountCents,statementName:statement.sourceName,accountIban:statement.accountIban||'',bookingText:text(row),outgoingInvoiceId:invoice?.id||'',outgoingInvoiceNumber:invoice?.invoiceNumber||'',counterparty:invoice?.memberName||'',paymentRowIndex:paymentIndex,creditedCents:paymentRow?.bankNetAmountCents??paymentRow?.splitOriginalAmountCents??paymentRow?.amountCents??null,grossCents:invoice?.amountCents??null,historicalImport:statement.historicalImport===true});
  }
 }
 for(const invoice of outgoing){const associated=fees.filter(f=>f.outgoingInvoiceId===invoice.id);if(!associated.length)continue;const gross=invoice.amountCents,feeCents=associated.reduce((n,f)=>n+f.amountCents,0),first=associated[0];const paymentMatch={...(invoice.paymentMatch||{}),statementId:first.statementId,rowIndex:first.paymentRowIndex,bookingKey:first.statementId+'_'+first.paymentRowIndex,amountCents:gross,date:first.date,sourceName:first.statementName,evidence:'Zahlbetrag und dokumentierte Bankgebühr begleichen den Rechnungsbetrag'};outgoingUpdates.push({id:invoice.id,paymentStatus:'paid',paidDate:first.date,paymentReview:false,paymentMatch,bankPaymentSettlement:{grossCents:gross,creditedCents:first.creditedCents,feeCents,netCents:gross-feeCents,feeReceiptIds:associated.map(f=>f.id),feeBookingKeys:associated.map(f=>f.bookingKey)}});}
 return {statementUpdates,fees,outgoingUpdates};
}
function bankFeeReceipt(fee,now,actor){return {id:fee.id,sourceHash:fee.id,sourceName:'Interner Buchungsbeleg BG-'+fee.date.slice(0,4)+'-'+fee.id.slice(0,8).toUpperCase()+'.pdf',invoiceNumber:'BG-'+fee.date.slice(0,4)+'-'+fee.id.slice(0,8).toUpperCase(),supplier:'Bankgebühren'+(fee.counterparty?' · '+fee.counterparty:''),invoiceDate:fee.date,year:Number(fee.date.slice(0,4)),amountCents:fee.amountCents,currency:'EUR',accountNumber:'2703',iban:fee.accountIban,dueDate:'',description:'Interner Buchungsbeleg für Bankgebühren'+(fee.outgoingInvoiceNumber?' zu Ausgangsrechnung '+fee.outgoingInvoiceNumber:'')+'. Quelle: '+fee.statementName+'.',paymentStatus:'paid',paidDate:fee.date,paymentReview:false,reviewStatus:'reviewed',reviewNote:'',sourceFileMissing:false,isInternalBookingReceipt:true,internalReceiptKind:'bank_fee',internalFeeBookingKey:fee.bookingKey,outgoingInvoiceId:fee.outgoingInvoiceId,outgoingInvoiceNumber:fee.outgoingInvoiceNumber,historicalImport:fee.historicalImport,paymentMatch:{bookingKey:fee.bookingKey,statementId:fee.statementId,rowIndex:fee.rowIndex,sourceName:fee.statementName,amountCents:-fee.amountCents,date:fee.date,evidence:'Bankgebühren laut Kontoauszug · interner Buchungsbeleg'},originalImport:{statementId:fee.statementId,rowIndex:fee.rowIndex,bookingKey:fee.bookingKey,bookingText:fee.bookingText,amountCents:fee.amountCents,date:fee.date},createdAt:now,createdBy:actor,updatedAt:now,updatedBy:actor};}
function generateBankFeePdf(fee){const PDFDocument=require('pdfkit');const money=n=>new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}).format(n/100);return new Promise((resolve,reject)=>{const doc=new PDFDocument({size:'A4',margin:48,info:{Title:'Interner Buchungsbeleg Bankgebühren',Author:'PROdigitalTV',CreationDate:new Date(fee.date+'T12:00:00Z'),ModDate:new Date(fee.date+'T12:00:00Z')}}),chunks=[];doc.on('data',c=>chunks.push(c));doc.on('error',reject);doc.on('end',()=>resolve(Buffer.concat(chunks)));doc.fontSize(20).fillColor('#07346a').text('PROdigitalTV');doc.moveDown().fontSize(16).text('Interner Buchungsbeleg');doc.fontSize(11).fillColor('#111111').text('Bankgebühren · Konto 2703 / Bankspesen');doc.moveDown();const lines=[['Belegnummer','BG-'+fee.date.slice(0,4)+'-'+fee.id.slice(0,8).toUpperCase()],['Buchungsdatum',fee.date.split('-').reverse().join('.')],['Bankgebühr',money(fee.amountCents)],['Kontoauszug',fee.statementName],['Kontobuchung',fee.bookingKey],['Konto-IBAN',fee.accountIban],['Ausgangsrechnung',fee.outgoingInvoiceNumber||''],['Rechnungsempfänger',fee.counterparty],['Rechnungsbetrag',fee.grossCents===null?'':money(fee.grossCents)],['Bankgutschrift',fee.creditedCents===null?'':money(fee.creditedCents)]];for(const [label,value]of lines)if(value){doc.font('Helvetica-Bold').text(label+': ',{continued:true});doc.font('Helvetica').text(value);doc.moveDown(0.5);}doc.moveDown().text('Die Gebühr wird als Ausgabe erfasst. Bei Gebührenabzug gilt der Rechnungsbetrag durch Nettogutschrift und dokumentierte Bankgebühr als beglichen.');doc.moveDown().fontSize(10).text('Buchungstext des Kontoauszugs:').text(fee.bookingText,{width:495});doc.moveDown().text('Interner Nachweis auf Grundlage des Kontoauszugs; keine Lieferantenrechnung und kein Ausweis von Umsatzsteuer.');doc.end();});}
function createBankFeeReconciliation({db,bucket,requireAdmin,HttpsError}){return async request=>{await requireAdmin(request);const names=['accountingStatements','membershipContributions','accountingIncomingInvoices','accountingPaymentMatches','accountingOutgoingPaymentMatches'];const snapshots=await Promise.all(names.map(n=>db.collection(n).get()));const data=snapshots.map(s=>s.docs.map(d=>({id:d.id,...d.data()})));const ruleSnapshot=await db.collection('settings').doc('accountingBankFeeRules').get();const closureSnapshot=await db.collection('accountingYearClosures').get(),closed=new Set(closureSnapshot.docs.map(d=>Number(d.id)));const open=r=>!require('./accountingYearClosure').accountingRecordYears(r).some(y=>closed.has(y));const plan=bankFeePlan(data[0].filter(open),data[1].filter(open),data[2],data[3],data[4],ruleSnapshot.exists?ruleSnapshot.data():{});if(plan.fees.length>100)throw new HttpsError('resource-exhausted','Zu viele Gebührenbelege für einen Abgleich.');const {isDeepStrictEqual}=require('node:util'),now=new Date().toISOString(),actor=request.auth.uid,records=[];for(const fee of plan.fees){const existing=data[2].find(r=>r.id===fee.id);if(existing&&existing.outgoingInvoiceId===fee.outgoingInvoiceId&&existing.sourcePdfArtifact)continue;const pdf=await generateBankFeePdf(fee),hash=sha(pdf),storagePath='accounting/incoming/'+hash+'.pdf';await bucket.file(storagePath).save(pdf,{resumable:false,contentType:'application/pdf',metadata:{cacheControl:'private, no-store'}});const record=existing?{...existing,outgoingInvoiceId:fee.outgoingInvoiceId,outgoingInvoiceNumber:fee.outgoingInvoiceNumber,description:bankFeeReceipt(fee,now,actor).description,updatedAt:now,updatedBy:actor}:bankFeeReceipt(fee,now,actor);record.sourcePdfArtifact={storagePath,sha256:hash,size:pdf.length,savedAt:now};records.push(record);}
const changedOutgoing=plan.outgoingUpdates.filter(p=>{const old=data[1].find(r=>r.id===p.id);return Object.entries(p).some(([k,v])=>k!=='id'&&!isDeepStrictEqual(old[k],v));});if(!records.length&&!changedOutgoing.length&&!plan.statementUpdates.length)return {created:0,updated:0,settled:0};
await db.runTransaction(async tx=>{const refs=snapshots.flatMap(s=>s.docs.map(d=>d.ref));const current=await tx.getAll(...refs);const originals=snapshots.flatMap(s=>s.docs);for(let i=0;i<current.length;i++)if(!current[i].exists||!current[i].updateTime.isEqual(originals[i].updateTime))throw new HttpsError('aborted','Buchhaltungsdaten geändert; bitte Abgleich erneut ausführen.');const newRefs=records.filter(r=>!data[2].some(old=>old.id===r.id)).map(r=>db.collection('accountingIncomingInvoices').doc(r.id));const newDocs=newRefs.length?await tx.getAll(...newRefs):[];if(newDocs.some(d=>d.exists))throw new HttpsError('aborted','Gebührenbeleg inzwischen erfasst.');await assertAccountingWritable(db,[...plan.statementUpdates.map(p=>data[0].find(r=>r.id===p.id)),...records,...changedOutgoing.map(p=>({...data[1].find(r=>r.id===p.id),...p}))],HttpsError,tx);for(const patch of plan.statementUpdates)tx.update(db.collection('accountingStatements').doc(patch.id),{rows:patch.rows});for(const record of records){tx.set(db.collection('accountingIncomingInvoices').doc(record.id),record);const fee=plan.fees.find(f=>f.id===record.id);if(!data[3].some(c=>c.id===fee.bookingKey))tx.create(db.collection('accountingPaymentMatches').doc(fee.bookingKey),{invoiceId:record.id,statementId:fee.statementId,rowIndex:fee.rowIndex,amountCents:-fee.amountCents,date:fee.date,createdAt:now,createdBy:actor});}for(const patch of changedOutgoing){const {id,...fields}=patch;tx.update(db.collection('membershipContributions').doc(id),fields);const key=patch.paymentMatch.bookingKey;if(!data[4].some(c=>c.id===key))tx.create(db.collection('accountingOutgoingPaymentMatches').doc(key),{invoiceId:id,statementId:patch.paymentMatch.statementId,rowIndex:patch.paymentMatch.rowIndex,amountCents:patch.paymentMatch.amountCents,date:patch.paidDate,createdAt:now,createdBy:actor});}});return {created:records.filter(r=>!data[2].some(old=>old.id===r.id)).length,updated:records.filter(r=>data[2].some(old=>old.id===r.id)).length,settled:changedOutgoing.length};};}
module.exports={bankFeePlan,bankFeeReceipt,generateBankFeePdf,createBankFeeReconciliation};
