const {assertAccountingWritable,accountingClosedYears,updateOpenAccountingRecord}=require('./accountingYearClosure');
const {drawInvoiceTemplate,TEMPLATE_VERSION,PAGE}=require('./accountingInvoiceTemplate');
const PDFDocument=require('pdfkit');
const {createHash}=require('node:crypto');
const {invoiceContentFingerprint,resolvedInvoice}=require('./accountingInvoiceRevision');
const {invoiceDispatchPlan,invoiceMailAttachment}=require('./accountingInvoiceDispatch');
const digest=value=>createHash('sha256').update(value).digest('hex');
function generateInvoicePdf(record){
 invoiceDispatchPlan(record);if(!record.street||!record.postalCode||!record.city)throw new Error('Straße, PLZ und Ort für die Rechnung fehlen.');
 return new Promise((resolve,reject)=>{const doc=new PDFDocument({size:[PAGE.width,PAGE.height],margin:0,info:{Title:'RECHNUNG '+record.invoiceNumber+' MB - '+record.memberName,Author:'PROdigitalTV'}}),chunks=[];doc.on('data',c=>chunks.push(c));doc.on('error',reject);doc.on('end',()=>resolve(Buffer.concat(chunks)));try{drawInvoiceTemplate(doc,record);doc.end();}catch(error){reject(error);doc.destroy();}});
}
function createInvoicePdfGeneration({db,bucket,requireAdmin,HttpsError}){return async request=>{
 await requireAdmin(request);const {invoiceId,action}=request.data||{};if(typeof invoiceId!=='string'||!invoiceId||invoiceId.includes('/')||!['generate','read'].includes(action))throw new HttpsError('invalid-argument','Ungültige PDF-Anfrage.');
 const ref=db.collection('membershipContributions').doc(invoiceId),snap=await ref.get();if(!snap.exists)throw new HttpsError('not-found','Rechnung nicht gefunden.');const record=snap.data();const member=record.memberId?(await db.collection('members').doc(record.memberId).get()).data()||{}:{};const resolved=resolvedInvoice(record,member);const fingerprint=invoiceContentFingerprint(resolved);
 if(action==='read'&&(await accountingClosedYears(db,[record])).length){const artifact=record.invoicePdfArtifact||record.sourcePdfArtifact;if(!artifact)throw new HttpsError('not-found','Im abgeschlossenen Jahr ist keine gespeicherte Rechnungs-PDF vorhanden.');const [attachment]=await invoiceMailAttachment({template:'accounting_invoice',invoiceAttachment:artifact},bucket);return {pdfBase64:attachment.content.toString('base64'),filename:attachment.filename};}
 if(action==='read'){if(record.historicalImport&&record.sourcePdfArtifact&&!record.invoicePdfArtifact){if(record.invoiceNeedsRegeneration)throw new HttpsError('failed-precondition','Rechnung geändert. Bitte neu erzeugen.');if(record.sourcePdfArtifact.sha256!==record.sourceHash)throw new HttpsError('data-loss','Original-PDF passt nicht zum gespeicherten Beleg.');const [attachment]=await invoiceMailAttachment({template:'accounting_invoice',invoiceAttachment:record.sourcePdfArtifact},bucket);return {pdfBase64:attachment.content.toString('base64'),filename:attachment.filename};}if(record.invoiceNeedsRegeneration||record.invoicePdfArtifact?.fingerprint!==fingerprint||record.invoicePdfArtifact?.templateVersion!==TEMPLATE_VERSION)throw new HttpsError('failed-precondition','PDF ist veraltet. Bitte neu erzeugen.');const [attachment]=await invoiceMailAttachment({template:'accounting_invoice',invoiceAttachment:record.invoicePdfArtifact},bucket);return {pdfBase64:attachment.content.toString('base64'),filename:attachment.filename};}
 await assertAccountingWritable(db,[record],HttpsError);
 let pdf;try{pdf=await generateInvoicePdf(resolved);}catch(error){throw new HttpsError('failed-precondition',error.message);}
 const artifact={templateVersion:TEMPLATE_VERSION,storagePath:`accounting-mail/${digest(invoiceId)}/${digest(pdf)}.pdf`,sha256:digest(pdf),filename:`Rechnung-${record.invoiceNumber.replace(/[^a-zA-Z0-9_.-]/g,'_')}-v${Number(record.invoiceRevision||0)+1}.pdf`,fingerprint,revision:Number(record.invoiceRevision||0),generatedAt:new Date().toISOString(),generatedBy:request.auth.uid};await bucket.file(artifact.storagePath).save(pdf,{resumable:false,contentType:'application/pdf'});
 await db.runTransaction(async tx=>{const fresh=await tx.get(ref);const latest=fresh.data();await assertAccountingWritable(db,[latest],HttpsError,tx);const currentMember=latest.memberId?(await tx.get(db.collection('members').doc(latest.memberId))).data()||{}:{};if(invoiceContentFingerprint(resolvedInvoice(latest,currentMember))!==fingerprint||Number(latest.invoiceRevision||0)!==artifact.revision)throw new HttpsError('failed-precondition','Rechnung wurde inzwischen geändert. Bitte erneut erzeugen.');tx.update(ref,{invoicePdfArtifact:artifact,invoiceNeedsRegeneration:false,invoiceNeedsRedispatch:true});});
 return {pdfBase64:pdf.toString('base64'),filename:artifact.filename};
};}
module.exports={generateInvoicePdf,createInvoicePdfGeneration};
