function accountingRecordYears(record={}){
 const year=Number(record.accountingPeriodYear||record.year||String(record.invoiceDate||record.date||record.periodFrom||'').slice(0,4)),years=new Set();
 if(Number.isInteger(year)&&year>=2000&&year<=2100)years.add(year);
 const paid=Number(String(record.paymentMatch?.date||record.paidDate||'').slice(0,4));if(paid>=2000&&paid<=2100)years.add(paid);
 if(record.periodFrom&&record.periodTo){const start=Number(record.periodFrom.slice(0,4)),end=Number(record.periodTo.slice(0,4));for(let y=start;y<=end&&y<=2100&&y-start<101;y++)if(y>=2000)years.add(y);}
 return [...years];
}
async function accountingClosedYears(db,records,tx){const years=[...new Set(records.flatMap(accountingRecordYears))],closed=[];for(const year of years){const ref=db.collection('accountingYearClosures').doc(String(year)),snapshot=tx?await tx.get(ref):await ref.get();if(snapshot.exists)closed.push(year);}return closed;}
async function assertAccountingWritable(db,records,HttpsError,tx){const closed=await accountingClosedYears(db,records,tx);if(closed.length){const message='Buchhaltungsjahr '+closed.join(', ')+' ist abgeschlossen. Ansehen, Drucken und Exportieren bleiben möglich.';throw HttpsError?new HttpsError('failed-precondition',message):Object.assign(new Error(message),{code:'failed-precondition'});}}
async function updateOpenAccountingRecord(db,ref,patch,HttpsError){return db.runTransaction(async tx=>{const snapshot=await tx.get(ref);if(!snapshot.exists)return;await assertAccountingWritable(db,[snapshot.data()],HttpsError,tx);tx.update(ref,patch);});}
function createAccountingYearClosure({db,requireAdmin,HttpsError}){return async request=>{await requireAdmin(request);const {pinRef,historyRef,createPinRecord}=require('./accountingYearPin');const year=Number(request.data?.year),now=new Date().toISOString(),currentYear=Number(new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Berlin',year:'numeric'}).format(new Date()));if(!Number.isInteger(year)||year<2000||year>=currentYear||request.data?.confirm!==true)throw new HttpsError('invalid-argument','Nur vergangene Buchhaltungsjahre dürfen abgeschlossen werden.');return db.runTransaction(async tx=>{const ref=db.collection('accountingYearClosures').doc(String(year)),securityRef=pinRef(db),[snapshot,security]=await Promise.all([tx.get(ref),tx.get(securityRef)]);if(snapshot.exists)return {...snapshot.data(),alreadyClosed:true};if(security.exists&&request.data?.pin!==undefined)throw new HttpsError('failed-precondition','Die gemeinsame PIN wurde inzwischen festgelegt. Bitte das Abschlussfenster erneut öffnen.');let initialPin;if(!security.exists){try{initialPin=createPinRecord(request.data?.pin,request.auth.uid,now);}catch(error){throw new HttpsError('failed-precondition',error.message);}}const closure={year,closedAt:now,closedBy:request.auth.uid,status:'closed'};if(initialPin)tx.create(securityRef,initialPin);tx.create(ref,closure);tx.create(historyRef(db),{year,action:'close',at:now,by:request.auth.uid,closure});return closure;});};}
module.exports={accountingRecordYears,accountingClosedYears,assertAccountingWritable,updateOpenAccountingRecord,createAccountingYearClosure};
