const {randomBytes,scryptSync,timingSafeEqual,randomUUID}=require('node:crypto');
const PIN_COLLECTION='accountingYearSecurity',PIN_ID='sharedPin';
function createPinRecord(pin,actor,now){if(typeof pin!=='string'||!/^\d{6}$/.test(pin))throw Error('Bitte eine PIN mit genau sechs Ziffern festlegen.');const salt=randomBytes(16).toString('hex');return {salt,hash:scryptSync(pin,salt,32).toString('hex'),createdAt:now,createdBy:actor,failedAttempts:0,lockedUntilMs:0};}
function pinMatches(pin,record){if(typeof pin!=='string'||!/^\d{6}$/.test(pin)||!/^([a-f0-9]{2}){32}$/.test(record.hash||'')||!/^([a-f0-9]{2}){16}$/.test(record.salt||''))return false;return timingSafeEqual(scryptSync(pin,record.salt,32),Buffer.from(record.hash,'hex'));}
function pinRef(db){return db.collection(PIN_COLLECTION).doc(PIN_ID);}
function historyRef(db){return db.collection('accountingYearClosureHistory').doc(randomUUID());}
function createYearPinStatus({db,requireAdmin}){return async request=>{await requireAdmin(request);return {configured:(await pinRef(db).get()).exists};};}
function createAccountingYearPinSetup({db,requireAdmin,HttpsError}){return async request=>{await requireAdmin(request);let record;try{record=createPinRecord(request.data?.pin,request.auth.uid,new Date().toISOString());}catch(error){throw new HttpsError('invalid-argument',error.message);}return db.runTransaction(async tx=>{const ref=pinRef(db),snapshot=await tx.get(ref);if(snapshot.exists)throw new HttpsError('failed-precondition','Die gemeinsame PIN wurde bereits festgelegt. Bitte das Fenster erneut öffnen und die vorhandene PIN zum Entsperren verwenden.');tx.create(ref,record);tx.create(historyRef(db),{action:'pin_setup',at:record.createdAt,by:request.auth.uid});return {configured:true};});};}
function createAccountingYearUnlock({db,requireAdmin,HttpsError,clock=()=>Date.now(),closing=false}){return async request=>{await requireAdmin(request);const year=Number(request.data?.year),pin=request.data?.pin;if(!Number.isInteger(year)||year<2000||year>2100||typeof pin!=='string'||!/^\d{6}$/.test(pin))throw new HttpsError('invalid-argument','Bitte das Jahr und eine PIN mit genau sechs Ziffern angeben.');if(closing&&(request.data?.confirm!==true||year>=Number(new Intl.DateTimeFormat('en',{timeZone:'Europe/Berlin',year:'numeric'}).format(new Date(clock())))))throw new HttpsError('invalid-argument','Nur vergangene Buchhaltungsjahre dürfen abgeschlossen werden.');const result=await db.runTransaction(async tx=>{const securityRef=pinRef(db),ref=db.collection('accountingYearClosures').doc(String(year)),[security,snapshot]=await Promise.all([tx.get(securityRef),tx.get(ref)]);if(!security.exists)return {error:'failed-precondition',message:'Die gemeinsame PIN wurde noch nicht festgelegt.'};const stored=security.data(),nowMs=clock(),now=new Date(nowMs).toISOString();if(Number(stored.lockedUntilMs||0)>nowMs)return {error:'resource-exhausted',message:'Zu viele falsche PIN-Eingaben. Bitte nach 15 Minuten erneut versuchen.'};if(!pinMatches(pin,stored)){const attempts=(Number(stored.lockedUntilMs||0)&&Number(stored.lockedUntilMs)<=nowMs?0:Number(stored.failedAttempts||0))+1;tx.update(securityRef,{failedAttempts:attempts,lockedUntilMs:attempts>=5?nowMs+15*60*1000:0});return {error:attempts>=5?'resource-exhausted':'permission-denied',message:attempts>=5?'Zu viele falsche PIN-Eingaben. Bitte nach 15 Minuten erneut versuchen.':'Die PIN ist falsch. Das Jahr bleibt abgeschlossen.'};}if(closing){tx.update(securityRef,{failedAttempts:0,lockedUntilMs:0});if(snapshot.exists)return {...snapshot.data(),alreadyClosed:true};const closure={year,closedAt:now,closedBy:request.auth.uid,status:'closed'};tx.create(ref,closure);tx.create(historyRef(db),{year,action:'close',at:now,by:request.auth.uid,closure});return closure;}if(!snapshot.exists)return {year,status:'open',alreadyOpen:true};const closure=snapshot.data();tx.update(securityRef,{failedAttempts:0,lockedUntilMs:0});tx.create(historyRef(db),{year,action:'unlock',at:now,by:request.auth.uid,closure,reason:String(request.data?.reason||'').trim().slice(0,1000)});tx.delete(ref);return {year,status:'open',unlockedAt:now,unlockedBy:request.auth.uid};});if(result.error)throw new HttpsError(result.error,result.message);return result;};}
module.exports={createPinRecord,pinMatches,pinRef,historyRef,createYearPinStatus,createAccountingYearPinSetup,createAccountingYearUnlock};
