const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');
const source=fs.readFileSync(require('node:path').join(__dirname,'index.js'),'utf8');const handler=source.slice(source.indexOf('exports.deletePortalParticipantPhoto ='),source.indexOf('exports.markPortalParticipantPhotosSeen ='));
class HttpsError extends Error{constructor(code,message){super(message);this.code=code;}}
function setup(overrides={},storageFails=false,accessFails=false){const actions=[];const medium={uploadedBy:'owner',eventId:'event',source:'portal-gallery-upload',mediaType:'image',status:'uploaded',storagePath:'portal-gallery-photos/owner/photo/test.jpg',...overrides};const c=vm.createContext({exports:{},region:'test',onCall:(_,fn)=>fn,HttpsError,clean:v=>String(v||'').trim(),participantPhotoRecord:m=>m.source==='portal-gallery-upload'&&m.mediaType==='image',requireParticipantPhotoAccess:async()=>{if(accessFails)throw new HttpsError('permission-denied','Eventzugang fehlt');},db:{collection:()=>({doc:()=>({get:async()=>({exists:true,data:()=>medium}),delete:async()=>actions.push('record')})})},storageBucket:'test',getStorage:()=>({bucket:()=>({file:()=>({delete:async()=>{if(storageFails)throw Error('storage unavailable');actions.push('file');}})})})});vm.runInContext(handler,c);return{actions,remove:c.exports.deletePortalParticipantPhoto};}
const request={auth:{uid:'owner',token:{email_verified:true}},data:{mediaId:'photo',eventId:'event'}};
test('owner removes file and gallery record',async()=>{const s=setup();await s.remove(request);assert.deepEqual(s.actions,['file','record']);});
test('foreign owner and wrong event are rejected before deleting',async()=>{for(const changes of [{uploadedBy:'other'},{eventId:'other'},{storagePath:'private/secret.jpg'}]){const s=setup(changes);await assert.rejects(s.remove(request));assert.deepEqual(s.actions,[]);}});
test('unverified or unauthorised event access cannot delete',async()=>{const s=setup({},false,true);await assert.rejects(s.remove(request));assert.deepEqual(s.actions,[]);const t=setup();await assert.rejects(t.remove({...request,auth:null}));assert.deepEqual(t.actions,[]);});
test('storage failure preserves record for retry',async()=>{const s=setup({},true);await assert.rejects(s.remove(request),/storage unavailable/);assert.deepEqual(s.actions,[]);});
