import {loadClosedAccountingYears,accountingRecordIsClosed} from './accountingYearClosure.js?v=8';
import {getFirebaseServices} from '../firebase/firebaseClient.js?v=3';
import {consolidatePartnerIbans} from './accountingPartnerIbans.js?v=1';
// Firestore does not guarantee object field order across reads.
const canonicalData=value=>JSON.stringify(value,(_key,item)=>item&&typeof item==='object'&&!Array.isArray(item)?Object.fromEntries(Object.keys(item).sort().map(key=>[key,item[key]])):item);
const sameData=(left,right)=>canonicalData(left)===canonicalData(right);
let active;
export function reconcilePartnerIbans(){if(!active)active=run().finally(()=>{active=null;});return active;}
async function run(){const f=await getFirebaseServices();if(!f)throw Error('Firebase nicht erreichbar.');const names=['accountingIncomingInvoices','membershipContributions','accountingStatements','members'],snapshots=await Promise.all(names.map(c=>f.firestore.getDocs(f.firestore.collection(f.db,c)))),data=snapshots.map(s=>s.docs.map(d=>({id:d.id,...d.data()}))),ref=f.firestore.doc(f.db,'settings','accountingPartners'),registrySnapshot=await f.firestore.getDoc(ref),registry=registrySnapshot.data()||{},closed=await loadClosedAccountingYears(f),plan=consolidatePartnerIbans(registry,{incoming:data[0].filter(record=>!accountingRecordIsClosed(record,closed)),outgoing:data[1].filter(record=>!accountingRecordIsClosed(record,closed)),statements:data[2],members:data[3]}),updates=[...plan.invoiceUpdates,...plan.memberUpdates.map(p=>({...p,collection:'members'}))];if(!updates.length&&sameData(plan.registry,registry))return {merged:0,updated:0};if(updates.length>400)throw Error('Zu viele Datensätze für einen gemeinsamen Abgleich.');await f.firestore.runTransaction(f.db,async tx=>{const currentRegistry=await tx.get(ref);if(!sameData(currentRegistry.data()||{},registry))throw Error('Partnerliste wurde geändert. Bitte Abgleich erneut ausführen.');const refs=updates.map(p=>f.firestore.doc(f.db,p.collection,p.id)),current=await Promise.all(refs.map(r=>tx.get(r)));for(let i=0;i<updates.length;i++){const baseline=snapshots[names.indexOf(updates[i].collection)].docs.find(d=>d.id===updates[i].id);if(!current[i].exists()||!sameData(current[i].data(),baseline.data()))throw Error('Buchung wurde geändert. Bitte Abgleich erneut ausführen.');}// Imported bank rows are immutable under Firestore rules; partner links are stored on invoices.
const updatedAt=new Date().toISOString(),updatedBy=f.auth.currentUser.uid;updates.forEach((p,i)=>tx.update(refs[i],{...p.patch,updatedAt,updatedBy}));tx.set(ref,plan.registry);});return {merged:plan.merges.length,updated:updates.length};}
