import {getFirebaseServices} from '../firebase/firebaseClient.js?v=3';
import {callEventModerator} from '../firebase/eventModeratorService.js?v=1';
export function accountingLockYears(record={}){const year=Number(record.accountingPeriodYear||record.year||String(record.invoiceDate||record.date||record.periodFrom||'').slice(0,4)),years=new Set();if(Number.isInteger(year)&&year>=2000&&year<=2100)years.add(year);const paid=Number(String(record.paymentMatch?.date||record.paidDate||'').slice(0,4));if(paid>=2000&&paid<=2100)years.add(paid);if(record.periodFrom&&record.periodTo){const start=Number(record.periodFrom.slice(0,4)),end=Number(record.periodTo.slice(0,4));for(let y=start;y<=end&&y<=2100&&y-start<101;y++)if(y>=2000)years.add(y);}return [...years].join(',');}
export async function mountAccountingYearClosure(host){
 if(!host)return;const f=await getFirebaseServices();if(!f)return;let closures=new Map(),ready=false,stopped=false;const yearInput=host.querySelector('[data-overview-year]'),status=host.querySelector('[data-year-closure-status]'),button=host.querySelector('[data-close-accounting-year]');
 const apply=()=>{if(stopped)return;for(const row of document.querySelectorAll('[data-accounting-lock-years]')){const years=row.dataset.accountingLockYears.split(',').filter(Boolean),closed=years.some(year=>closures.has(year));const locked=!ready||closed;for(const control of row.querySelectorAll('[data-accounting-edit],[data-incoming-edit],[data-bank-account],[data-incoming-account],[data-accounting-account],[data-overview-account-select],[data-partner-reassign],[data-outgoing-select],[data-outgoing-actions] button,[data-overview-plan] button,[data-overview-plan] input')){if(locked){if(!control.dataset.yearLockDisabled){control.dataset.yearLockWasDisabled=control.disabled?'yes':'no';control.dataset.yearLockDisabled='yes';}if(!control.disabled)control.disabled=true;control.title=closed?'Buchhaltungsjahr abgeschlossen · nur Lesen':'Jahresstatus wird geprüft';}else if(control.dataset.yearLockDisabled){control.disabled=control.dataset.yearLockWasDisabled==='yes';delete control.dataset.yearLockDisabled;delete control.dataset.yearLockWasDisabled;control.removeAttribute('title');}}}
 if(yearInput&&button){const year=String(yearInput.value),closure=closures.get(year),currentYear=Number(new Intl.DateTimeFormat('en',{timeZone:'Europe/Berlin',year:'numeric'}).format(new Date())),canClose=Number(year)>=2000&&Number(year)<currentYear;button.disabled=!ready||(!closure&&!canClose);const state=closure?'closed':'open';if(button.dataset.lockState!==state){button.dataset.lockState=state;button.innerHTML=yearLockIcon(Boolean(closure));if(status.textContent)status.textContent='';}button.title=closure?'Jahr '+year+' entsperren':canClose?'Jahr '+year+' abschließen':'Das laufende Jahr kann nicht abgeschlossen werden';button.setAttribute('aria-label',button.title);const form=host.querySelector('[data-overview-plan]');if(form)form.dataset.accountingLockYears=year;}
 };
 const observer=new MutationObserver(()=>{if(!host.isConnected){stopped=true;unsubscribe();observer.disconnect();return;}apply();});let unsubscribe=()=>{};observer.observe(document.body,{childList:true,subtree:true});
 unsubscribe=f.firestore.onSnapshot(f.firestore.collection(f.db,'accountingYearClosures'),snapshot=>{closures=new Map(snapshot.docs.map(d=>[d.id,d.data()]));ready=true;apply();},error=>{ready=false;if(status)status.textContent='Jahresstatus konnte nicht geladen werden: '+error.message;if(button)button.disabled=true;});
 yearInput?.addEventListener('change',apply);if(button)button.onclick=async()=>{const year=Number(yearInput.value),closed=closures.has(String(year));if(button.disabled)return;button.disabled=true;try{const configured=(await callEventModerator('accountingYearPinStatus')).configured;if(closed){openYearPinDialog({year,unlock:true,setup:!configured,onComplete:()=>{closures.delete(String(year));apply();}});return;}openYearPinDialog({year,setup:!configured,onComplete:closure=>{closures.set(String(year),closure);apply();}});}catch(error){status.textContent=error.message;}finally{apply();}};
 apply();return ()=>{stopped=true;unsubscribe();observer.disconnect();};
}

export async function loadClosedAccountingYears(f){const snapshots=await f.firestore.getDocs(f.firestore.collection(f.db,'accountingYearClosures'));return new Set(snapshots.docs.map(d=>d.id));}
export function accountingRecordIsClosed(record,closed){return accountingLockYears(record).split(',').some(y=>closed.has(y));}

function yearLockIcon(closed){return '<svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" aria-hidden="true"><rect x="5" y="10" width="14" height="11" rx="2"/>'+ (closed?'<path d="M8 10V6a4 4 0 0 1 8 0v4"/>':'<path d="M8 10V6a4 4 0 0 1 8 0"/>')+'<path d="M12 14v3"/></svg>';}
export function openYearPinDialog({year,unlock=false,setup=false,onComplete=()=>{}}){
 const dialog=document.createElement('dialog');dialog.style.cssText='width:min(320px,92vw);border:1px solid #dce4ef;border-radius:16px;padding:16px';dialog.setAttribute('aria-label',unlock?'Jahr '+year+' entsperren':'Jahr '+year+' abschließen');
 dialog.innerHTML='<form style="display:flex;align-items:center;gap:8px;flex-wrap:wrap"><input name="pin" aria-label="'+(setup?'Neue PIN festlegen':'PIN')+'" placeholder="'+(setup?'Neue PIN · 6 Stellen':'PIN · 6 Stellen')+'" type="password" inputmode="numeric" pattern="[0-9]{6}" minlength="6" title="PIN mit genau sechs Ziffern" maxlength="6" autocomplete="'+(setup?'new-password':'off')+'" required style="flex:1;min-width:100px;width:130px"><button type="submit" aria-label="'+(unlock?'Entsperren':'Abschließen')+'" title="'+(unlock?'Entsperren':'Abschließen')+'" class="button button--secondary" style="padding:8px"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="m5 12 4 4L19 6"/></svg></button><button type="button" aria-label="Abbrechen" title="Abbrechen" data-close class="button button--secondary" style="padding:8px"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" aria-hidden="true"><path d="m6 6 12 12M18 6 6 18"/></svg></button><p role="status" aria-live="polite" style="margin:0;font-size:13px;width:100%"></p></form>';
 let busy=false,smsMode=false,challengeId='',firstPin='';const form=dialog.querySelector('form'),input=dialog.querySelector('[name=pin]'),feedback=dialog.querySelector('[role=status]');
 if(unlock){const smsButton=document.createElement('button');smsButton.type='button';smsButton.className='button button--secondary';smsButton.style.padding='8px';smsButton.title='Code per SMS senden';smsButton.setAttribute('aria-label',smsButton.title);smsButton.innerHTML='<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" aria-hidden="true"><rect x="6" y="2" width="12" height="20" rx="2"/><path d="M10 18h4"/></svg>';form.insertBefore(smsButton,feedback);smsButton.onclick=async()=>{if(busy)return;busy=true;const controls=dialog.querySelectorAll('button,input');controls.forEach(c=>c.disabled=true);feedback.textContent='SMS wird gesendet …';try{const result=await callEventModerator('requestAccountingYearSms',{year});challengeId=result.challengeId;smsMode=true;firstPin='';input.value='';input.placeholder='SMS-Code';input.pattern='[0-9]{6}';input.minLength=6;input.title='SMS-Code mit sechs Ziffern';input.setAttribute('aria-label','SMS-Code');input.autocomplete='one-time-code';feedback.textContent='An '+result.phoneMasked+' · 10 Minuten gültig';}catch(error){feedback.textContent=error.message;}finally{busy=false;controls.forEach(c=>c.disabled=false);input.focus();}};}
 document.body.append(dialog);dialog.showModal();dialog.querySelector('[data-close]').onclick=()=>dialog.close();dialog.addEventListener('cancel',event=>{if(busy)event.preventDefault();});dialog.addEventListener('close',()=>{firstPin='';form.reset();dialog.remove();},{once:true});input.focus();
 form.onsubmit=async event=>{event.preventDefault();if(busy)return;const pin=input.value;if(setup&&!smsMode&&!firstPin){firstPin=pin;input.value='';input.placeholder='PIN wiederholen · 6 Stellen';input.setAttribute('aria-label','PIN wiederholen');input.focus();return;}if(setup&&!smsMode&&pin!==firstPin){firstPin='';input.value='';input.placeholder='Neue PIN · 6 Stellen';feedback.textContent='PIN stimmt nicht überein.';input.focus();return;}busy=true;const controls=dialog.querySelectorAll('button,input');controls.forEach(c=>c.disabled=true);feedback.textContent='…';try{if(unlock&&setup&&!smsMode)await callEventModerator('setupAccountingYearPin',{pin});const result=smsMode?await callEventModerator('unlockAccountingYearSms',{year,code:pin,challengeId}):await callEventModerator(unlock?'unlockAccountingYear':setup?'closeAccountingYear':'closeAccountingYearWithPin',{year,pin,...(!unlock?{confirm:true}:{})});onComplete(result);dialog.close();}catch(error){feedback.textContent=error.message;}finally{busy=false;controls.forEach(c=>c.disabled=false);}};
 return dialog;
}
