import {callEventModerator} from '../firebase/eventModeratorService.js?v=1';
import {accountingFolderHandle} from './accountingFolders.js?v=16';
import {invoicePdfFile} from './accountingInvoicePdf.js?v=9';
import {escapeHtml} from './format.js?v=4';
const pdfBase64=file=>new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=()=>reject(new Error('PDF konnte nicht gelesen werden.'));reader.readAsDataURL(file);});
export function openInvoiceDispatch(userId,record){
 const dialog=document.createElement('dialog');dialog.style.cssText='width:min(960px,94vw);max-height:90dvh;overflow:auto;border:1px solid #dce4ef;border-radius:8px;padding:24px';
 dialog.innerHTML='<h2>Rechnung senden</h2><div data-dispatch-content></div><p role="status" data-dispatch-status>Rechnung und PDF werden geladen ...</p><button type="button" class="button button--secondary" data-dispatch-close>Schliessen</button>';
 document.body.append(dialog);dialog.showModal();let url,file,plan,busy=true;
 const $=s=>dialog.querySelector(s);const controls=()=>{dialog.querySelectorAll('button,input,textarea').forEach(el=>el.disabled=busy);if($('[data-dispatch-send]'))$('[data-dispatch-send]').disabled=busy||!file||!$('[data-dispatch-confirm]').checked;};
 $('[data-dispatch-close]').onclick=()=>{if(!busy)dialog.close();};dialog.addEventListener('cancel',e=>{if(busy)e.preventDefault();});dialog.addEventListener('close',()=>{if(url)URL.revokeObjectURL(url);dialog.remove();},{once:true});
 const history=()=>plan.history.map(item=>`<details><summary>${escapeHtml(item.queuedAt.slice(0,10).split('-').reverse().join('.'))} · ${escapeHtml(({queued:'In Versandwarteschlange',sent:'Versendet',failed:'Versand fehlgeschlagen',skipped:'Uebersprungen'})[item.status]||item.status)}</summary><p>${escapeHtml(item.to)} · ${escapeHtml(item.subject)}</p><pre style="white-space:pre-wrap;overflow-wrap:anywhere">${escapeHtml(item.text)}</pre></details>`).join('')||'<p>Noch kein Rechnungsversand erfasst.</p>';
 const render=()=>{
  $('[data-dispatch-content]').innerHTML=`<p>Rechnung <strong>${escapeHtml(plan.invoiceNumber)}</strong></p><div class="form-grid"><div class="field"><label>Empfaenger</label><input readonly value="${escapeHtml(plan.to)}"></div><div class="field"><label>Betreff</label><input data-dispatch-subject maxlength="250" value="${escapeHtml(plan.subject)}"></div><div class="field"><label>Mailtext</label><textarea data-dispatch-text rows="9">${escapeHtml(plan.text)}</textarea></div></div><p>PDF-Anhang: <strong>${escapeHtml(file.name)}</strong></p><iframe title="Rechnungs-PDF" src="${url}" style="width:100%;height:360px;border:1px solid #dce4ef"></iframe><p><label><input type="checkbox" data-dispatch-confirm> PDF geprueft: Rechnungsnummer, Empfaenger und Betrag stimmen.</label></p><button type="button" class="button button--primary" data-dispatch-send>Rechnung mit PDF versenden</button><h3>Versandhistorie</h3><div data-dispatch-history>${history()}</div>`;
  $('[data-dispatch-confirm]').onchange=controls;
  $('[data-dispatch-send]').onclick=async()=>{if(busy)return;busy=true;controls();try{await callEventModerator('accountingInvoiceDispatch',{action:'send',invoiceId:record.id,expectedFingerprint:plan.fingerprint,subject:$('[data-dispatch-subject]').value,text:$('[data-dispatch-text]').value,pdfConfirmed:$('[data-dispatch-confirm]').checked,pdfBase64:await pdfBase64(file)});$('[data-dispatch-status]').textContent='Rechnung mit PDF an den Mailversand uebergeben.';plan=await callEventModerator('accountingInvoiceDispatch',{action:'preview',invoiceId:record.id});$('[data-dispatch-history]').innerHTML=history();$('[data-dispatch-confirm]').checked=false;}catch(error){$('[data-dispatch-status]').textContent=error.message||'Versand fehlgeschlagen.';}finally{busy=false;controls();}};
 };
 controls();(async()=>{try{plan=await callEventModerator('accountingInvoiceDispatch',{action:'preview',invoiceId:record.id});const handle=await accountingFolderHandle(userId,'outgoing');file=await invoicePdfFile(handle,record);if(file.size>5*1024*1024)throw new Error('Bitte eine Rechnungs-PDF mit maximal 5 MB verwenden.');url=URL.createObjectURL(file);if(dialog.open){render();$('[data-dispatch-status]').textContent='';}}catch(error){$('[data-dispatch-status]').textContent=error.message||'Rechnung konnte nicht geladen werden.';}finally{busy=false;controls();}})();
}
