import {extractIban} from './bankStatementParser.js?v=6';
export function partnerBankIban(record,statements=[]){const match=record.paymentMatch,statement=statements.find(s=>(s.id||s.sourceHash)===match?.statementId),row=statement?.rows?.[match?.rowIndex];return row?extractIban(row.iban||row.details||''):extractIban(record.counterpartyIban||record.iban||'');}
export function consolidatePartnerIbans(registry,{incoming=[],outgoing=[],statements=[],members=[]}={}){
 registry=structuredClone(registry);const partners=registry.partners||{},parent=new Map(),ibans=new Map(),records=[];
 const root=id=>{while(parent.has(id)&&parent.get(id)!==id)id=parent.get(id);return id;};
 for(const [kind,list,collection] of [['creditor',incoming,'accountingIncomingInvoices'],['debtor',outgoing,'membershipContributions']])for(const record of list){if(record.archived||record.isInternalBookingReceipt||record.partnerAssignmentCorrection)continue;const partner=partners[record.accountingPartnerId];if(!partner||partner.kind!==kind)continue;const iban=partnerBankIban(record,statements);if(!iban)continue;const invoiceIban=extractIban(record.counterpartyIban||record.iban||'');if(kind==='creditor'&&(!invoiceIban||invoiceIban!==iban)&&!partner.ibans?.includes(iban))continue;const id=partner.id;parent.set(id,parent.get(id)||id);const key=kind+':'+iban,old=ibans.get(key);if(old&&root(old)!==root(id)){const a=root(old),b=root(id),winner=Number(partners[a].number)<=Number(partners[b].number)?a:b;parent.set(winner===a?b:a,winner);}ibans.set(key,id);const match=record.paymentMatch,row=statements.find(s=>s.id===match?.statementId)?.rows?.[match?.rowIndex];records.push({record,kind,collection,iban,row});}
 const merges=[];for(const id of parent.keys()){const target=root(id);if(id!==target){partners[id].mergedInto=target;merges.push({from:id,to:target,oldNumber:partners[id].number,number:partners[target].number});}}
 for(const {record,iban}of records){const p=partners[root(record.accountingPartnerId)];p.ibans=[...new Set([...(p.ibans||[]),iban])];}
 for(const target of new Set(merges.map(m=>m.to))){const p=partners[target],sources=records.filter(r=>root(r.record.accountingPartnerId)===target&&r.row).sort((a,b)=>(b.row.date||'').localeCompare(a.row.date||'')),name=String(sources[0]?.row.originalDescription||sources[0]?.row.description||'').split(/\s+(?:BIC|IBAN)\b/i)[0].trim();if(name){p.previousNames=[...new Set([...(p.previousNames||[]),p.name,...merges.filter(m=>m.to===target).map(m=>partners[m.from].name)])];p.name=name;}}
 const invoiceUpdates=[];for(const [kind,list,collection]of [['creditor',incoming,'accountingIncomingInvoices'],['debtor',outgoing,'membershipContributions']])for(const record of list){if(record.isInternalBookingReceipt)continue;const target=root(record.accountingPartnerId),p=partners[target];if(!p||p.kind!==kind)continue;const key=kind==='creditor'?'creditorNumber':'debtorNumber';if(record.accountingPartnerId!==target||record[key]!==p.number)invoiceUpdates.push({collection,id:record.id,patch:{accountingPartnerId:target,[key]:p.number}});}
 const updatedRecord=new Map([...incoming,...outgoing].map(r=>[r.id,{...r,...invoiceUpdates.find(p=>p.id===r.id)?.patch}]));const statementUpdates=[];
 for(const statement of statements){let changed=false;const rows=statement.rows.map((row,index)=>{if(row.bankFeeDerived||row.accountNumber==='2703')return row;const record=[...incoming,...outgoing].find(r=>!r.archived&&!r.isInternalBookingReceipt&&r.paymentMatch?.statementId===statement.id&&r.paymentMatch.rowIndex===index),kind=row.amountCents<0?'creditor':'debtor',iban=extractIban(row.iban||row.details||''),id=record?updatedRecord.get(record.id)?.accountingPartnerId:root(ibans.get(kind+':'+iban)),p=partners[id];if(!p||p.kind!==kind)return row;const key=kind==='creditor'?'creditorNumber':'debtorNumber';if(row.accountingPartnerId===p.id&&row[key]===p.number)return row;changed=true;return {...row,...(iban?{iban}:{}),accountingPartnerId:p.id,[key]:p.number};});if(changed)statementUpdates.push({id:statement.id,patch:{rows}});}
 const memberUpdates=[];for(const member of members){const target=root(member.accountingPartnerId),p=partners[target];if(p?.kind==='debtor'&&(target!==member.accountingPartnerId||member.debtorNumber!==p.number))memberUpdates.push({id:member.id,patch:{accountingPartnerId:target,debtorNumber:p.number}});}
 return {registry,merges,invoiceUpdates,statementUpdates,memberUpdates,identifiedIbans:ibans.size};
}
