import {escapeHtml} from './format.js?v=4';
export const accountingFolderCategories=[['outgoing','Ausgangsrechnungen'],['incoming','Eingangsrechnungen'],['statements','Kontoauszüge']];
export function accountingFolderKey(userId,category){if(!userId||!accountingFolderCategories.some(([id])=>id===category))throw new Error('Ungültige Ordnerzuordnung.');return `${userId}:${category}`;}
export function accountingFoldersMarkup(category='',showStatus=true){const categories=category?accountingFolderCategories.filter(([id])=>id===category):accountingFolderCategories;return `<section class="panel"><div class="${category?'form-grid':'form-grid--three'}">${categories.map(([id,label])=>`<details data-accounting-folder-assignment="${id}"><summary data-accounting-folder-summary="${id}">Ordner zuweisen · ${label}</summary><section><div class="field"><label for="accounting-path-${id}">${label} · gemeinsamer Zielpfad</label><input id="accounting-path-${id}" data-accounting-folder-path="${id}" placeholder="Wird bei der Ordnerauswahl übernommen"><small>Ein vorhandener Zielpfad wird automatisch übernommen.</small></div><button type="button" class="button button--primary button--small" data-accounting-folder-pick="${id}" title="Ordner auswählen, zentral zuordnen, Zugriff freigeben und auf diesem Gerät speichern">Ordner zuweisen</button><details data-accounting-folder-alternative="${id}"><summary>Alternative: PDF-Dateien auswählen</summary><label>PDFs aus diesem Ordner auswählen<input type="file" multiple accept="application/pdf,.pdf" data-accounting-folder-files="${id}"></label><small>Die Dateien werden für diese Sitzung freigegeben. Die zentrale Ordnerzuordnung bleibt erhalten.</small></details><p data-accounting-folder-central="${id}">Zentrale Zuordnung wird geladen …</p><p data-accounting-folder-name="${id}">Auf diesem Gerät noch nicht freigegeben</p><details data-accounting-folder-browser="${id}" hidden><summary>Dateien im Ordner</summary><div data-accounting-folder-list="${id}"></div></details></section></details><p data-accounting-folder-feedback="${id}" role="status" aria-live="polite"></p>`).join('')}</div><small class="muted">Die Zuordnung gilt für alle Rechner. Auf einem neuen Rechner den Ordner einmal über denselben Button freigeben. Dateien bleiben erhalten.</small>${showStatus?'<p data-accounting-folder-status role="status" aria-live="polite"></p>':''}</section>`;}
export async function ensureFolderPermission(handle,mode='read'){let state=await handle.queryPermission({mode});if(state!=='granted')state=await handle.requestPermission({mode});if(state!=='granted')throw new Error('Der Ordnerzugriff wurde nicht freigegeben.');}
function openFolderStore(){return new Promise((resolve,reject)=>{const request=indexedDB.open('pdtv-accounting-folders',1);request.onupgradeneeded=()=>request.result.createObjectStore('folders');request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(new Error('Die Ordnerzuordnung kann in diesem Browser nicht gespeichert werden.'));});}
export async function folderStore(operation,key,value){const db=await openFolderStore();try{return await new Promise((resolve,reject)=>{const transaction=db.transaction('folders',operation==='get'?'readonly':'readwrite');const store=transaction.objectStore('folders');const request=operation==='get'?store.get(key):operation==='put'?store.put(value,key):store.delete(key);let result;request.onsuccess=()=>result=request.result;transaction.oncomplete=()=>resolve(result);transaction.onerror=()=>reject(transaction.error||new Error('Ordnerzuordnung konnte nicht gespeichert werden.'));transaction.onabort=()=>reject(transaction.error||new Error('Ordnerzuordnung konnte nicht gespeichert werden.'));});}finally{db.close();}}
const sessionFolderHandles=new Map();
const sessionRootHandles=new Map();
const defaultCentral={read:async(...args)=>(await import('./centralAccountingFolders.js?v=1')).centralAccountingFolders.read(...args),save:async(...args)=>(await import('./centralAccountingFolders.js?v=1')).centralAccountingFolders.save(...args)};
export function folderPathName(path){return String(path||'').trim().replace(/[\\/]+$/,'').split(/[\\/]/).filter(Boolean).at(-1)||'';}
export function folderBindingValid(binding,central){return Boolean(binding?.handle&&central?.assignmentId&&binding.assignmentId===central.assignmentId);}
export function folderFromSelectedFiles(files,{folderName=''}={}){
 const selected=Array.from(files||[]);const name=selected[0]?.webkitRelativePath?.split('/')[0]||folderName;
 if(!selected.length||!name)throw new Error('Bitte einen Ordner mit Dateien auswählen.');
 const entries=selected.filter(file=>!file.webkitRelativePath||file.webkitRelativePath.split('/').length===2).map(file=>[file.name,{name:file.name,kind:'file',getFile:async()=>file}]);
 return {name,kind:'directory',selectionOnly:true,queryPermission:async()=> 'granted',requestPermission:async()=> 'granted',async *entries(){yield* entries;},async getDirectoryHandle(child){const subset=selected.filter(file=>file.webkitRelativePath?.split('/')[1]===child);if(!subset.length)throw Object.assign(new Error('Unterordner nicht gefunden'),{name:'NotFoundError'});return {name:child,kind:'directory',selectionOnly:true,queryPermission:async()=> 'granted',requestPermission:async()=> 'granted',async *entries(){for(const file of subset)if(file.webkitRelativePath.split('/').length===3)yield [file.name,{name:file.name,kind:'file',getFile:async()=>file}];}};}};
}
export function selectFolderFiles(){return new Promise((resolve,reject)=>{
 const input=document.createElement('input');input.type='file';input.multiple=true;input.setAttribute('webkitdirectory','');input.hidden=true;document.body.append(input);
 let settled=false;const finish=(error,handle)=>{if(settled)return;settled=true;input.remove();error?reject(error):resolve(handle);};
 input.onchange=()=>{try{finish(null,folderFromSelectedFiles(input.files));}catch(error){finish(error);}};
 input.oncancel=()=>setTimeout(()=>{if(settled)return;if(input.files?.length){try{finish(null,folderFromSelectedFiles(input.files));}catch(error){finish(error);}}else finish(Object.assign(new Error('Ordnerauswahl abgebrochen.'),{name:'AbortError'}));},0);
 try{input.click();}catch(error){finish(error);}
});}
export async function chooseAccountingFolder(options,{nativePicker=globalThis.window?.showDirectoryPicker?.bind(globalThis.window),fallback=selectFolderFiles}={}){
 if(typeof nativePicker!=='function')return fallback();
 try{return await nativePicker(options);}catch(error){
  if(['NotFoundError','TypeError','InvalidStateError','DataError'].includes(error.name)&&options.startIn){const {startIn,...retry}=options;return nativePicker(retry);}
  if(['SecurityError','NotSupportedError','NotAllowedError','AbortError'].includes(error.name))return fallback();
  throw error;
 }
}
export function folderOperation(promise,ms,message){return new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error(message)),ms);Promise.resolve(promise).then(value=>{clearTimeout(timer);resolve(value);},error=>{clearTimeout(timer);reject(error);});});}
export async function mountAccountingFolders(userId,{store=folderStore,picker=chooseAccountingFolder,central=defaultCentral,timeoutMs=10000,storageTimeoutMs=1500}={}){
 const status=document.querySelector('[data-accounting-folder-status]');if(!status)return;
 if(!userId){status.textContent='Bitte neu anmelden, um Ordner zuzuweisen.';return;}
 if(!document.querySelector('[data-accounting-folder-assignment]'))return mountSharedAccountingFolder(userId,{store,picker,central,timeoutMs,storageTimeoutMs});
 const bindings=new Map(),shared=new Map(),revisions=new Map(),loading=new Map();const supported=typeof picker==='function';
 const feedback=(category,text)=>{status.textContent=text;const local=document.querySelector(`[data-accounting-folder-feedback="${category}"]`);if(local)local.textContent=text;};
 const element=(kind,category)=>document.querySelector(`[data-accounting-folder-${kind}="${category}"]`);
 const update=category=>{const binding=bindings.get(category),common=shared.get(category);const valid=folderBindingValid(binding,common),granted=valid&&binding.permissionState==='granted';element('assignment',category).open=!common;element('summary',category).textContent=common?`Ordner: ${common.folderName}${granted?' · freigegeben':valid?' · Zugriff aktivieren':' · auf diesem Gerät noch freigeben'}`:'Ordner zuweisen';element('name',category).textContent=valid?binding.handle.name+(binding.handle.selectionOnly?' · Dateien für diese Sitzung ausgewählt':''):binding?.handle?'Zielordner geändert. Bitte einmal Ordner zuweisen.':'Auf diesem Gerät noch nicht freigegeben';element('central',category).textContent=common?`Zentral gespeichert: ${common.path||common.folderName}`:'Noch kein Ordner zugewiesen';element('pick',category).disabled=!supported;element('path',category).value=common?.path||common?.folderName||'';const browser=element('browser',category);browser.hidden=!valid;browser.open=false;element('list',category).innerHTML='';};
 const persist=async(category,binding)=>{if(binding.handle.selectionOnly)return false;try{await folderOperation(store('put',accountingFolderKey(userId,category),binding),storageTimeoutMs,'Die Gerätezuordnung konnte nicht rechtzeitig gespeichert werden.');return true;}catch{return false;}};
 for(const [category]of accountingFolderCategories){
  const key=accountingFolderKey(userId,category);const cached=sessionFolderHandles.get(key);if(cached)bindings.set(category,cached);
  const filesInput=element('files',category);filesInput.onchange=async()=>{try{const current=shared.get(category);if(!current)throw Error('Bitte zuerst den gemeinsamen Zielpfad eintragen und einen Ordner zuweisen.');const handle=folderFromSelectedFiles(filesInput.files,{folderName:current.folderName});const binding={handle,assignmentId:current.assignmentId};bindings.set(category,binding);sessionFolderHandles.set(key,binding);update(category);feedback(category,`${filesInput.files.length} Dateien aus „${current.folderName}“ für diese Sitzung ausgewählt. Die Rechnungen werden eingelesen.`);if(typeof window!=='undefined')window.dispatchEvent(new CustomEvent('pdtv-accounting-folder-ready',{detail:{category}}));}catch(error){feedback(category,error.message);}finally{filesInput.value='';}};
  const pick=element('pick',category);pick.onclick=async()=>{pick.disabled=true;revisions.set(category,(revisions.get(category)||0)+1);const requestedPath=String(element('path',category).value||'').trim();try{const old=bindings.get(category);const options={id:`pdtv-${category}`,mode:category==='outgoing'?'read':'readwrite'};if(old?.handle&&!old.handle.selectionOnly)options.startIn=old.handle;feedback(category,'Bitte den Ordner im Auswahlfenster auswählen. Falls es nicht öffnet: „Alternative: PDF-Dateien auswählen“ verwenden.');const handle=await picker(options);element('summary',category).textContent=`Ausgewählt: ${handle.name}`;element('name',category).textContent=`${handle.name} · Zuordnung noch nicht gespeichert`;feedback(category,`Ordner „${handle.name}“ ausgewählt. Zentrale Zuordnung wird geprüft …`);await loading.get(category);const previous=shared.get(category);let path=requestedPath||previous?.path||handle.name;if(folderPathName(path)!==handle.name){if(!requestedPath||requestedPath===(previous?.path||previous?.folderName))path=path.replace(/[^\\/]+[\\/]*$/,handle.name);else throw new Error('Der ausgewählte Ordner muss zum letzten Teil des Zielpfads passen.');}const replace=Boolean(previous)&&(previous.folderName!==handle.name||(previous.path||previous.folderName)!==path);const common=previous&&!replace?previous:await folderOperation(central.save(category,handle.name,{replace,expectedId:previous?.assignmentId||null,path}),timeoutMs,'Zentrale Ordnerzuordnung konnte nicht rechtzeitig gespeichert werden. Bitte erneut versuchen.');if(common.folderName!==handle.name)throw new Error('Die gemeinsame Zuordnung wurde inzwischen geändert. Bitte den Bereich neu laden.');shared.set(category,common);const binding={handle,assignmentId:common.assignmentId,permissionState:'granted'};bindings.set(category,binding);sessionFolderHandles.set(key,binding);update(category);feedback(category,`Ordner „${handle.name}“ freigegeben. Gerätezuordnung wird gespeichert …`);const saved=await persist(category,binding);feedback(category,saved?`Ordner „${handle.name}“ zentral zugewiesen, auf diesem Gerät freigegeben und gespeichert.`:`Ordner „${handle.name}“ zentral gespeichert; Dateien für diese Sitzung ausgewählt. Nach einem Neustart erneut auswählen.`);if(typeof window!=='undefined')window.dispatchEvent(new CustomEvent('pdtv-accounting-folder-ready',{detail:{category}}));}catch(error){feedback(category,error.name==='AbortError'?'Ordnerauswahl abgebrochen. Falls kein Fenster erschien, „Alternative: PDF-Dateien auswählen“ verwenden.':error.message||'Ordner konnte nicht zugewiesen werden.');element('alternative',category).open=true;}finally{pick.disabled=!supported;}};
  const browser=element('browser',category);browser.ontoggle=async()=>{if(!browser.open)return;try{const common=await central.read(category);shared.set(category,common);const binding=bindings.get(category);if(!folderBindingValid(binding,common)){update(category);throw new Error('Der Zielordner wurde geändert. Bitte einmal Ordner zuweisen.');}await ensureFolderPermission(binding.handle);const entries=[];for await(const [name,entry]of binding.handle.entries())entries.push({name,kind:entry.kind});element('list',category).innerHTML=entries.length?`<ul style="overflow-wrap:anywhere">${entries.sort((a,b)=>a.name.localeCompare(b.name,'de')).map(entry=>`<li>${escapeHtml(entry.name)}${entry.kind==='directory'?' (Unterordner)':''}</li>`).join('')}</ul>`:'<p class="muted">Der Ordner ist leer.</p>';}catch(error){status.textContent=error.message||'Ordner konnte nicht gelesen werden.';}};
  const initialRevision=revisions.get(category)||0;loading.set(category,(async()=>{try{const [common,saved]=await Promise.all([folderOperation(central.read(category),timeoutMs,'Zentrale Ordnerzuordnung konnte nicht rechtzeitig geladen werden.'),folderOperation(store('get',key),storageTimeoutMs,'Gerätezuordnung nicht erreichbar.').catch(()=>null)]);shared.set(category,common);if((revisions.get(category)||0)===initialRevision&&!bindings.has(category)&&saved)bindings.set(category,saved.handle?saved:{handle:saved,assignmentId:null});let binding=bindings.get(category);if(binding?.handle&&!binding.assignmentId){let target=common;if(!target)target=await central.save(category,binding.handle.name);if(target.folderName===binding.handle.name){shared.set(category,target);binding={handle:binding.handle,assignmentId:target.assignmentId};bindings.set(category,binding);sessionFolderHandles.set(key,binding);await persist(category,binding);}}if(binding?.handle?.queryPermission)binding.permissionState=await binding.handle.queryPermission({mode:'read'}).catch(()=> 'prompt');update(category);}catch(error){element('central',category).textContent='Zentrale Zuordnung konnte nicht geladen werden';feedback(category,error.message||'Ordnerzuordnung konnte nicht geladen werden.');throw error;}})());loading.get(category).catch(()=>{});
 }
 if(!supported)status.textContent='Für die Ordnerauswahl ist ein Browser mit Ordnerfreigabe erforderlich.';
 await Promise.allSettled([...loading.values()]);
 const rootButton=document.querySelector('[data-accounting-root-pick]');if(rootButton){let remembered=null;try{remembered=await folderOperation(store('get',userId+':root'),storageTimeoutMs,'');}catch{}const rootSummary=document.querySelector('[data-accounting-root-summary]'),rootDetails=document.querySelector('[data-accounting-root-assignment]');rootDetails.open=!remembered;if(remembered?.handle)rootSummary.textContent='Buchhaltungsordner: '+remembered.handle.name;if(remembered?.handle)sessionRootHandles.set(userId,remembered.handle);const rootState=remembered?.handle?.queryPermission?await remembered.handle.queryPermission({mode:'readwrite'}).catch(()=> 'prompt'):null;if(remembered?.handle){rootButton.textContent=rootState==='granted'?'Ordnerzugriff prüfen':'Ordnerzugriff aktivieren';rootDetails.open=rootState!=='granted';rootSummary.textContent='Buchhaltungsordner: '+remembered.handle.name+(rootState==='granted'?' · freigegeben':' · Zugriff aktivieren');}rootButton.onclick=async()=>{rootButton.disabled=true;try{const root=await activateAccountingRoot(remembered?.handle,{picker});const children=await resolveAccountingRootFolders(root,[...shared].map(([category,common])=>({category,...common})));let persistent=true;for(const child of children){const old=shared.get(child.category),common=old&&old.folderName===child.name?old:await central.save(child.category,child.name,{replace:Boolean(old),expectedId:old?.assignmentId||null,path:root.name+'/'+child.name});shared.set(child.category,common);const binding={handle:child.handle,assignmentId:common.assignmentId,permissionState:'granted'};bindings.set(child.category,binding);sessionFolderHandles.set(accountingFolderKey(userId,child.category),binding);persistent=(await persist(child.category,binding))&&persistent;update(child.category);}remembered={handle:root};sessionRootHandles.set(userId,root);rootButton.textContent='Ordnerzugriff prüfen';if(!root.selectionOnly)try{await folderOperation(store('put',userId+':root',remembered),storageTimeoutMs,'');}catch{persistent=false;}rootSummary.textContent='Buchhaltungsordner: '+root.name+' · drei Bereiche verbunden';rootDetails.open=false;status.textContent=persistent?'Buchhaltungsordner freigegeben und für alle drei Bereiche auf diesem Gerät gespeichert.':'Alle drei Bereiche für diese Sitzung verbunden; der Browser konnte die Freigabe nicht dauerhaft speichern.';if(typeof window!=='undefined')window.dispatchEvent(new CustomEvent('pdtv-accounting-folder-ready',{detail:{category:'all'}}));}catch(error){status.textContent=error.name==='AbortError'?'Ordnerauswahl abgebrochen.':error.message;}finally{rootButton.disabled=false;}};}
}
export async function activateAccountingRoot(remembered,{picker=chooseAccountingFolder}={}){
 // Invoke requestPermission directly in the click handler, before storage/network awaits.
 if(remembered&&!remembered.selectionOnly&&typeof remembered.requestPermission==='function'){
  try{const state=await remembered.requestPermission({mode:'readwrite'});if(state==='granted')return remembered;}catch(error){if(!['NotFoundError','InvalidStateError','SecurityError','NotAllowedError'].includes(error.name))throw error;}
 }
 return picker({id:'pdtv-accounting-root',mode:'readwrite',...(remembered&&!remembered.selectionOnly?{startIn:remembered}:{})});
}
export async function accountingFolderHandle(userId,category,{store=folderStore,central=defaultCentral,mode='read',requestPermission=true}={}){
 const key=accountingFolderKey(userId,category);let binding=sessionFolderHandles.get(key)||await folderOperation(store('get',key),1500,'Die Gerätezuordnung ist nicht erreichbar.');
 const root=sessionRootHandles.get(userId)||(await folderOperation(store('get',userId+':root'),1500,'').catch(()=>null))?.handle;
 // Reconstruct child handles from the one authorized parent, without new prompts.
 if(root&&!root.selectionOnly&&typeof root.getDirectoryHandle==='function'&&await root.queryPermission({mode})==='granted'){
  const common=await folderOperation(central.read(category),10000,'Zentrale Ordnerzuordnung ist nicht erreichbar.');
  if(common?.folderName){const handle=await root.getDirectoryHandle(common.folderName,{create:false});binding={handle,assignmentId:common.assignmentId};sessionFolderHandles.set(key,binding);}
 }
 if(!binding?.handle)throw folderPermissionError(category,'Der gespeicherte Ordnerzugriff ist auf diesem Gerät noch nicht vorhanden.');
 if(mode==='readwrite'&&(binding.handle.selectionOnly||typeof binding.handle.getFileHandle!=='function'))throw new Error('Dieser Ordner ist nur lesbar. Für automatisches Speichern den Buchhaltungsordner mit Schreibzugriff freigeben.');
 const permission=await binding.handle.queryPermission({mode});
 if(permission!=='granted'){
  if(!requestPermission)throw folderPermissionError(category,'Der Browser muss den gespeicherten Ordnerzugriff erneut freigeben.');
  try{await ensureFolderPermission(binding.handle,mode);}catch(error){throw folderPermissionError(category,'Der gespeicherte Zugriff konnte nicht aktiviert werden.');}
 }
 const common=await folderOperation(central.read(category),10000,'Zentrale Ordnerzuordnung ist nicht erreichbar. Bitte erneut versuchen.');
 if(!folderBindingValid(binding,common))throw new Error('Der gemeinsame Zielordner wurde geändert. Bitte „Ordner zuweisen“ verwenden.');
 sessionFolderHandles.set(key,binding);return binding.handle;
}
function folderPermissionError(category,reason){const label=accountingFolderCategories.find(([id])=>id===category)?.[1]||'Buchhaltung';const error=new Error(label+': '+reason+' Oben „Ordnerzugriff aktivieren“ anklicken; das gilt für alle drei Bereiche.');error.code='accounting/folder-permission';return error;}
export async function resolveAccountingRootFolders(root,targets=[]){const normalize=value=>String(value).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]/g,'');const directories=[];for await(const [name,handle]of root.entries())if(handle.kind==='directory')directories.push({name,handle});const conventional={outgoing:['Ausgangsrechnungen'],incoming:['Eingangsrechnungen'],statements:['Kontoauszüge','Kontoauszuege']};const result=[];for(const [category]of accountingFolderCategories){const target=targets.find(item=>item.category===category),names=[target?.folderName,...conventional[category]].filter(Boolean);let match;for(const name of names){match=directories.find(dir=>normalize(dir.name)===normalize(name));if(match)break;try{if(root.getDirectoryHandle){const handle=await root.getDirectoryHandle(name,{create:false});match={name:handle.name,handle};break;}}catch(error){if(!['NotFoundError','TypeMismatchError'].includes(error.name))throw error;}}if(!match)throw Error('Im ausgewählten Buchhaltungsordner fehlt der Unterordner '+conventional[category][0]+'.');result.push({category,...match});}return result;}
export function accountingRootFolderMarkup(){return '<div class="actions muted" style="margin:8px 0;gap:10px;font-size:13px"><button type="button" class="button button--secondary button--small" style="white-space:nowrap;padding:5px 12px;font-size:13px" data-accounting-root-pick title="Hauptordner zuweisen und alle drei Buchhaltungsbereiche gemeinsam freigeben">Ordner zuweisen</button><span data-accounting-root-summary></span><details style="flex:1;min-width:160px"><summary style="cursor:pointer">Ordnerabgleich · Details</summary><div data-accounting-folder-status role="status" aria-live="polite" style="padding-top:6px"></div></details></div>';}

async function mountSharedAccountingFolder(userId,{store,picker,central,timeoutMs,storageTimeoutMs}){
 const button=document.querySelector('[data-accounting-root-pick]'),summary=document.querySelector('[data-accounting-root-summary]'),status=document.querySelector('[data-accounting-folder-status]');if(!button)return;
 button.disabled=true;let remembered=sessionRootHandles.get(userId)||null,shared=new Map();
 try{const [saved,...folders]=await Promise.all([folderOperation(store('get',userId+':root'),storageTimeoutMs,'').catch(()=>null),...accountingFolderCategories.map(([category])=>folderOperation(central.read(category),timeoutMs,'Ordnerzuordnung nicht erreichbar.'))]);remembered=remembered||saved?.handle;for(const [index,[category]]of accountingFolderCategories.entries())shared.set(category,folders[index]);if(remembered){sessionRootHandles.set(userId,remembered);summary.textContent=remembered.name;const state=await remembered.queryPermission({mode:'readwrite'});button.textContent=state==='granted'?'Ordner zuweisen':'Ordnerzugriff aktivieren';}else if(folders.some(Boolean))summary.textContent='Zentral zugeordnet';}catch(error){status.textContent=error.message;}finally{button.disabled=false;}
 button.onclick=async()=>{button.disabled=true;status.textContent='';try{
  const root=await activateAccountingRoot(remembered,{picker});const children=await resolveAccountingRootFolders(root,[...shared].map(([category,common])=>({category,...common})));let persistent=!root.selectionOnly;
  for(const child of children){const old=shared.get(child.category),common=old&&old.folderName===child.name?old:await central.save(child.category,child.name,{replace:Boolean(old),expectedId:old?.assignmentId||null,path:root.name+'/'+child.name});shared.set(child.category,common);const binding={handle:child.handle,assignmentId:common.assignmentId,permissionState:'granted'};sessionFolderHandles.set(accountingFolderKey(userId,child.category),binding);if(!root.selectionOnly)try{await folderOperation(store('put',accountingFolderKey(userId,child.category),binding),storageTimeoutMs,'');}catch{persistent=false;}}
  remembered=root;sessionRootHandles.set(userId,root);if(!root.selectionOnly)try{await folderOperation(store('put',userId+':root',{handle:root}),storageTimeoutMs,'');}catch{persistent=false;}
  summary.textContent=root.name+' · freigegeben';button.textContent='Ordner zuweisen';status.textContent=persistent?'':'Nur für diese Sitzung freigegeben.';
  window.dispatchEvent(new CustomEvent('pdtv-accounting-folder-ready',{detail:{category:'all'}}));
 }catch(error){status.textContent=error.name==='AbortError'?'Ordnerauswahl abgebrochen.':error.message;}finally{button.disabled=false;}};
}
