import {saveGeneratedInvoiceToFolder} from './invoiceFolderWriter.js?v=3';
import {callEventModerator} from '../firebase/eventModeratorService.js?v=1';
import {accountingFolderHandle} from './accountingFolders.js?v=16';
export function generatedInvoiceFile(result){const bytes=Uint8Array.from(atob(result.pdfBase64),c=>c.charCodeAt(0));return new File([bytes],result.filename,{type:'application/pdf'});}
export function openInvoicePdfGeneration(userId,records){
 const dialog=document.createElement('dialog');dialog.style.cssText='width:min(1000px,94vw);max-height:90dvh;overflow:auto;padding:24px;border:1px solid #dce4ef;border-radius:18px';const title=document.createElement('h2');title.textContent='Rechnungs-PDFs neu erzeugen';const status=document.createElement('p');status.setAttribute('role','status');const close=document.createElement('button');close.type='button';close.className='button button--secondary';close.textContent='Schließen';close.disabled=true;close.onclick=()=>dialog.close();dialog.append(title,status,close);document.body.append(dialog);dialog.showModal();let busy=true;const urls=[];dialog.addEventListener('cancel',e=>{if(busy)e.preventDefault();});dialog.addEventListener('close',()=>{urls.forEach(url=>URL.revokeObjectURL(url));dialog.remove();},{once:true});
 (async()=>{let done=0;for(const [index,record]of records.entries()){status.textContent=`PDF ${index+1} von ${records.length} erzeugen …`;const section=document.createElement('section');section.className='panel';const heading=document.createElement('h3');heading.textContent=record.invoiceNumber+' · '+record.memberName;const message=document.createElement('p');section.append(heading,message);dialog.insertBefore(section,status);
  try{const result=await callEventModerator('generateAccountingInvoicePdf',{action:'generate',invoiceId:record.id});const file=generatedInvoiceFile(result),url=URL.createObjectURL(file);urls.push(url);const frame=document.createElement('iframe');frame.title='Rechnung '+record.invoiceNumber;frame.src=url;frame.style.cssText='width:100%;height:430px;border:1px solid #dce4ef';const download=document.createElement('a');download.href=url;download.download=file.name;download.textContent='PDF herunterladen';download.className='button button--secondary';const save=document.createElement('button');save.type='button';save.className='button button--secondary';save.textContent='Im Ausgangsrechnungsordner speichern';const saveCopy=async()=>{save.disabled=true;try{const saved=await saveGeneratedInvoiceToFolder(userId,record,file);message.textContent='PDF zentral und im Ausgangsrechnungsordner gespeichert: '+saved.filename+(saved.backup?' · Vorherige PDF unter Versionen gesichert.':'');save.hidden=true;return true;}catch(error){message.textContent='PDF ist zentral gespeichert, aber noch nicht im Ausgangsrechnungsordner: '+error.message;save.hidden=false;save.textContent='Ordnerablage erneut versuchen';return false;}finally{save.disabled=false;}};save.onclick=saveCopy;section.append(frame,download,save);message.textContent='PDF zentral gespeichert. Automatische Ablage im Ausgangsrechnungsordner …';await saveCopy();done++;}catch(error){message.textContent=error.message;message.style.color='#c62828';}}
 busy=false;close.disabled=false;status.textContent=done+' von '+records.length+' PDFs erzeugt. Es wurde keine E-Mail versendet.';
 })();
}
