import {loadClosedAccountingYears,accountingRecordIsClosed} from './accountingYearClosure.js?v=8';
import {centralAccountingFolders} from './centralAccountingFolders.js?v=1';
import {getFirebaseServices} from '../firebase/firebaseClient.js?v=3';
export const INVENTORY_VERSION=1;
export function compareFolderFiles(previous,current){const before=new Map((previous||[]).map(f=>[f.name,f]));const after=new Map(current.map(f=>[f.name,f]));return {added:current.filter(f=>!before.has(f.name)),changed:current.filter(f=>before.has(f.name)&&(before.get(f.name).hash!==f.hash||before.get(f.name).size!==f.size||before.get(f.name).lastModified!==f.lastModified)),removed:(previous||[]).filter(f=>!after.has(f.name))};}
export async function inspectAccountingFolder(category,folder){const common=await centralAccountingFolders.read(category);if(!common?.assignmentId)throw Error('Zentrale Ordnerzuordnung fehlt.');const f=await getFirebaseServices();if(!f)throw Error('Firebase ist nicht erreichbar.');const ref=f.firestore.doc(f.db,'settings',`accountingInventory-${category}-${common.assignmentId}`),snapshot=await f.firestore.getDoc(ref),previous=snapshot.exists()?snapshot.data():null;const files=[];
 for await(const [name,handle]of folder.entries()){if(handle.kind!=='file'||! /\.pdf$/i.test(name))continue;const file=await handle.getFile(),hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',await file.arrayBuffer())),b=>b.toString(16).padStart(2,'0')).join('');files.push({name,size:file.size,lastModified:file.lastModified,hash,file});}
 files.sort((a,b)=>a.name.localeCompare(b.name,'de'));const metadata=files.map(({file,...row})=>row),changes=compareFolderFiles(previous?.files,metadata);return {category,assignmentId:common.assignmentId,ref,previous,files,metadata,complete:!folder.selectionOnly,needsRead:!previous||previous.version!==INVENTORY_VERSION||changes.added.length>0||changes.changed.length>0||changes.removed.length>0,changes};
}
export function invoiceFileAvailability(records,inventory){if(!inventory.complete)return [];return records.filter(r=>!r.archived&&!r.historicalImport&&!r.isInternalBookingReceipt&&r.sourceHash).map(record=>{const file=inventory.metadata.find(file=>file.hash===record.sourceHash);const patch={sourceFileMissing:!file,sourceFileName:file?.name||record.sourceFileName||record.sourceName||'',sourceFileAssignmentId:inventory.assignmentId};return {id:record.id,record,patch};}).filter(({record,patch})=>Object.entries(patch).some(([key,value])=>record[key]!==value));}
export async function syncIncomingFileAvailability(records,inventory){const f=await getFirebaseServices(),closed=await loadClosedAccountingYears(f),changes=invoiceFileAvailability(records,inventory).filter(item=>!accountingRecordIsClosed(item.record,closed));for(let start=0;start<changes.length;start+=100){const chunk=changes.slice(start,start+100);await f.firestore.runTransaction(f.db,async tx=>{const refs=chunk.map(item=>f.firestore.doc(f.db,'accountingIncomingInvoices',item.id)),snapshots=await Promise.all(refs.map(ref=>tx.get(ref)));chunk.forEach((item,index)=>{if(!snapshots[index].exists()||snapshots[index].data().sourceHash!==item.record.sourceHash)return;tx.update(refs[index],{...item.patch,sourceFileCheckedAt:new Date().toISOString(),updatedAt:new Date().toISOString(),updatedBy:f.auth.currentUser.uid});});});for(const item of chunk)Object.assign(item.record,item.patch);}return records.filter(r=>!r.archived&&r.sourceFileMissing).length;}
export async function saveAccountingInventory(inventory){if(!inventory.complete)return;const f=await getFirebaseServices(),known=new Map([...(inventory.previous?.knownFiles||inventory.previous?.files||[]),...inventory.metadata].map(file=>[file.hash,file])),present=new Set(inventory.metadata.map(file=>file.hash));const record={category:inventory.category,assignmentId:inventory.assignmentId,version:INVENTORY_VERSION,files:inventory.metadata,knownFiles:[...known.values()],missingFiles:[...known.values()].filter(file=>!present.has(file.hash)),checkedAt:new Date().toISOString(),updatedBy:f.auth.currentUser.uid};await f.firestore.runTransaction(f.db,async tx=>{const current=await tx.get(inventory.ref);if((current.exists()?current.data().checkedAt:null)!==(inventory.previous?.checkedAt||null))throw Error('Der Ordner wurde parallel abgeglichen. Bitte die Übersicht erneut öffnen.');tx.set(inventory.ref,record);});return record;}
export function inventoryFeedback(inventory,missing=0){if(!inventory.complete)return 'Dateiauswahl eingelesen; keine Prüfung auf entfernte Dateien möglich.';const change=inventory.changes;return `${change.added.length} neue, ${change.changed.length} geänderte, ${change.removed.length} entfernte PDF-Dateien · ${missing} Rechnungs-PDFs fehlen.`;}
import {invoicePdfMatches} from './accountingInvoicePdf.js?v=9';
export function outgoingFileAvailability(records,inventory){if(!inventory.complete)return [];return records.filter(r=>!r.archived&&!r.historicalImport&&r.invoiceNumber).map(record=>{if(record.invoicePdfArtifact)return {id:record.id,record,patch:{sourceFileMissing:false}};const current=invoicePdfMatches(inventory.metadata.map(file=>file.name),record);let name=current.length===1?current[0]:null;if(!name){const old=invoicePdfMatches((inventory.previous?.knownFiles||inventory.previous?.files||[]).map(file=>file.name),record);const hashes=new Set((inventory.previous?.knownFiles||inventory.previous?.files||[]).filter(file=>old.includes(file.name)).map(file=>file.hash));const renamed=inventory.metadata.filter(file=>hashes.has(file.hash));if(renamed.length===1)name=renamed[0].name;}const patch={sourceFileMissing:!name&&current.length===0,...(name?{pdfFileName:name}:{})};return {id:record.id,record,patch};}).filter(({record,patch})=>Object.entries(patch).some(([key,value])=>record[key]!==value));}
export async function syncOutgoingFileAvailability(records,inventory){const f=await getFirebaseServices(),closed=await loadClosedAccountingYears(f);for(const item of outgoingFileAvailability(records,inventory).filter(item=>!accountingRecordIsClosed(item.record,closed))){await f.firestore.runTransaction(f.db,async tx=>{const ref=f.firestore.doc(f.db,'membershipContributions',item.id),snapshot=await tx.get(ref);if(!snapshot.exists()||snapshot.data().invoiceNumber!==item.record.invoiceNumber)return;const patch={...item.patch};if(snapshot.data().invoicePdfArtifact)patch.sourceFileMissing=false;tx.update(ref,{...patch,updatedAt:new Date().toISOString(),updatedBy:f.auth.currentUser.uid});});}return records.filter(r=>!r.archived&&!r.invoicePdfArtifact&&outgoingFileAvailability([r],inventory).some(item=>item.patch.sourceFileMissing)).length;}
