import {callEventModerator} from '../firebase/eventModeratorService.js?v=1';
import {escapeHtml} from './format.js?v=4';
const periodLabel=r=>r.exists?'Bereits vorhanden':r.notDue?'Kein Beitrag in diesem Jahr':`${r.contributionFrom.split('-').reverse().join('.')} – ${r.contributionTo.split('-').reverse().join('.')} · ${r.contributionMonths} Monate${r.membershipStartDate?'':' (Eintrittsdatum nicht hinterlegt: voller Jahresbeitrag)'}`;
const money=value=>new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}).format(value/100);
export function contributionAmount(value){const text=String(value).trim();if(!/^\d+(?:[.,]\d{1,2})?$/.test(text))throw new Error('Bitte gültige Beiträge in EUR eingeben.');const [whole,decimal='']=text.split(/[.,]/);const cents=Number(whole)*100+Number(decimal.padEnd(2,'0'));if(!Number.isSafeInteger(cents)||cents>100000000)throw new Error('Der Beitrag ist zu hoch.');return cents;}
export function openAnnualContributions(){
 const year=new Date().getFullYear();const dialog=document.createElement('dialog');
 dialog.style.cssText='width:min(960px,94vw);max-height:90dvh;overflow:auto;border:1px solid #dce4ef;border-radius:18px;padding:24px';
 dialog.innerHTML=`<h2>Jahresbeiträge erstellen</h2><p>Ein Mitglied, mehrere per Checkbox oder alle auswählen. Vorhandene Jahresbeiträge werden nicht erneut angelegt. Neue Mitglieder zahlen ab dem nächsten Monatsersten bis Jahresende. Das Eintrittsdatum wird im Mitgliederdatensatz hinterlegt.</p><div class="form-grid--four"><div class="field"><label for="annual-year">Beitragsjahr</label><input id="annual-year" data-year type="number" min="1900" max="2200" value="${year}"></div><div class="field"><label for="annual-date">Rechnungsdatum</label><input id="annual-date" data-date type="date" value="${year}-01-01"></div><div class="field"><label for="annual-company">Unternehmensbeitrag EUR</label><input id="annual-company" data-company inputmode="decimal" value="800,00"></div><div class="field"><label for="annual-individual">Einzelbeitrag EUR</label><input id="annual-individual" data-individual inputmode="decimal" value="180,00"></div></div><div class="actions"><button type="button" class="button button--secondary" data-load>Mitglieder laden / aktualisieren</button><label><input type="checkbox" data-all disabled> Alle auswählen</label></div><div data-members></div><p role="status" data-status></p><div data-preview></div><p class="muted">Es werden Beitragsdatensätze mit Zahlungsstatus „Offen“ angelegt. Es werden keine E-Mails versendet.</p><div class="actions"><button type="button" class="button button--secondary" data-review disabled>Auswahl prüfen</button><button type="button" class="button button--primary" data-create disabled>Jahresbeiträge anlegen</button><button type="button" class="button button--secondary" data-close>Abbrechen</button></div>`;
 document.body.append(dialog);dialog.showModal();dialog.addEventListener('close',()=>dialog.remove(),{once:true});
 const $=selector=>dialog.querySelector(selector);let rows=[],plan=null,busy=false;
 const inputs=()=>({year:Number($('[data-year]').value),invoiceDate:$('[data-date]').value,companyCents:contributionAmount($('[data-company]').value),individualCents:contributionAmount($('[data-individual]').value)});
 const selected=()=>[...dialog.querySelectorAll('[data-member]:checked')].map(el=>el.dataset.member);
 const controls=()=>{const count=selected().length;$('[data-all]').disabled=busy||!rows.some(r=>!r.exists&&!r.notDue);$('[data-review]').disabled=busy||!count;$('[data-create]').disabled=busy||!plan?.newCount;$('[data-load]').disabled=busy;dialog.querySelectorAll('[data-member], [data-year], [data-date], [data-company], [data-individual]').forEach(el=>el.disabled=busy);const choices=dialog.querySelectorAll('[data-member]');$('[data-all]').checked=choices.length>0&&count===choices.length;$('[data-all]').indeterminate=count>0&&count<choices.length;};
 const invalidate=()=>{plan=null;$('[data-preview]').innerHTML='';controls();};
 const run=async work=>{if(busy)return;busy=true;controls();$('[data-status]').textContent='Wird geprüft …';try{await work();}catch(error){$('[data-status]').textContent=error.message||'Die Beiträge konnten nicht verarbeitet werden.';}finally{busy=false;controls();}};
 $('[data-close]').onclick=()=>{if(!busy)dialog.close();};dialog.addEventListener('cancel',event=>{if(busy)event.preventDefault();});
 $('[data-load]').onclick=()=>run(async()=>{invalidate();const result=await callEventModerator('generateAnnualContributions',{...inputs(),dryRun:true});rows=result.rows;$('[data-members]').innerHTML=`<div class="table-wrap"><table class="table"><thead><tr><th>Auswahl</th><th>Mitglied</th><th>Beitrag</th><th>Status</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${r.exists||r.notDue?'–':`<input type="checkbox" data-member="${escapeHtml(r.memberId)}" aria-label="${escapeHtml(r.memberName)} auswählen">`}</td><td>${escapeHtml(r.memberName)}</td><td>${money(r.amountCents||0)}</td><td>${r.exists?`Bereits vorhanden: ${escapeHtml(r.invoiceNumber||'')}`:escapeHtml(periodLabel(r))}</td></tr>`).join('')||'<tr><td colspan="4">Keine aktiven Mitglieder gefunden.</td></tr>'}</tbody></table></div>`;$('[data-status]').textContent=`${result.newCount} Mitglieder ohne Jahresbeitrag · ${result.skippedCount} bereits vorhanden`;dialog.querySelectorAll('[data-member]').forEach(el=>el.onchange=invalidate);});
 $('[data-all]').onchange=event=>{dialog.querySelectorAll('[data-member]').forEach(el=>el.checked=event.target.checked);invalidate();};
 for(const key of ['year','date','company','individual'])$(`[data-${key}]`).oninput=()=>{if(key==='year')$('[data-date]').value=`${$('[data-year]').value}-01-01`;rows=[];$('[data-members]').innerHTML='';invalidate();$('[data-status]').textContent='Einstellungen geändert. Bitte Mitglieder erneut laden.';};
 $('[data-review]').onclick=()=>run(async()=>{invalidate();const request={...inputs(),memberIds:selected(),dryRun:true};const result=await callEventModerator('generateAnnualContributions',request);plan={...result,request};$('[data-preview]').innerHTML=`<h3>Vorschau: ${result.newCount} Jahresbeiträge · ${money(result.totalCents)}</h3><div class="table-wrap"><table class="table"><thead><tr><th>Mitglied</th><th>Rechnung</th><th>Datum</th><th>Zeitraum</th><th>Beitrag</th></tr></thead><tbody>${result.rows.map(r=>`<tr><td>${escapeHtml(r.memberName)}</td><td>${escapeHtml(r.invoiceNumber)}${r.exists?' (bereits vorhanden)':''}</td><td>${escapeHtml(request.invoiceDate.split('-').reverse().join('.'))}</td><td>${escapeHtml(periodLabel(r))}</td><td>${money(r.amountCents||0)}</td></tr>`).join('')}</tbody></table></div>`;$('[data-status]').textContent='Vorschau geprüft. Mit „Jahresbeiträge anlegen“ speichern.';});
 $('[data-create]').onclick=()=>run(async()=>{if(!plan)return;const result=await callEventModerator('generateAnnualContributions',{...plan.request,dryRun:false,expectedFingerprint:plan.fingerprint});plan=null;rows=[];$('[data-members]').innerHTML='';$('[data-preview]').innerHTML='';$('[data-status]').textContent=`${result.created} Jahresbeiträge gespeichert · ${money(result.totalCents)} · ${result.skipped} übersprungen`;$('[data-close]').textContent='Schließen';window.dispatchEvent(new Event('pdtv-accounting-saved'));});
 $('[data-load]').click();
}
