export function extractIban(text){
 const lengths={DE:22,AT:20,GB:22,CH:21,FR:27,NL:18,BE:16,ES:24,IT:27,LU:20,IE:22};
 const valid=value=>{let remainder=0;for(const char of value.slice(4)+value.slice(0,4)){const digits=/[A-Z]/.test(char)?String(char.charCodeAt(0)-55):char;for(const digit of digits)remainder=(remainder*10+Number(digit))%97;}return remainder===1;};
 for(const match of String(text||'').toUpperCase().matchAll(/\b[A-Z]{2}\d{2}(?:\s*[A-Z0-9]){11,30}/g)){
  const compact=match[0].replace(/\s/g,'');const expected=lengths[compact.slice(0,2)];
  if(expected){const value=compact.slice(0,expected);if(value.length===expected&&valid(value))return value;}
  else for(let length=15;length<=Math.min(compact.length,34);length++){const value=compact.slice(0,length);if(valid(value))return value;}
 }
 return '';
}
const euro=text=>{const m=String(text).match(/([\d.]+),(\d{2})\s*([+-])?/);if(!m)throw Error('Betrag konnte nicht gelesen werden.');const cents=Number(m[1].replaceAll('.',''))*100+Number(m[2]);if(!Number.isSafeInteger(cents))throw Error('Ungültiger Betrag.');return m[3]==='-'?-cents:cents;};
const iso=text=>{const [day,month,year]=text.split('.');return `${year}-${month}-${day}`;};

export function parseHvbTransactions(pages,sourceName){
 const text=pages.join('\n'),period=text.match(/(?:ausgewählten Zeitraum|Datum)\s+(\d{2}\.\d{2}\.\d{4})\s*-\s*(\d{2}\.\d{2}\.\d{4})/i),closing=text.match(/Kontostand am\s*(\d{2}\.\d{2}\.\d{4})\s+(-?[\d.]+,\d{2})\s*EUR/i);
 const header=text.split(/Umsätze im gewählten Zeitraum/i)[0],accountIban=extractIban(header);
 if(!period||!closing||!accountIban)throw Error(sourceName+': Zeitraum, Kontostand oder Konto-IBAN der Umsatzübersicht nicht erkannt.');
 const periodFrom=iso(period[1]),periodTo=iso(period[2]);if(iso(closing[1])!==periodTo)throw Error(sourceName+': Kontostand gehört nicht zum Ende des ausgewählten Zeitraums.');
 const signed=v=>String(v).startsWith('-')?-euro(v):euro(v);const rows=[];let current=null;const finish=()=>{if(!current)return;rows.push({...current,description:current.lines[0]||current.type,details:current.lines.join('\n'),iban:extractIban(current.lines.join('\n'))});current=null;};
 for(const page of pages){let table=false;for(const raw of page.split('\n')){const line=raw.trim();if(/^Buchung\s+Valuta\s+Verwendungszweck\s+Betrag/i.test(line)){table=true;continue;}if(!table)continue;if(/^https?:|^\d{2}\.\d{2}\.\d{4}\s*-\s*\d{2}:\d{2}\s+Uhr\s+Seite|^Seite\s+\d+/i.test(line)){finish();table=false;continue;}const booking=line.match(/^(\d{2}\.\d{2}\.\d{4})\s+(\d{2}\.\d{2}\.\d{4})\s+(.+?)\s+(-?[\d.]+,\d{2})\s*EUR$/);if(booking){finish();const date=iso(booking[1]);if(date<periodFrom||date>periodTo)throw Error(sourceName+': Buchungsdatum liegt außerhalb des Auszugszeitraums.');current={date,valueDate:iso(booking[2]),type:booking[3],amountCents:signed(booking[4]),lines:[]};}else if(/^\d{2}\.\d{2}\.\d{4}\s+\d{2}\.\d{2}\.\d{4}/.test(line))throw Error(sourceName+': Eine Umsatzzeile konnte nicht vollständig gelesen werden.');else if(current&&line)current.lines.push(line);}finish();}
 if(!rows.length)throw Error(sourceName+': Keine Buchungen in der Umsatzübersicht erkannt.');rows.sort((a,b)=>a.date.localeCompare(b.date));const closingCents=signed(closing[2]),openingCents=closingCents-rows.reduce((sum,r)=>sum+r.amountCents,0);let balance=openingCents;for(const row of rows){balance+=row.amountCents;row.balanceCents=balance;}const previous=new Date(periodFrom+'T12:00:00Z');previous.setUTCDate(previous.getUTCDate()-1);
 return {sourceName,accountIban,periodFrom,periodTo,openingDate:previous.toISOString().slice(0,10),openingCents,openingSource:'Aus Endsaldo und vollständig gelesenen Umsätzen berechnet',closingCents,currency:'EUR',rows,warnings:[],format:'hvb-transactions'};
}

export function parseHvbStatement(pages,sourceName){
 if(/Kontoumsätze/.test(pages.join("\n"))&&/Buchung\s+Valuta\s+Verwendungszweck\s+Betrag/.test(pages.join("\n")))return parseHvbTransactions(pages,sourceName);
 const text=pages.join('\n');const header=pages[0]?.split(/Buchung\s*\/\s*Wert/i)[0]||'';const accountIban=extractIban(header);const period=text.match(/(\d{2}\.\d{2}\.\d{4})\s*-\s*(\d{2}\.\d{2}\.\d{4})/);
 const opening=text.match(/Ihr alter Kontostand per\s*(\d{2}\.\d{2}\.\d{4})\s*:\s*EUR\s*([\d.]+,\d{2}\s*[+-])/i);
 const closing=text.match(/Ihr neuer Kontostand\s*:\s*EUR\s*([\d.]+,\d{2}\s*[+-])/i);
 if(!period||!opening||!closing)throw Error(`${sourceName}: Zeitraum oder Anfangs-/Endsaldo nicht erkannt. Bitte Original prüfen.`);
 const from=iso(period[1]),to=iso(period[2]),rows=[];let balance=euro(opening[2]),current=null,table=false;const warnings=[];
 const finish=()=>{if(!current)return;const details=current.lines.map(line=>line.replace(/^\d{2}\.\d{2}\.\s*/,'' )).filter(line=>line&&!/^(?:ECHTZEIT|AUFTRAG UM|[A-Z]{2}\d{8,}|KUNDENREFERENZ|MANDATSREFERENZ|GLAEUBIGER-ID)/i.test(line));balance+=current.amountCents;rows.push({...current,iban:extractIban(current.lines.join('\n')),description:details[0]||current.type,details:details.join('\n'),balanceCents:balance});current=null;};
 for(const page of pages){table=false;for(const raw of page.split('\n')){const line=raw.trim();if(/Buchung\s*\/\s*Wert.*Buchungsinformation/i.test(line)){table=true;continue;}if(!table)continue;if(/Kontostand|[Ü�]bertrag:|Bitte.*R[ü�]ckseite|Seite\s+\d+\s+von/i.test(line)){finish();if(/[Ü�]bertrag:/.test(line)){const amount=line.match(/EUR\s*([\d.]+,\d{2}\s*[+-])/);if(amount&&euro(amount[1])!==balance)warnings.push('Seitenübertrag stimmt nicht mit den gelesenen Buchungen überein.');}if(/Ihr neuer Kontostand|Bitte.*R[ü�]ckseite|Seite\s+\d+\s+von/i.test(line))table=false;continue;}const booking=line.match(/^(\d{2})\.(\d{2})\.\s+(.+?)\s+([\d.]+,\d{2})\s*([+-])$/);if(booking){finish();let year=Number(to.slice(0,4));if(Number(booking[2])>Number(to.slice(5,7)))year--;const date=`${year}-${booking[2]}-${booking[1]}`;if(date<from||date>to)throw Error(`${sourceName}: Buchungsdatum liegt außerhalb des Auszugszeitraums.`);current={date,type:booking[3],amountCents:euro(booking[4]+booking[5]),lines:[]};}else if(current&&line)current.lines.push(line);}finish();}
 if(balance!==euro(closing[1]))warnings.push(`Endsaldo stimmt nicht: ${balance} statt ${euro(closing[1])} Cent. Buchungen bitte prüfen.`);
 if(!rows.length&&euro(opening[2])!==euro(closing[1]))warnings.push('Keine Buchungen erkannt, obwohl sich der Saldo verändert hat.');
 return {sourceName,accountIban,periodFrom:from,periodTo:to,openingDate:iso(opening[1]),openingCents:euro(opening[2]),closingCents:euro(closing[1]),currency:'EUR',rows,warnings};
}
export function bankLedger(statements){const sorted=[...statements].sort((a,b)=>a.periodFrom.localeCompare(b.periodFrom)||a.sourceName.localeCompare(b.sourceName));const warnings=sorted.flatMap(s=>s.warnings||[]);const accountIbans=[...new Set(sorted.map(s=>s.accountIban).filter(Boolean))];if(accountIbans.length>1)warnings.push('Die Auszüge gehören zu unterschiedlichen IBANs. Bitte getrennt einlesen.');let previous=null;const rows=[];let debitCents=0,creditCents=0;for(const statement of sorted){if(previous&&(statement.periodFrom<previous.periodTo||statement.openingCents!==previous.closingCents))warnings.push(`Lücke oder Überschneidung vor ${statement.sourceName}.`);for(const {rowIndex,row}of statement.rows.map((row,rowIndex)=>({row,rowIndex})).sort((a,b)=>(a.row.postingOrder??a.rowIndex)-(b.row.postingOrder??b.rowIndex))){if(row.amountCents<0)debitCents+=row.amountCents;else creditCents+=row.amountCents;rows.push({...row,sourceName:statement.sourceName,statementId:statement.id||statement.sourceHash||'',rowIndex});}previous=statement;}return {rows,warnings,accountIbans,openingCents:sorted[0]?.openingCents??0,openingDate:sorted[0]?.openingDate||'',debitCents,creditCents,closingCents:sorted.at(-1)?.closingCents??0};}
export function pdfTextLines(items){const lines=[];for(const item of items){if(!item.str?.trim())continue;const y=item.transform[5];let line=lines.find(line=>Math.abs(line.y-y)<2);if(!line){line={y,items:[]};lines.push(line);}line.items.push({x:item.transform[4],text:item.str});}return lines.sort((a,b)=>b.y-a.y).map(line=>line.items.sort((a,b)=>a.x-b.x).map(item=>item.text).join(' ')).join('\n');}
