import {extractIban,pdfTextLines} from './bankStatementParser.js?v=6';
export function invoiceCents(value){const text=String(value??'').trim().replace(/\s|€/g,'');if(!/^\d+(?:\.\d{3})*(?:,\d{1,2})?$/.test(text))throw Error('Bitte einen Betrag wie 1.234,56 eingeben.');const [whole,fraction='']=text.split(',');const cents=Number(whole.replaceAll('.',''))*100+Number(fraction.padEnd(2,'0'));if(!Number.isSafeInteger(cents))throw Error('Ungültiger Betrag.');return cents;}
const invoiceDate=value=>{const m=String(value||'').match(/\b(\d{1,2})\.(\d{1,2})\.(\d{4})\b/);if(!m)return '';const iso=`${m[3]}-${m[2].padStart(2,'0')}-${m[1].padStart(2,'0')}`;const date=new Date(iso+'T12:00:00Z');return Number.isFinite(date.getTime())&&date.toISOString().slice(0,10)===iso?iso:'';};
export function parseIncomingInvoice(text,sourceName){
 if((/Kontoumsätze/i.test(text)&&/Buchung\s+Valuta\s+Verwendungszweck\s+Betrag/i.test(text))||(/Ihr alter Kontostand/i.test(text)&&/Ihr neuer Kontostand/i.test(text)&&/Buchung\s*\/\s*Wert/i.test(text)))throw Error('Diese PDF ist ein Kontoauszug, keine Eingangsrechnung. Bitte unter „Kontoauszüge / Zahlungsverkehr“ einlesen.');
 if(/\b(?:USD|GBP|CHF)\b|\$/.test(text))throw Error('Fremdwährung erkannt. Der EUR-Import ist für diese Rechnung nicht geeignet.');
 text=text.replace(/(\d)[ \t]+(?=,\d)/g,'$1').replace(/(,\d)[ \t]+(?=\d)/g,'$1');
 const dropbox=/^Dropbox International Unlimited Company\b/m.test(text);
 const dropboxMeta=dropbox?text.match(/(\d{1,2})\.\s+(Januar|Februar|März|April|Mai|Juni|Juli|August|September|Oktober|November|Dezember)\s+(\d{4})\s+\d{1,2}:\d{2}\s+GMT\s+([A-Z0-9-]+)/i):null;
 const months=['januar','februar','märz','april','mai','juni','juli','august','september','oktober','november','dezember'];
 const dropboxDate=dropboxMeta?invoiceDate(dropboxMeta[1]+'.'+(months.indexOf(dropboxMeta[2].toLowerCase())+1)+'.'+dropboxMeta[3]):'';
 const lines=text.split('\n').map(l=>l.trim()).filter(Boolean);const number=text.match(/(?:Rechnungs(?:nummer|[- ]?Nr\.?|[- ]?Nummer)|Invoice\s*(?:number|no\.?)|Rechnung\s+Nr\.?)\s*[:#]?\s*([^\s:]+)|Rechnung\s*[:#]\s*([^\s:]+)/i);
 const fallbackNumber=text.match(/(?:Re-Nr\.?|Rechnung\s*\|\s*Nummer)\s*:?\s*([A-Z0-9][A-Z0-9/.-]+)|(?:^|\n)\s*RECHNUNG\s+([A-Z0-9][A-Z0-9/.-]+)|PRO-FORMA\s+Invoice\s+(PF\s+[0-9/.-]+)/i);
 const date=text.match(/(?:Rechnungsdatum|Invoice date|Datum)\s*:?\s*(\d{1,2}\.\d{1,2}\.\d{4})/i);const fallbackDate=text.match(/(?:Hamburg, den|Düsseldorf,)\s*(\d{1,2}\.\d{1,2}\.\d{4})/i);const isoDate=text.match(/Invoice date:\s*(\d{4}-\d{2}-\d{2})/i);const due=text.match(/(?:Fällig(?:keit| am)?|zahlbar bis|Zahlungsziel)\s*:?\s*(\d{1,2}\.\d{1,2}\.\d{4})/i);
 const amounts=[...text.matchAll(/(?:Gesamtbetrag|Rechnungsbetrag|Bruttobetrag|Endbetrag|Summe brutto|Total(?: amount)?)\s*:?\s*(?:EUR\s*)?([\d.]+,\d{2})\s*(?:€|EUR)?/gi)];const extra=[...text.matchAll(/(?:Rechnungsbetrag(?: gesamt)?|Rechnungsgesamtbetrag|Zahlbetrag|Rechnungssumme|Gesamtbetrag(?: \(brutto\))?|Endsumme|Endbetrag in EUR)\s*:?\s*([\d.]+,\d{2})/gi)].map(m=>invoiceCents(m[1]));for(const m of text.matchAll(/(?:^|\n)\s*Gesamt\s*:\s*([\d.]+,\d{2})/gi))extra.push(invoiceCents(m[1]));const english=text.match(/Total:\s*EUR\s*(\d+\.\d{2})/i);if(english)extra.push(Math.round(Number(english[1])*100));if(dropbox){const total=text.match(/(?:^|\n)Insgesamt\s+([\d.]+,\d{2})\s*€/i);if(total)extra.push(invoiceCents(total[1]));}const unique=[...new Set([...amounts.map(m=>invoiceCents(m[1])),...extra])];
 const explicitSupplier=text.match(/Verkauft von\s+([^\n]+)|Rechnungsaussteller:\s*([^,\n]+)|(?:^|\n)Von:\s*\n([^\n]+)/i);const nameHeader=lines[0]?.includes(' – ')?lines[0].split(' – ')[0]:'';const roleSupplier=text.match(/Leistungserbringer Rechnungsempfänger\s*\n([^\n]+?)\s+ProdigitalTV/i);const supplierLine=lines.find(l=>/\b(?:GmbH|gGmbH|AG|UG|Ltd|PartGmbB|GbR)\b/i.test(l)&&!/PROdigitalTV|Interessengemeinschaft|Bank|Kontoinhaber/i.test(l));
 return {sourceName,accountNumber:text.match(/(?:Sachkonto|Buchungskonto|Kostenkonto)\s*:?\s*(\d{4,8})\b/i)?.[1]||'',supplier:dropbox?'Dropbox International Unlimited Company':explicitSupplier?.[1]||explicitSupplier?.[2]||explicitSupplier?.[3]||roleSupplier?.[1]||nameHeader||supplierLine||'',invoiceNumber:dropboxMeta?dropboxMeta[4]:(number?.[1]||number?.[2]||fallbackNumber?.[1]||fallbackNumber?.[2]||fallbackNumber?.[3]||'').replace(/^-$/,''),invoiceDate:dropboxDate||invoiceDate(date?.[1]||fallbackDate?.[1])||isoDate?.[1]||'',dueDate:invoiceDate(due?.[1]),amountCents:unique.length===1?unique[0]:null,currency:'EUR',iban:extractIban(text),description:'',paymentStatus:'outstanding',paidDate:'',reviewStatus:'needs_review',extractedText:text.slice(0,60000)};
}
export async function readIncomingPdf(file){const pdfjs=await import('/assets/vendor/pdfjs/pdf.min.mjs');pdfjs.GlobalWorkerOptions.workerSrc='/assets/vendor/pdfjs/pdf.worker.min.mjs';const bytes=await file.arrayBuffer();const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes)),b=>b.toString(16).padStart(2,'0')).join('');const task=pdfjs.getDocument({data:new Uint8Array(bytes),isEvalSupported:false,standardFontDataUrl:'/assets/vendor/pdfjs/standard_fonts/'});try{const pdf=await task.promise;const pages=[];for(let i=1;i<=pdf.numPages;i++)pages.push(pdfTextLines((await(await pdf.getPage(i)).getTextContent()).items));return {...parseIncomingInvoice(pages.join('\n'),file.name),id:hash,sourceHash:hash};}finally{await task.destroy();}}
