import {invoicePaymentCandidates,paymentBookingKey,confirmInvoicePayment,invoiceAssignmentDifferences,invoiceAssignmentSnapshot} from './invoicePaymentMatching.js?v=17';
import {openIncomingInvoicePdf} from './incomingInvoicePdf.js?v=7';
import {escapeHtml} from './format.js?v=4';
import {germanCsvDate} from './csvText.js?v=2';
const money=value=>Number.isSafeInteger(value)?new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}).format(value/100):'Betrag fehlt';
const iban=value=>String(value||'').replace(/\s/g,'').toUpperCase();
export function assignmentCandidates(invoice,statements,claims=[],today){return invoicePaymentCandidates(invoice,statements,claims,today).filter(row=>!iban(invoice.iban)||!iban(row.iban)||iban(invoice.iban)===iban(row.iban)).map(row=>({...row,ibanMatch:Boolean(iban(invoice.iban)&&iban(row.iban)&&iban(invoice.iban)===iban(row.iban))})).sort((a,b)=>Number(b.ibanMatch)-Number(a.ibanMatch)||a.date.localeCompare(b.date));}
export function unassignedDebitBookings(statements,invoices,claims=[],today=new Date().toISOString().slice(0,10)){const used=new Set([...claims.map(c=>c.id),...invoices.map(i=>i.paymentMatch?.bookingKey).filter(Boolean)]);return statements.filter(s=>!s.warnings?.length).flatMap(s=>(s.rows||[]).map((row,index)=>({...row,index,excluded:s.excludedAssignmentRows?.includes(index),statementId:s.id||s.sourceHash,sourceName:s.sourceName,bookingKey:paymentBookingKey(s.id||s.sourceHash,index)}))).filter(row=>!row.excluded&&row.statementId&&row.amountCents<0&&row.date<=today&&!used.has(row.bookingKey)).sort((a,b)=>a.date.localeCompare(b.date));}
export function invoiceAssignmentsMarkup(invoices,statements,claims){return `<section class="panel"><h2>Belege und Kontobuchungen zuordnen</h2><p>Rechnung links auswählen, passende Kontobuchung rechts prüfen und die Verbindung speichern. Verglichen werden IBAN und exakter Betrag.</p><div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,340px),1fr));gap:20px"><section><h3>Rechnungsbelege</h3><div class="field"><label>Suchen</label><input type="search" data-assignment-invoice-search placeholder="Lieferant, RG-Nr., IBAN oder Betrag"></div><p data-assignment-invoice-count></p><div data-assignment-invoices style="max-height:55dvh;overflow:auto;display:grid;gap:8px"></div></section><section><h3>Kontobuchungen</h3><div class="field"><label>Suchen</label><input type="search" data-assignment-booking-search placeholder="Empfänger, Verwendungszweck, IBAN oder Betrag"></div><label><input type="checkbox" data-assignment-only-matches> Nur passende Buchungen anzeigen</label><p data-assignment-booking-count></p><div data-assignment-bookings style="max-height:55dvh;overflow:auto;display:grid;gap:8px"></div></section></div><div class="panel" style="margin-top:20px"><div data-assignment-comparison>Bitte eine Rechnung auswählen.</div><div class="actions"><button type="button" class="button button--primary" data-assignment-save disabled title="Rechnung und Kontobuchung dauerhaft verknüpfen und das Buchungsdatum als Zahlungsdatum übernehmen">Zuordnung speichern</button><button type="button" class="button button--secondary" data-assignment-pdf disabled title="Das Original-PDF der ausgewählten Rechnung öffnen">Rechnung öffnen</button></div><p data-assignment-status role="status" aria-live="polite"></p></div><details><summary data-assignment-linked-count>Bereits zugeordnete Rechnungen</summary><div data-assignment-linked></div></details><script type="application/json" data-assignment-data>${JSON.stringify({invoices,statements,claims}).replaceAll('<','\\u003c')}</script></section>`;}
export function mountInvoiceAssignments(userId,scope=document){const data=scope.querySelector('[data-assignment-data]');if(!data)return;const {invoices,statements,claims}=JSON.parse(data.textContent);const root=data.parentElement;const $=selector=>root.querySelector(selector);let selectedInvoiceId='',selectedBookingKey='',busy=false,acceptDifferences=false;let available=invoices.filter(i=>!i.archived&&!['paid','cancelled'].includes(i.paymentStatus)&&!i.paymentMatch);let bookings=unassignedDebitBookings(statements,invoices,claims);
 const selectedInvoice=()=>available.find(i=>i.id===selectedInvoiceId);const candidates=()=>selectedInvoice()?assignmentCandidates(selectedInvoice(),statements,claims):[];
 const render=()=>{const invoice=selectedInvoice(),matches=candidates(),row=bookings.find(r=>r.bookingKey===selectedBookingKey),differences=invoice&&row?invoiceAssignmentDifferences(invoice,row):[];const search=$('[data-assignment-invoice-search]').value.trim().toLocaleLowerCase('de');const shownInvoices=available.filter(i=>[i.supplier,i.invoiceNumber,i.sourceName,i.iban,money(i.amountCents)].join(' ').toLocaleLowerCase('de').includes(search));$('[data-assignment-invoice-count]').textContent=`${shownInvoices.length} noch nicht zugeordnete Rechnungen`;
 $('[data-assignment-invoices]').innerHTML=shownInvoices.map(i=>`<label style="display:block;padding:12px;border:1px solid ${i.id===selectedInvoiceId?'#e60012':'#dce4ef'};border-radius:12px;overflow-wrap:anywhere"><input type="radio" name="assignment-invoice" value="${escapeHtml(i.id)}" ${i.id===selectedInvoiceId?'checked':''} ${busy?'disabled':''}> <strong>${escapeHtml(i.supplier||i.sourceName)}</strong>${trashButton('invoice',i.id)}<div>${escapeHtml(i.invoiceNumber||'RG-Nr. fehlt')} · ${germanCsvDate(i.invoiceDate)} · ${money(i.amountCents)}</div><small>IBAN: ${escapeHtml(i.iban||'Nicht hinterlegt')}</small></label>`).join('')||'<p>Keine unzugeordneten Rechnungen gefunden.</p>';
 const bookingSearch=$('[data-assignment-booking-search]').value.trim().toLocaleLowerCase('de');const only=$('[data-assignment-only-matches]').checked;const shownBookings=(only&&invoice?matches:bookings).filter(r=>[r.description,r.details,r.iban,money(-r.amountCents),germanCsvDate(r.date)].join(' ').toLocaleLowerCase('de').includes(bookingSearch));$('[data-assignment-booking-count]').textContent=invoice?`${matches.length} passende Buchungen · ${shownBookings.length} angezeigt`:`${shownBookings.length} unzugeordnete Kontobelastungen`;
 $('[data-assignment-bookings]').innerHTML=shownBookings.map(r=>{const candidate=matches.find(m=>m.bookingKey===r.bookingKey);return `<label style="display:block;padding:12px;border:1px solid ${r.bookingKey===selectedBookingKey?'#e60012':'#dce4ef'};border-radius:12px;overflow-wrap:anywhere"><input type="radio" name="assignment-booking" value="${escapeHtml(r.bookingKey)}" ${r.bookingKey===selectedBookingKey?'checked':''} ${busy?'disabled':''}> <strong>${germanCsvDate(r.date)} · ${money(-r.amountCents)}</strong>${trashButton('booking',r.bookingKey)}<div>${escapeHtml(r.description)}</div><small>IBAN: ${escapeHtml(r.iban||'Nicht im Auszug enthalten')}</small>${candidate?`<div>${candidate.ibanMatch?'IBAN und Betrag stimmen überein':'Betrag stimmt überein · IBAN fehlt, bitte prüfen'}</div>`:invoice?'<div>IBAN, Betrag oder Datum passen nicht zur ausgewählten Rechnung.</div>':''}<details><summary>Verwendungszweck</summary><p style="white-space:pre-wrap">${escapeHtml(r.details||'')}</p><small>${escapeHtml(r.sourceName)}</small></details></label>`;}).join('')||'<p>Keine passenden Kontobuchungen. Betrag und IBAN der Rechnung prüfen oder „Nur passende Buchungen“ ausschalten.</p>';
 $('[data-assignment-comparison]').innerHTML=!invoice?'Bitte eine Rechnung auswählen.':!row?`<strong>${escapeHtml(invoice.supplier||invoice.sourceName)} · ${money(invoice.amountCents)}</strong><p>Bitte rechts eine Kontobuchung auswählen.</p>`:`<strong>${escapeHtml(invoice.invoiceNumber||invoice.sourceName)} ↔ ${germanCsvDate(row.date)} · ${money(-row.amountCents)}</strong><p>${differences.length?escapeHtml(differences.join(' · ')):iban(invoice.iban)&&iban(row.iban)?'IBAN und Betrag stimmen überein.':'Der Betrag stimmt überein. Eine IBAN fehlt; Empfänger und Verwendungszweck bitte prüfen.'}</p><p>Mit „Zuordnung speichern“ werden Rechnung und Kontobuchung verbunden. Zahlungsdatum: ${germanCsvDate(row.date)}.${!Number.isSafeInteger(invoice.amountCents)||invoice.amountCents<=0?' Der Rechnungsbetrag fehlt noch. Die Verknüpfung wird gespeichert; der Beleg bleibt zur Prüfung.':-row.amountCents<invoice.amountCents?' Der Betrag deckt die Rechnung nicht vollständig; sie bleibt offen.':' Die Rechnung wird als bezahlt erfasst.'}</p>${differences.length?`<label><input type="checkbox" data-assignment-accept-differences ${acceptDifferences?'checked':''}> Ich habe die Abweichungen geprüft und möchte diese beiden Datensätze verbinden.</label>`:''}`;
 $('[data-assignment-save]').disabled=!invoice||!row||(differences.length>0&&!acceptDifferences)||busy;$('[data-assignment-pdf]').disabled=!invoice||busy;
 const acknowledgment=$('[data-assignment-accept-differences]');if(acknowledgment)acknowledgment.onchange=()=>{acceptDifferences=acknowledgment.checked;render();};
 root.querySelectorAll('[data-assignment-remove]').forEach(button=>button.onclick=async event=>{event.preventDefault();event.stopPropagation();const kind=button.dataset.assignmentRemove,id=button.dataset.assignmentRemoveId;const item=kind==='invoice'?invoices.find(i=>i.id===id):bookings.find(r=>r.bookingKey===id);if(!item||!window.confirm(kind==='invoice'?'Diesen Rechnungsbeleg aus der Liste entfernen? Die Original-PDF bleibt erhalten.':'Diese Buchung aus der Zuordnung entfernen? Der originale Kontoauszug und dessen Saldo bleiben erhalten.'))return;busy=true;render();try{await removeAssignmentItem(kind,item);}catch(error){$('[data-assignment-status]').textContent=error.message||'Entfernen fehlgeschlagen.';}finally{busy=false;render();}});
 root.querySelectorAll('[name="assignment-invoice"]').forEach(input=>input.onchange=()=>{selectedInvoiceId=input.value;acceptDifferences=false;render();});root.querySelectorAll('[name="assignment-booking"]').forEach(input=>input.onchange=()=>{selectedBookingKey=input.value;acceptDifferences=false;render();});
 const linked=invoices.filter(i=>i.paymentMatch);$('[data-assignment-linked-count]').textContent=`${linked.length} bereits zugeordnete Rechnungen`;$('[data-assignment-linked]').innerHTML=`<div class="table-wrap"><table class="table"><thead><tr><th>Rechnung</th><th>Lieferant</th><th>IBAN</th><th>Betrag</th><th>Kontobuchung / Zahlungsdatum</th></tr></thead><tbody>${linked.map(i=>`<tr><td><button type="button" class="link" data-assignment-linked-pdf="${escapeHtml(i.id)}">${escapeHtml(i.invoiceNumber||i.sourceName)}</button></td><td>${escapeHtml(i.supplier||'')}</td><td>${escapeHtml(i.iban||'')}</td><td>${money(i.amountCents)}</td><td>${germanCsvDate(i.paidDate)} · ${escapeHtml(i.paymentMatch.sourceName||'')}</td></tr>`).join('')||'<tr><td colspan="5">Noch keine Zuordnungen gespeichert.</td></tr>'}</tbody></table></div>`;root.querySelectorAll('[data-assignment-linked-pdf]').forEach(button=>button.onclick=()=>openIncomingInvoicePdf(userId,invoices.find(i=>i.id===button.dataset.assignmentLinkedPdf)));
};
const replaceInvoices=rows=>{const before=selectedInvoice();const snapshot=before?JSON.stringify(invoiceAssignmentSnapshot(before)):'';invoices.splice(0,invoices.length,...rows);available=invoices.filter(i=>!i.archived&&!['paid','cancelled'].includes(i.paymentStatus)&&!i.paymentMatch);bookings=unassignedDebitBookings(statements,invoices,claims);const after=selectedInvoice();if(!after){selectedInvoiceId='';selectedBookingKey='';acceptDifferences=false;}else if(snapshot!==JSON.stringify(invoiceAssignmentSnapshot(after)))acceptDifferences=false;if(!bookings.some(r=>r.bookingKey===selectedBookingKey))selectedBookingKey='';render();};
 for(const selector of ['[data-assignment-invoice-search]','[data-assignment-booking-search]','[data-assignment-only-matches]'])$(selector).oninput=render;
 $('[data-assignment-pdf]').onclick=()=>openIncomingInvoicePdf(userId,selectedInvoice());
 $('[data-assignment-save]').onclick=async()=>{const invoice=selectedInvoice(),row=bookings.find(r=>r.bookingKey===selectedBookingKey);if(!invoice||!row)return;busy=true;render();$('[data-assignment-status]').textContent='Zuordnung wird gespeichert …';try{await confirmInvoicePayment(invoice.id,row.bookingKey,invoice.updatedAt,{manual:true,acceptDifferences,expectedInvoice:{...invoice}});$('[data-assignment-status]').textContent='Rechnung und Kontobuchung zugeordnet.';}catch(error){if(error.latestInvoice)replaceInvoices(invoices.map(i=>i.id===error.latestInvoice.id?error.latestInvoice:i));$('[data-assignment-status]').textContent=error.message||'Zuordnung konnte nicht gespeichert werden.';}finally{busy=false;render();}};
render();return {selectBooking(key){selectedBookingKey=bookings.some(r=>r.bookingKey===key)?key:'';acceptDifferences=false;render();},updateSources(sources){if(sources.statements)statements.splice(0,statements.length,...sources.statements);if(sources.claims)claims.splice(0,claims.length,...sources.claims);this.updateInvoices([...invoices]);},updateInvoices(rows){replaceInvoices(rows);},selectInvoice(id=''){selectedInvoiceId=available.some(i=>i.id===id)?id:'';selectedBookingKey='';render();}};
}

function trashButton(kind,id){return `<button type="button" class="button button--secondary button--small" style="float:right;padding:6px;line-height:1" data-assignment-remove="${kind}" data-assignment-remove-id="${escapeHtml(id)}" title="${kind==='invoice'?'Beleg aus der Liste entfernen':'Buchung aus der Zuordnung entfernen'}" aria-label="Element entfernen"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><path d="M3 6h18M9 6V3h6v3M5 6l1 15h12l1-15M10 10v7M14 10v7"/></svg></button>`;}
export async function removeAssignmentItem(kind,item){const {getFirebaseServices}=await import('../firebase/firebaseClient.js?v=3');const f=await getFirebaseServices();if(!f)throw Error('Firebase ist nicht erreichbar.');if(!['invoice','booking'].includes(kind))throw Error('Ungültiges Element.');const id=kind==='invoice'?item.id:item.statementId;const ref=f.firestore.doc(f.db,kind==='invoice'?'accountingIncomingInvoices':'accountingStatements',id);const claimRef=kind==='booking'?f.firestore.doc(f.db,'accountingPaymentMatches',item.bookingKey):null;await f.firestore.runTransaction(f.db,async transaction=>{const doc=await transaction.get(ref),claim=claimRef?await transaction.get(claimRef):null;if(!doc.exists())throw Error('Element nicht mehr vorhanden.');const current=doc.data();const now=new Date().toISOString();if(kind==='invoice'){if(current.paymentMatch||current.paymentStatus==='paid')throw Error('Zugeordnete oder bezahlte Rechnungen können hier nicht entfernt werden.');transaction.update(ref,{archived:true,archivedAt:now,archivedBy:f.auth.currentUser.uid,updatedAt:now,updatedBy:f.auth.currentUser.uid});}else{if(claim?.exists())throw Error('Die Buchung ist inzwischen einer Rechnung zugeordnet.');if(!Number.isInteger(item.index)||!current.rows?.[item.index])throw Error('Buchung nicht mehr vorhanden.');transaction.update(ref,{excludedAssignmentRows:[...new Set([...(current.excludedAssignmentRows||[]),item.index])],updatedAt:now,updatedBy:f.auth.currentUser.uid});}});}
