import {accountingFolderHandle} from './accountingFolders.js?v=16';
import {getFirebaseServices} from '../firebase/firebaseClient.js?v=3';
import {invoicePdfMatches} from './accountingInvoicePdf.js?v=9';
const digest=async file=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',await file.arrayBuffer())),b=>b.toString(16).padStart(2,'0')).join('');
async function existingFile(folder,name){try{return await folder.getFileHandle(name);}catch(error){if(error.name==='NotFoundError')return null;throw error;}}
async function write(entry,file){let stream;try{stream=await entry.createWritable();await stream.write(file);await stream.close();}catch(error){try{await stream?.abort();}catch{}throw error;}}
export function invoiceFolderFilename(record,names){const matches=invoicePdfMatches(names,record);if(matches.length>1)throw Error('Mehrere aktuelle PDFs für diese Rechnung gefunden. Bitte die Dateizuordnung prüfen.');return matches[0]||`RECHNUNG ${record.invoiceNumber} MB - ${record.memberName||'Mitglied'}`.replace(/[<>:"/\\|?*\u0000-\u001f]/g,'_').replace(/[. ]+$/,'').slice(0,195)+'.pdf';}
export async function writeGeneratedInvoicePdf(folder,record,file){const names=[];for await(const [name,entry]of folder.entries())if(entry.kind==='file')names.push(name);const filename=invoiceFolderFilename(record,names),hash=await digest(file),existing=await existingFile(folder,filename);let backup='';if(existing){const old=await existing.getFile(),oldHash=await digest(old);if(oldHash===hash)return {filename,sha256:hash,unchanged:true,backup:''};const versions=await folder.getDirectoryHandle('Versionen',{create:true});backup=filename.replace(/\.pdf$/i,'')+'-vorher-'+oldHash.slice(0,12)+'.pdf';const prior=await existingFile(versions,backup);if(prior){if(await digest(await prior.getFile())!==oldHash)throw Error('Die Sicherungsdatei stimmt nicht mit der bisherigen PDF überein.');}else await write(await versions.getFileHandle(backup,{create:true}),old);if(await digest(await(await versions.getFileHandle(backup)).getFile())!==oldHash)throw Error('Die vorherige PDF konnte nicht zuverlässig gesichert werden.');}
 const target=existing||await folder.getFileHandle(filename,{create:true});await write(target,file);if(await digest(await target.getFile())!==hash)throw Error('Die gespeicherte Rechnungs-PDF konnte nicht bestätigt werden.');return {filename,sha256:hash,unchanged:false,backup};}
export async function saveGeneratedInvoiceToFolder(userId,record,file){const folder=await accountingFolderHandle(userId,'outgoing',{mode:'readwrite'}),f=await getFirebaseServices();if(!f)throw Error('Firebase ist nicht erreichbar.');const ref=f.firestore.doc(f.db,'membershipContributions',record.id),snapshot=await f.firestore.getDoc(ref);if(!snapshot.exists())throw Error('Rechnung nicht mehr vorhanden.');const latest={id:snapshot.id,...snapshot.data()},hash=await digest(file);if(latest.invoiceNeedsRegeneration||latest.invoicePdfArtifact?.sha256!==hash)throw Error('Diese PDF ist inzwischen veraltet. Bitte neu erzeugen.');const saved=await writeGeneratedInvoicePdf(folder,latest,file);await f.firestore.runTransaction(f.db,async tx=>{const current=await tx.get(ref);if(!current.exists()||current.data().invoicePdfArtifact?.sha256!==hash)throw Error('Rechnung wurde während der Ordnerablage geändert. Bitte neu erzeugen.');tx.update(ref,{pdfFileName:saved.filename,localPdfSha256:hash,localPdfSavedAt:new Date().toISOString(),sourceFileMissing:false,updatedAt:new Date().toISOString(),updatedBy:f.auth.currentUser.uid});});return saved;}
