import test from 'node:test';import assert from 'node:assert/strict';import {webcrypto} from 'node:crypto';
import {storeAccountingPdf,mountAccountingDropzone,accountingDropzoneMarkup} from '../src/utils/accountingDropzone.js';
if(!globalThis.crypto)globalThis.crypto=webcrypto;
const file=(name,content)=>({name,arrayBuffer:async()=>new TextEncoder().encode(content).buffer});
function folder(initial={}){const files=new Map(Object.entries(initial));let writes=0;return {name:'Eingangsrechnungen',files,get writes(){return writes;},async getFileHandle(name,options={}){if(!files.has(name)){if(!options.create)throw Object.assign(Error('missing'),{name:'NotFoundError'});files.set(name,'');}return {getFile:async()=>file(name,files.get(name)),createWritable:async()=>({write:async f=>{writes++;files.set(name,new TextDecoder().decode(await f.arrayBuffer()));},close:async()=>{},abort:async()=>{}})};}};}
test('identical files are reused; a different same-name PDF gets a unique filename without overwriting',async()=>{const handle=folder({'Rechnung.pdf':'original'});const duplicate=await storeAccountingPdf(handle,file('Rechnung.pdf','original'));assert.equal(duplicate.duplicate,true);assert.equal(handle.writes,0);const result=await storeAccountingPdf(handle,file('Rechnung.pdf','new'));assert.notEqual(result.name,'Rechnung.pdf');assert.equal(handle.files.get('Rechnung.pdf'),'original');assert.equal(handle.files.get(result.name),'new');assert.equal(handle.writes,1);});
test('an existing database PDF name cannot be silently replaced with different content',async()=>{const handle=folder({'RG 2170.pdf':'original'});await assert.rejects(storeAccountingPdf(handle,file('drop.pdf','changed'),'RG 2170.pdf'),/nicht überschrieben/);assert.equal(handle.writes,0);});
test('every PDF is validated before copying; import failure retains the selection for a safe retry',async()=>{const nodes=new Map();const root={style:{},querySelector(selector){if(!nodes.has(selector))nodes.set(selector,{hidden:true,disabled:false,textContent:''});return nodes.get(selector);},addEventListener(){}};let fail=true;const calls=[];const drop=mountAccountingDropzone({querySelector:()=>root},{userId:'admin',category:'incoming',folder:async()=>({name:'Eingangsrechnungen'}),validateFile:async f=>{calls.push('validate '+f.name);return {};},store:async(_,f)=>{calls.push('copy '+f.name);return {duplicate:false};},onStored:async()=>{calls.push('capture');if(fail)throw Error('Firebase offline');}});await drop.accept([file('a.pdf','a'),file('b.pdf','b')]);assert.deepEqual(calls,['validate a.pdf','validate b.pdf','copy a.pdf','copy b.pdf','capture']);assert.equal(nodes.get('[data-drop-retry]').hidden,false);assert.match(nodes.get('[data-drop-status]').textContent,/Firebase offline/);fail=false;await nodes.get('[data-drop-retry]').onclick();assert.match(nodes.get('[data-drop-status]').textContent,/Erfassung abgeschlossen/);assert.match(accountingDropzoneMarkup('incoming','Rechnungen'),/multiple/);});
test('non-PDF files never reach folder access or capture',async()=>{const root={style:{},querySelector:()=>({}),addEventListener(){}};const drop=mountAccountingDropzone({querySelector:()=>root},{category:'incoming',folder:async()=>assert.fail('folder accessed'),validateFile:async()=>assert.fail('parsed'),onStored:async()=>assert.fail('captured')});await drop.accept([file('bad.exe','bad')]);});
