import {accountingFolderHandle} from '../src/utils/accountingFolders.js';
import test from 'node:test';import assert from 'node:assert/strict';
import {accountingFolderCategories,accountingFolderKey,ensureFolderPermission,accountingFoldersMarkup} from '../src/utils/accountingFolders.js';
test('three independent categories per user and device',()=>{assert.equal(accountingFolderCategories.length,3);assert.notEqual(accountingFolderKey('admin1','outgoing'),accountingFolderKey('admin2','outgoing'));assert.notEqual(accountingFolderKey('admin1','outgoing'),accountingFolderKey('admin1','incoming'));assert.throws(()=>accountingFolderKey('','outgoing'));assert.throws(()=>accountingFolderKey('admin','unknown'));});
test('granted folder does not request permission again',async()=>{let requests=0;await ensureFolderPermission({queryPermission:async()=> 'granted',requestPermission:async()=>{requests++;}});assert.equal(requests,0);});
test('expired access asks permission and refuses denial',async()=>{let requests=0;await assert.rejects(ensureFolderPermission({queryPermission:async()=> 'prompt',requestPermission:async()=>{requests++;return 'denied';}}),/nicht freigegeben/);assert.equal(requests,1);});
test('permission renewed after browser restart',async()=>{await ensureFolderPermission({queryPermission:async()=> 'prompt',requestPermission:async()=> 'granted'});});
test('UI offers all pickers and removing assignment leaves files intact',()=>{const html=accountingFoldersMarkup();for(const [id,label]of accountingFolderCategories){assert.ok(html.includes(label));assert.ok(html.includes(`data-accounting-folder-pick="${id}"`));}assert.ok(html.includes('Dateien bleiben erhalten'));});
import {folderStore} from '../src/utils/accountingFolders.js';
test('saved folder handles can be restored and assignment removed',async()=>{const values=new Map();let closed=0;globalThis.indexedDB={open(){const request={};setTimeout(()=>{request.result={close(){closed++;},transaction(){const transaction={};transaction.objectStore=()=>{const operation=(action,key,value)=>{const request={};setTimeout(()=>{if(action==='put')values.set(key,value);if(action==='delete')values.delete(key);request.result=action==='get'?values.get(key):key;request.onsuccess?.();transaction.oncomplete?.();},0);return request;};return {get:key=>operation('get',key),put:(value,key)=>operation('put',key,value),delete:key=>operation('delete',key)};};return transaction;}};request.onsuccess();},0);return request;}};const handle={name:'Ausgangsrechnungen',kind:'directory'};const key=accountingFolderKey('admin','outgoing');assert.equal(await folderStore('get',key),undefined);await folderStore('put',key,handle);assert.equal(await folderStore('get',key),handle);await folderStore('delete',key);assert.equal(await folderStore('get',key),undefined);assert.equal(closed,5);delete globalThis.indexedDB;});
import {mountAccountingFolders as realMountAccountingFolders,folderBindingValid,folderPathName} from '../src/utils/accountingFolders.js';
function fakeCentral(){const values=new Map();let revision=0;return {values,read:async category=>values.get(category)||null,save:async(category,folderName,{path=folderName,replace=false,expectedId=null}={})=>{const old=values.get(category);if(old&&!replace)return old;if(replace&&old?.assignmentId!==expectedId)throw Error('stale');const value={category,folderName,path,assignmentId:'test-'+(++revision)};values.set(category,value);return value;}};}
const mountAccountingFolders=(userId,options)=>realMountAccountingFolders(userId,{central:fakeCentral(),...options});
function folderUi(){const nodes=new Map();const node=key=>{if(!nodes.has(key))nodes.set(key,{textContent:'Kein Ordner zugewiesen',disabled:false,hidden:false,innerHTML:''});return nodes.get(key);};const document={querySelector:node,querySelectorAll:()=>[]};return {document,node};}
test('folder name and actions update immediately before storage completes',async()=>{const ui=folderUi();globalThis.document=ui.document;let finish;const pending=new Promise(resolve=>finish=resolve);const handle={name:'Rechnungen 2026',kind:'directory'};await mountAccountingFolders('immediate-test',{picker:async()=>handle,store:async operation=>operation==='put'?pending:undefined});const pick=ui.node('[data-accounting-folder-pick="outgoing"]');const selection=pick.onclick();await new Promise(resolve=>setTimeout(resolve,0));assert.equal(ui.node('[data-accounting-folder-name="outgoing"]').textContent,handle.name);assert.equal(ui.node('[data-accounting-folder-browser="outgoing"]').hidden,false);finish();await selection;assert.match(ui.node('[data-accounting-folder-status]').textContent,/gespeichert/);delete globalThis.document;});
test('handle serialization failure retains visible assignment across page remounts',async()=>{const ui=folderUi();globalThis.document=ui.document;const handle={name:'Dropbox Ausgangsrechnungen',kind:'directory'};const central=fakeCentral();const store=async operation=>{if(operation==='put')throw new Error('DataCloneError');};await mountAccountingFolders('clone-test',{central,picker:async()=>handle,store});await ui.node('[data-accounting-folder-pick="outgoing"]').onclick();assert.equal(ui.node('[data-accounting-folder-name="outgoing"]').textContent,handle.name);assert.match(ui.node('[data-accounting-folder-status]').textContent,/für diese Sitzung/);const next=folderUi();globalThis.document=next.document;await mountAccountingFolders('clone-test',{central,picker:async()=>handle,store});assert.equal(next.node('[data-accounting-folder-name="outgoing"]').textContent,handle.name);delete globalThis.document;});
test('late restoration cannot overwrite a newly chosen folder',async()=>{const ui=folderUi();globalThis.document=ui.document;let finish;const pending=new Promise(resolve=>finish=resolve);const handle={name:'Neuer Ordner',kind:'directory'};const mount=mountAccountingFolders('restore-race-test',{picker:async()=>handle,store:async(operation,key)=>operation==='get'&&key.endsWith(':outgoing')?pending:undefined});const choice=ui.node('[data-accounting-folder-pick="outgoing"]').onclick();finish({name:'Alter Ordner'});await mount;await choice;assert.equal(ui.node('[data-accounting-folder-name="outgoing"]').textContent,handle.name);delete globalThis.document;});
test('shared target path survives switching devices, local permissions remain separate',async()=>{const central=fakeCentral();await central.save('outgoing','Ausgangsrechnungen',{path:'PROdigitalTV/Buchhaltung Aktuell/Ausgangsrechnungen'});const store=async()=>null;const first=folderUi();globalThis.document=first.document;await mountAccountingFolders('shared-device-a',{central,store,picker:async()=>({name:'Ausgangsrechnungen'})});await first.node('[data-accounting-folder-pick="outgoing"]').onclick();assert.equal(first.node('[data-accounting-folder-browser="outgoing"]').hidden,false);const second=folderUi();globalThis.document=second.document;await mountAccountingFolders('shared-device-b',{central,store,picker:async()=>({name:'Ausgangsrechnungen'})});assert.match(second.node('[data-accounting-folder-central="outgoing"]').textContent,/PROdigitalTV\/Buchhaltung Aktuell/);assert.equal(second.node('[data-accounting-folder-browser="outgoing"]').hidden,true);await second.node('[data-accounting-folder-pick="outgoing"]').onclick();assert.equal(second.node('[data-accounting-folder-browser="outgoing"]').hidden,false);assert.equal(central.values.get('outgoing').assignmentId,'test-1');delete globalThis.document;});
test('changing the central target invalidates old local handles',()=>{const handle={name:'Rechnungen'};assert.equal(folderBindingValid({handle,assignmentId:'old'},{assignmentId:'new'}),false);assert.equal(folderBindingValid({handle,assignmentId:'same'},{assignmentId:'same'}),true);assert.equal(folderBindingValid({handle},null),false);});
test('previous device assignments migrate to central metadata',async()=>{const central=fakeCentral(),ui=folderUi();globalThis.document=ui.document;const store=async(operation,key)=>operation==='get'&&key.endsWith(':incoming')?{name:'Eingangsrechnungen',kind:'directory'}:undefined;await mountAccountingFolders('migration-device',{central,store,picker:async()=>({name:'Eingangsrechnungen'})});assert.equal(central.values.get('incoming').folderName,'Eingangsrechnungen');assert.equal(ui.node('[data-accounting-folder-browser="incoming"]').hidden,false);delete globalThis.document;});
test('an unavailable central store does not create a misleading local assignment',async()=>{const central={read:async()=>{throw Error('offline');},save:async()=>{throw Error('offline');}},ui=folderUi();globalThis.document=ui.document;await mountAccountingFolders('offline-device',{central,store:async()=>null,picker:async()=>({name:'Rechnungen'})});await ui.node('[data-accounting-folder-pick="outgoing"]').onclick();assert.match(ui.node('[data-accounting-folder-status]').textContent,/offline/);assert.notEqual(ui.node('[data-accounting-folder-name="outgoing"]').textContent,'Rechnungen');delete globalThis.document;});
test('one selection replaces the shared target and saves the local binding',async()=>{const central=fakeCentral();await central.save('incoming','Eingangsrechnungen',{path:'PROdigitalTV/Alt/Eingangsrechnungen'});const ui=folderUi();globalThis.document=ui.document;let saved;await mountAccountingFolders('one-button-device',{central,store:async(operation,key,value)=>{if(operation==='put')saved=value;},picker:async options=>{assert.equal(options.mode,'readwrite');return {name:'Neue Eingangsrechnungen'};}});await ui.node('[data-accounting-folder-pick="incoming"]').onclick();assert.equal(central.values.get('incoming').path,'PROdigitalTV/Alt/Neue Eingangsrechnungen');assert.equal(saved.assignmentId,central.values.get('incoming').assignmentId);assert.match(ui.node('[data-accounting-folder-status]').textContent,/freigegeben und gespeichert/);delete globalThis.document;});
test('a common path supports Windows and Dropbox-relative spelling',()=>{assert.equal(folderPathName('D:\\Dropbox\\Buchhaltung\\Ausgangsrechnungen\\'),'Ausgangsrechnungen');assert.equal(folderPathName('PROdigitalTV/Buchhaltung/Ausgangsrechnungen'),'Ausgangsrechnungen');});

test('each folder box has exactly one assignment button',()=>{for(const [category]of accountingFolderCategories){const html=accountingFoldersMarkup(category,false);assert.equal((html.match(/<button /g)||[]).length,1);assert.match(html,/>Ordner zuweisen<\/button>/);assert.ok(!html.includes('data-accounting-folder-path-save'));assert.ok(!html.includes('data-accounting-folder-central-change'));}});
import {chooseAccountingFolder,folderFromSelectedFiles} from '../src/utils/accountingFolders.js';
test('unsupported embedded browser uses folder file selection',async()=>{let calls=0;const handle={name:'Kontoauszuege'};assert.equal(await chooseAccountingFolder({}, {nativePicker:null,fallback:async()=>{calls++;return handle;}}),handle);assert.equal(calls,1);});
test('embedded picker failure including false abort uses directory-file fallback',async()=>{for(const name of ['SecurityError','AbortError']){let fallbackCalls=0;const handle={name:'Kontoauszuege'};assert.equal(await chooseAccountingFolder({}, {nativePicker:async()=>{throw Object.assign(Error('picker failed'),{name});},fallback:async()=>{fallbackCalls++;return handle;}}),handle);assert.equal(fallbackCalls,1);}await assert.rejects(chooseAccountingFolder({}, {nativePicker:async()=>{throw Object.assign(Error('false abort'),{name:'AbortError'});},fallback:async()=>{throw Object.assign(Error('actual cancel'),{name:'AbortError'});}}),{name:'AbortError'});});
test('file selection exposes only files in the selected folder to the parser',async()=>{const pdf={name:'Auszug.pdf',webkitRelativePath:'Kontoauszuege/Auszug.pdf'};const nested={name:'Alt.pdf',webkitRelativePath:'Kontoauszuege/Archiv/Alt.pdf'};const handle=folderFromSelectedFiles([pdf,nested]);const entries=[];for await(const entry of handle.entries())entries.push(entry);assert.equal(handle.name,'Kontoauszuege');assert.equal(handle.selectionOnly,true);assert.equal(entries.length,1);assert.equal(await entries[0][1].getFile(),pdf);await ensureFolderPermission(handle);assert.throws(()=>folderFromSelectedFiles([]),/Ordner mit Dateien/);});
test('invalid saved start folder retries with a fresh directory chooser',async()=>{const calls=[];const handle={name:'Kontoauszuege'};assert.equal(await chooseAccountingFolder({id:'pdtv-statements',startIn:{}},{nativePicker:async options=>{calls.push(options);if(options.startIn)throw Object.assign(Error('missing'),{name:'NotFoundError'});return handle;}}),handle);assert.equal(calls.length,2);assert.equal(calls[1].startIn,undefined);});
test('blocked device storage cannot stall selection after the picker closes',async()=>{const ui=folderUi();globalThis.document=ui.document;const handle={name:'Kontoauszuege'};await mountAccountingFolders('blocked-idb',{central:fakeCentral(),picker:async()=>handle,store:()=>new Promise(()=>{}),storageTimeoutMs:20,timeoutMs:100});await ui.node('[data-accounting-folder-pick="statements"]').onclick();assert.match(ui.node('[data-accounting-folder-summary="statements"]').textContent,/Kontoauszuege.*freigegeben/);assert.match(ui.node('[data-accounting-folder-feedback="statements"]').textContent,/für diese Sitzung/);delete globalThis.document;});
test('an unchanged central path is reused without an unnecessary cloud transaction',async()=>{const central=fakeCentral();await central.save('statements','Kontoauszuege');central.save=async()=>{throw Error('should not save twice');};const ui=folderUi();globalThis.document=ui.document;await mountAccountingFolders('reuse-cloud',{central,picker:async()=>({name:'Kontoauszuege'}),store:async()=>null});await ui.node('[data-accounting-folder-pick="statements"]').onclick();assert.match(ui.node('[data-accounting-folder-feedback="statements"]').textContent,/gespeichert/);delete globalThis.document;});
test('cloud reads that never complete report an error next to the folder',async()=>{const ui=folderUi();globalThis.document=ui.document;await mountAccountingFolders('cloud-timeout',{central:{read:()=>new Promise(()=>{})},picker:async()=>({name:'Kontoauszuege'}),store:async()=>null,timeoutMs:20});await ui.node('[data-accounting-folder-pick="statements"]').onclick();assert.match(ui.node('[data-accounting-folder-feedback="statements"]').textContent,/nicht rechtzeitig geladen/);assert.equal(ui.node('[data-accounting-folder-pick="statements"]').disabled,false);delete globalThis.document;});
test('stale start handles cannot prevent a new folder chooser from opening',async()=>{for(const name of ['TypeError','InvalidStateError','DataError']){let calls=0;const handle={name:'Kontoauszuege'};assert.equal(await chooseAccountingFolder({startIn:{}},{nativePicker:async options=>{calls++;if(options.startIn)throw Object.assign(Error('invalid handle'),{name});return handle;}}),handle);assert.equal(calls,2);}});
test('explicit PDF selection works without directory-selection support',async()=>{const file={name:'Jan.pdf',webkitRelativePath:''};const handle=folderFromSelectedFiles([file],{folderName:'Kontoauszuege'});assert.equal(handle.name,'Kontoauszuege');const entries=[];for await(const entry of handle.entries())entries.push(entry);assert.equal(await entries[0][1].getFile(),file);});
test('a virtual session folder is never sent to the native chooser as startIn',async()=>{const central=fakeCentral();await central.save('statements','Kontoauszuege');const ui=folderUi();globalThis.document=ui.document;let options;await mountAccountingFolders('virtual-start',{central,picker:async received=>{options=received;return {name:'Kontoauszuege'};},store:async()=>({handle:{name:'Kontoauszuege',selectionOnly:true},assignmentId:'test-1'})});await ui.node('[data-accounting-folder-pick="statements"]').onclick();assert.equal(options.startIn,undefined);delete globalThis.document;});
test('automatic folder scan never opens a permission prompt',async()=>{let prompts=0;const handle={queryPermission:async()=> 'prompt',requestPermission:async()=>{prompts++;return 'granted';}};await assert.rejects(accountingFolderHandle('auto-no-prompt','incoming',{store:async()=>({handle,assignmentId:'a'}),central:{read:async()=>({assignmentId:'a'})},requestPermission:false}),/freigeben/);assert.equal(prompts,0);});
test('one root picker binds and remembers three children without three separate selections',async()=>{const ui=folderUi();globalThis.document=ui.document;const saved=new Map();let calls=0;const children=['Ausgangsrechnungen','Eingangsrechnungen','Kontoauszuege'].map(name=>({name,kind:'directory',queryPermission:async()=> 'granted'}));const root={name:'Buchhaltung',kind:'directory',async *entries(){for(const child of children)yield[child.name,child];}};try{await mountAccountingFolders('root-user',{picker:async()=>{calls++;return root;},store:async(action,key,value)=>action==='get'?saved.get(key):saved.set(key,value)});await ui.node('[data-accounting-root-pick]').onclick();assert.equal(calls,1);assert.equal(saved.get('root-user:incoming').handle.name,'Eingangsrechnungen');assert.equal(saved.get('root-user:outgoing').handle.name,'Ausgangsrechnungen');assert.equal(saved.get('root-user:statements').handle.name,'Kontoauszuege');assert.equal(saved.get('root-user:root').handle.name,'Buchhaltung');assert.equal(ui.node('[data-accounting-root-assignment]').open,false);}finally{delete globalThis.document;}});
import {activateAccountingRoot} from '../src/utils/accountingFolders.js';
test('saved root permission is requested before any awaited work and avoids picker',async()=>{let requested=false,picks=0;const root={requestPermission(){requested=true;return Promise.resolve('granted');}};const promise=activateAccountingRoot(root,{picker:async()=>{picks++;}});assert.equal(requested,true);assert.equal(await promise,root);assert.equal(picks,0);});
test('automatic scan restores a child through an already authorized saved parent',async()=>{let prompts=0;const child={name:'Eingangsrechnungen',queryPermission:async()=> 'granted'};const stale={queryPermission:async()=> 'prompt'};const root={queryPermission:async()=> 'granted',getDirectoryHandle:async(name,options)=>{assert.equal(name,'Eingangsrechnungen');assert.equal(options.create,false);return child;},requestPermission:async()=>{prompts++;}};const handle=await accountingFolderHandle('restored-parent','incoming',{store:async(op,key)=>key.endsWith(':root')?{handle:root}:{handle:stale,assignmentId:'current'},central:{read:async()=>({folderName:'Eingangsrechnungen',assignmentId:'current'})},requestPermission:false});assert.equal(handle,child);assert.equal(prompts,0);});
test('different categories get accurate actionable permission notices',async()=>{await assert.rejects(accountingFolderHandle('statement-permission','statements',{store:async()=>({handle:{queryPermission:async()=> 'prompt'},assignmentId:'a'}),requestPermission:false}),error=>error.code==='accounting/folder-permission'&&error.message.includes('Kontoauszüge')&&!error.message.includes('Eingangsordner'));});

import {selectFolderFiles} from '../src/utils/accountingFolders.js';
test('cancel event with confirmed files keeps the selected folder instead of discarding it',async()=>{const pdf={name:'Test.pdf',webkitRelativePath:'Buchhaltung/Test.pdf'};let removed=0;const input={files:[pdf],setAttribute(){},remove(){removed++;},click(){this.oncancel();}};const previous=globalThis.document;globalThis.document={createElement:()=>input,body:{append(){}}};try{const folder=await selectFolderFiles();assert.equal(folder.name,'Buchhaltung');assert.equal(removed,1);}finally{globalThis.document=previous;}});
