import test from 'node:test';import assert from 'node:assert/strict';import {saveBookingAccount} from '../src/utils/accountingBookingAccountEditor.js';
const booking={statementId:'s',rowIndex:0,date:'2025-01-22',amountCents:80000,accountNumber:'2120'},invoice={id:'i',accountNumber:'2120',paymentStatus:'paid',paidDate:'2025-01-22',amountCents:80000,paymentMatch:{...booking}};
function mock(input){const docs=structuredClone(input),writes=[];let writing=false;return {docs,writes,services:async()=>({db:{},auth:{currentUser:{uid:'admin'}},firestore:{doc:(_,c,id)=>c+'/'+id,runTransaction:async(_,callback)=>{const queued=[];await callback({get:async ref=>{assert.equal(writing,false,'all reads precede writes');return {exists:()=>Boolean(docs[ref]),data:()=>structuredClone(docs[ref])};},update:(ref,patch)=>{assert.ok(!ref.startsWith('accountingStatements/'),'bank source rows are protected by Firestore rules');writing=true;queued.push([ref,patch,false]);},set:(ref,data)=>{writing=true;queued.push([ref,data,true]);}});for(const [ref,data,set]of queued){docs[ref]=set?data:{...docs[ref],...data};writes.push(ref);}}}})};}
test('reclassifying a paid invoice updates invoice and shared mapping while keeping bank source immutable',async()=>{const m=mock({'membershipContributions/i':invoice,'accountingStatements/s':{openingCents:0,closingCents:80000,rows:[booking]},'settings/accountingBookingAccounts':{assignments:{'s:0':'2120'}}});await saveBookingAccount({invoice,booking,kind:'outgoing',assignments:{'s:0':'2120'}},'2121',m.services);assert.equal(m.docs['membershipContributions/i'].accountNumber,'2121');assert.equal(m.docs['accountingStatements/s'].rows[0].accountNumber,'2120');assert.ok(!m.writes.includes('accountingStatements/s'));assert.equal(m.docs['settings/accountingBookingAccounts'].assignments['s:0'],'2121');assert.equal(m.docs['membershipContributions/i'].paymentStatus,'paid');assert.equal(m.docs['membershipContributions/i'].paidDate,'2025-01-22');assert.equal(m.docs['accountingStatements/s'].closingCents,80000);assert.equal(m.docs['accountingStatements/s'].rows[0].amountCents,80000);});
test('previously assigned booking without receipt can be assigned to another account',async()=>{const row={...booking,amountCents:-1000,accountNumber:'2803'},m=mock({'accountingStatements/s':{rows:[row]},'settings/accountingBookingAccounts':{assignments:{'s:0':'2803'}}});await saveBookingAccount({booking:row,assignments:{'s:0':'2803'}},'2895',m.services);assert.equal(m.docs['accountingStatements/s'].rows[0].accountNumber,'2803');assert.ok(!m.writes.includes('accountingStatements/s'));assert.equal(m.docs['settings/accountingBookingAccounts'].assignments['s:0'],'2895');});
test('concurrent reassignment and invalid account prevent writes',async()=>{const m=mock({'accountingStatements/s':{rows:[booking]},'settings/accountingBookingAccounts':{assignments:{'s:0':'2705'}}});await assert.rejects(saveBookingAccount({booking,assignments:{'s:0':'2120'}},'2121',m.services),/inzwischen geändert/);assert.equal(m.writes.length,0);await assert.rejects(saveBookingAccount({booking},'1234',m.services),/Kontenplan/);});

import {accountingAccountNumber} from '../src/utils/accountingAccountNumber.js';
test('shared reassignment overrides imported account in every view',()=>{assert.equal(accountingAccountNumber(booking,{'s:0':'2121'}),'2121');assert.equal(accountingAccountNumber({...invoice,accountNumber:'2121'},{'s:0':'2121'},'outgoing'),'2121');});
