import test from 'node:test';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
const {invoiceDispatchPlan,invoicePdfBytes,createInvoiceDispatch,invoiceMailAttachment}=createRequire(import.meta.url)('../functions/accountingInvoiceDispatch.js');
const record={invoiceNumber:'2026-001',invoiceDate:'2026-01-01',year:2026,amountCents:80000,currency:'EUR',paymentStatus:'outstanding',billingEmail:'billing@example.de',memberName:'Test GmbH'};
const pdf=Buffer.from('%PDF-1.4\nfixture\n%%EOF');
test('invoice mail uses billing recipient, personal name and invoice details',()=>{const p=invoiceDispatchPlan(record,{billingEmail:'new@example.de',firstName:'Klaus',lastName:'Juli'});assert.equal(p.to,'new@example.de');assert.match(p.text,/Klaus Juli/);assert.match(p.text,/800,00/);assert.match(p.subject,/2026-001/);assert.doesNotThrow(()=>invoiceDispatchPlan({...record,paymentStatus:'paid'}));});
test('cancelled, archived, invalid amount, dates or recipient cannot be sent',()=>{for(const change of [{paymentStatus:'cancelled'},{archived:true},{amountCents:0},{invoiceDate:'2026-02-30'},{billingEmail:''}])assert.throws(()=>invoiceDispatchPlan({...record,...change}));});
test('PDF validation rejects non-PDF, invalid base64 and oversized attachments',()=>{assert.deepEqual(invoicePdfBytes(pdf.toString('base64')),pdf);for(const value of ['abc','!!!!',Buffer.from('not a PDF').toString('base64'),Buffer.concat([pdf,Buffer.alloc(5*1024*1024)]).toString('base64')])assert.throws(()=>invoicePdfBytes(value));assert.equal(invoicePdfBytes(Buffer.concat([pdf,Buffer.alloc(2*1024*1024)]).toString('base64')).length,pdf.length+2*1024*1024);});
function context(){const docs=new Map([['membershipContributions/inv',structuredClone(record)]]),files=new Map();let denied=false;const bucket={file:path=>({save:async bytes=>files.set(path,bytes),download:async()=>[files.get(path)]})};const db={collection:c=>({doc:id=>({key:c+'/'+id,get:async()=>({exists:docs.has(c+'/'+id),data:()=>structuredClone(docs.get(c+'/'+id))})})}),runTransaction:async work=>{const writes=[];const result=await work({get:async r=>({exists:docs.has(r.key),data:()=>structuredClone(docs.get(r.key))}),create:(r,data)=>{assert.equal(docs.has(r.key),false);writes.push(()=>docs.set(r.key,data));},update:(r,data)=>writes.push(()=>docs.set(r.key,{...docs.get(r.key),...data}))});writes.forEach(w=>w());return result;}};class HttpsError extends Error{};const call=createInvoiceDispatch({db,bucket,HttpsError,FieldValue:{serverTimestamp:()=>new Date().toISOString()},requireAdmin:async()=>{if(denied)throw Error('admin required');}});return {docs,files,bucket,deny:()=>denied=true,call:data=>call({auth:{uid:'admin'},data:{invoiceId:'inv',...data}})};}
const send=p=>({action:'send',expectedFingerprint:p.fingerprint,subject:p.subject,text:p.text,pdfConfirmed:true,pdfBase64:pdf.toString('base64')});
test('preview does not send; dispatch retains PDF and prevents duplicate requests',async()=>{const c=context(),p=await c.call({action:'preview'});assert.equal(c.files.size,0);assert.equal(c.docs.size,1);const result=await c.call(send(p));const mail=c.docs.get('mailQueue/'+result.mailId);assert.equal(mail.to,record.billingEmail);const attachments=await invoiceMailAttachment(mail,c.bucket);assert.equal(attachments[0].filename,'Rechnung-2026-001.pdf');assert.deepEqual(attachments[0].content,pdf);await assert.rejects(c.call(send(p)));assert.equal(c.docs.size,2);assert.equal((await c.call({action:'preview'})).history[0].status,'queued');assert.equal(c.docs.get('membershipContributions/inv').paymentStatus,'outstanding');});
test('changed invoice and unconfirmed PDF are blocked, admin required',async()=>{const c=context(),p=await c.call({action:'preview'});await assert.rejects(c.call({...send(p),pdfConfirmed:false}));c.docs.get('membershipContributions/inv').amountCents=18000;await assert.rejects(c.call(send(p)));assert.equal(c.docs.size,1);c.deny();await assert.rejects(c.call({action:'preview'}));});
test('attachment integrity and storage path are validated; other mails have no attachment',async()=>{const c=context(),p=await c.call({action:'preview'}),r=await c.call(send(p)),mail=c.docs.get('mailQueue/'+r.mailId);await assert.rejects(invoiceMailAttachment({...mail,invoiceAttachment:{...mail.invoiceAttachment,storagePath:'other/private.pdf'}},c.bucket));c.files.set(mail.invoiceAttachment.storagePath,Buffer.from('%PDF-1.4 changed'));await assert.rejects(invoiceMailAttachment(mail,c.bucket));await assert.rejects(invoiceMailAttachment({template:'accounting_reminder'},c.bucket));assert.deepEqual(await invoiceMailAttachment({template:'event_invitation'},c.bucket),[]);});

test('an already dispatched invoice can be sent again only after a fresh preview',async()=>{const c=context();const first=await c.call({action:'preview'});const a=await c.call(send(first));await assert.rejects(c.call(send(first)));const next=await c.call({action:'preview'});const b=await c.call(send(next));assert.notEqual(a.mailId,b.mailId);assert.equal(c.docs.get('membershipContributions/inv').invoiceDispatches.length,2);});
test('changed invoice blocks reuse of the old PDF; invoice revision invalidates the preview',async()=>{const c=context();const p=await c.call({action:'preview'});c.docs.get('membershipContributions/inv').invoiceRevision=1;c.docs.get('membershipContributions/inv').invoiceNeedsRegeneration=true;const changed=await c.call({action:'preview'});assert.notEqual(changed.fingerprint,p.fingerprint);await assert.rejects(c.call(send(changed)));assert.equal(c.docs.size,1);});
