import test from 'node:test';import assert from 'node:assert/strict';
import {matchOutgoingPayments} from '../src/utils/accountingPaymentReconciliation.js';
const invoice={id:'2026-022',invoiceNumber:'2026-022',invoiceDate:'2026-01-01',amountCents:18000,paymentStatus:'outstanding'};
const bank={id:'bank',warnings:[],sourceName:'Sep.pdf',rows:[{date:'2026-09-09',amountCents:18000,description:'Maximilian Martin Suhr',details:'2026-022 CEX 000000000'}]};
test('an exact invoice reference and credit amount identify Suhrs payment with the actual bank date',()=>{const plan=matchOutgoingPayments([invoice],[bank],[],'2026-10-06');assert.equal(plan[0].status,'matched');assert.equal(plan[0].booking.date,'2026-09-09');assert.equal(plan[0].booking.bookingKey,'bank_0');assert.equal(invoice.paymentStatus,'outstanding');});
test('amount alone, longer invoice references and ambiguous credits remain review cases',()=>{for(const details of ['', '2026-0220','12026-022'])assert.equal(matchOutgoingPayments([invoice],[{...bank,rows:[{...bank.rows[0],details}]}])[0].status,'review');assert.equal(matchOutgoingPayments([invoice],[{...bank,rows:[bank.rows[0],bank.rows[0]]}])[0].status,'review');assert.ok(matchOutgoingPayments([invoice,{...invoice,id:'another'}],[bank]).every(r=>r.status==='review'));});
test('debits, future payments, invalid statements, wrong amounts and used credits cannot pay an invoice',()=>{for(const row of [{...bank.rows[0],amountCents:-18000},{...bank.rows[0],amountCents:17999},{...bank.rows[0],date:'2026-12-01'},{...bank.rows[0],date:'2025-12-31'}])assert.equal(matchOutgoingPayments([invoice],[{...bank,rows:[row]}],[],'2026-10-06')[0].status,'unmatched');assert.equal(matchOutgoingPayments([invoice],[{...bank,warnings:['bad balance']}])[0].status,'unmatched');assert.equal(matchOutgoingPayments([invoice],[bank],[{id:'bank_0',invoiceId:'other'}])[0].status,'unmatched');assert.equal(matchOutgoingPayments([{...invoice,paymentStatus:'paid'}],[bank])[0].status,'unmatched');});
import fs from 'node:fs';import vm from 'node:vm';import {bankLedger} from '../src/utils/bankStatementParser.js';
test('dropping an already saved statement still runs both payment checks and returns a visible result',async()=>{const statement={...bank,sourceHash:'bank',periodFrom:'2026-09-01',periodTo:'2026-09-30',openingCents:0,closingCents:18000,accountIban:'',rows:[{...bank.rows[0],balanceCents:18000}]};const nodes=new Map();const node=key=>{if(!nodes.has(key))nodes.set(key,{textContent:key==='[data-bank-statements]'?JSON.stringify([statement]):key==='[data-incoming-records]'?'[]':key==='[data-accounting-records]'?'{"records":[]}':'',parentElement:{dispatchEvent(){}},innerHTML:'',addEventListener(){}});return nodes.get(key);};let matches=0;const source=fs.readFileSync('src/utils/bankStatements.js','utf8').replace(/^import .*;\r?\n/gm,'').replaceAll('export ','');const context={singleFlightImport:fn=>fn,inspectAccountingFolder:async()=>({files:[{file:{name:'Sep.pdf'},name:'Sep.pdf',hash:'bank'}],metadata:[{hash:'bank'}],complete:true,needsRead:false,changes:{added:[],changed:[],removed:[]}}),saveAccountingInventory:async()=>{},watchOverviewBookingAccounts:async()=>{},statementsForYear:rows=>rows,accountingAccountNumber:r=>r.accountNumber||'',CustomEvent:class{constructor(type){this.type=type;}},document:{querySelector:node},Intl,Number,Set,Map,JSON,Error,bankLedger,parseHvbStatement:()=>{},pdfTextLines:()=>{},extractIban:()=>'',escapeHtml:v=>String(v||''),germanCsvDate:v=>v,csvTextCell:v=>v,accountingDropzoneMarkup:()=>'',mountAccountingDropzone:()=>{},accountingFolderHandle:async()=>({async *entries(){yield ['Sep.pdf',{kind:'file',getFile:async()=>({name:'Sep.pdf'})}];}}),reconcileAccountingPayments:async()=>{matches++;return {incoming:{matched:1,review:0},outgoing:{matched:2,review:1}};}};vm.createContext(context);vm.runInContext(source,context);context.readPdf=async()=>statement;const view=context.mountBankStatements('admin');const result=await node('[data-bank-import]').onclick(null,{propagate:true});assert.equal(matches,1);assert.match(result.message,/Kontoauszugsordner abgeglichen/);assert.match(result.message,/2 Ausgangsrechnungen/);assert.match(node('[data-bank-status]').textContent,/1 Fälle zur Prüfung/);view.updateData({invoices:[{id:'linked',invoiceNumber:'RE26-002448',paymentMatch:{statementId:'bank',rowIndex:0}}]});assert.match(node('[data-bank-ledger]').innerHTML,/data-bank-invoice="linked"/);view.updateData({invoices:[]});assert.doesNotMatch(node('[data-bank-ledger]').innerHTML,/data-bank-invoice="linked"/);});

import {matchIncomingPayments} from '../src/utils/invoicePaymentMatching.js';
test('a line-wrapped invoice number still identifies the exact incoming payment',()=>{const bill={id:'notary',invoiceNumber:'RE26-002448',invoiceDate:'2026-09-02',amountCents:5010,paymentStatus:'unrecorded'};const statement={id:'october',warnings:[],rows:[{date:'2026-10-02',amountCents:-5010,details:'KOSTENRECHNUNG Nr. RE26-002\n448 INTERNET'}]};assert.equal(matchIncomingPayments([bill],[statement])[0].status,'matched');assert.equal(matchIncomingPayments([{...bill,invoiceNumber:'RE26-00244'}],[statement])[0].status,'review');});

test('previously confirmed paid invoices receive a unique bank link using matching name, amount and payment date',()=>{const paid={...invoice,memberName:'Michael Kayser',firstName:'Michael',lastName:'Kayser',paymentStatus:'paid',paidDate:'2026-09-09'};const statement={...bank,rows:[{...bank.rows[0],description:'Michael Curt Otto Kayser',details:'Mitgliedsbeitrag'}]};assert.equal(matchOutgoingPayments([paid],[statement])[0].status,'matched');assert.equal(matchOutgoingPayments([{...paid,paidDate:'2026-09-08'}],[statement])[0].status,'unmatched');assert.equal(matchOutgoingPayments([paid],[{...statement,rows:[statement.rows[0],statement.rows[0]]}])[0].status,'review');assert.equal(matchOutgoingPayments([{...paid,paymentStatus:'outstanding',paidDate:''}],[statement])[0].status,'review');assert.deepEqual(matchOutgoingPayments([{...paid,paymentMatch:{bookingKey:'bank_0'}}],[statement]),[]);});
test('membership invoice suffix MB is recognized but longer invoice numbers are rejected',()=>{assert.equal(matchOutgoingPayments([invoice],[{...bank,rows:[{...bank.rows[0],details:'ReNr 2026-022MB'}]}])[0].status,'matched');assert.equal(matchOutgoingPayments([invoice],[{...bank,rows:[{...bank.rows[0],details:'2026-0220MB'}]}])[0].status,'review');});
