import test from 'node:test';import assert from 'node:assert/strict';import {createRequire} from 'node:module';import {partnerKey,partnerPatch} from '../src/utils/accountingPartners.js';const {allocatePartner,partnerKey:serverKey}=createRequire(import.meta.url)('../functions/accountingPartners.js');
test('repeated supplier capitalization and punctuation reuse one creditor and counter',()=>{const registry={};const p=allocatePartner(registry,'creditor',{supplier:'Margit Lehmann'});p.defaultAccountNumber='2895';assert.equal(allocatePartner(registry,'creditor',{supplier:'MARGIT LEHMANN'}),p);assert.equal(registry.nextCreditor,70001);assert.equal(partnerKey('creditor',{supplier:'MARGIT LEHMANN'}),serverKey('creditor',{supplier:'Margit Lehmann'}));});
test('explicit per-invoice account survives supplier defaults and payment fields are never patched',()=>{const r={accountNumber:'2803',paymentStatus:'paid',paidDate:'2026-01-01'},p={id:'m',kind:'creditor',number:'70012',defaultAccountNumber:'2895'};assert.deepEqual(partnerPatch(r,p),{accountingPartnerId:'m',creditorNumber:'70012'});assert.equal(partnerPatch({accountNumber:''},p).accountNumber,'2895');});
test('member identity is stable on renaming and independent from creditor identity',()=>{const registry={};const p=allocatePartner(registry,'debtor',{memberId:'m.1',memberName:'Alpha'});assert.equal(allocatePartner(registry,'debtor',{memberId:'m.1',memberName:'New Alpha'}),p);assert.notEqual(allocatePartner(registry,'creditor',{supplier:'Alpha'}).number,p.number);assert.ok(!partnerKey('debtor',{memberId:'m.1'}).includes('.'));});
import {partnerBalance} from '../src/utils/accountingPartners.js';
test('creditor balance counts only open invoices until a bank debit is linked',()=>{const partner={id:partnerKey('creditor',{supplier:'Margit Lehmann'}),kind:'creditor'},invoice={supplier:'MARGIT LEHMANN',invoiceDate:'2026-01-01',amountCents:23287,paymentStatus:'paid',paidDate:'2026-01-02'};assert.equal(partnerBalance(partner,{incoming:[invoice],asOf:'2026-10-07'}).openCents,23287);const paymentMatch={statementId:'s',rowIndex:0};assert.equal(partnerBalance(partner,{incoming:[{...invoice,paymentMatch}],statements:[{id:'s',rows:[{date:'2026-01-02',amountCents:-23287}]}],asOf:'2026-10-07'}).openCents,0);assert.equal(partnerBalance(partner,{incoming:[{...invoice,paymentMatch}],statements:[{id:'s',rows:[{date:'2026-11-02',amountCents:-23287}]}],asOf:'2026-10-07'}).openCents,23287);});
test('debtor balance excludes paid, archived and future invoices and flags missing amounts',()=>{const partner={id:'d',kind:'debtor'},record={accountingPartnerId:'d',invoiceDate:'2026-01-01',amountCents:18000};assert.deepEqual(partnerBalance(partner,{outgoing:[record,{...record,paymentStatus:'paid'},{...record,archived:true},{...record,invoiceDate:'2027-01-01'},{...record,amountCents:null},{...record,accountingPartnerId:'other'}],asOf:'2026-10-07'}),{openCents:18000,unknown:1});});
import {partnerEntries} from '../src/utils/accountingPartners.js';
test('booking overlay retains paid and open invoices of only the selected partner',()=>{const partner={id:'creditor_m',kind:'creditor'},paid={id:'p',accountingPartnerId:partner.id,invoiceDate:'2026-01-01',amountCents:12000,paymentMatch:{statementId:'s',rowIndex:0}},open={id:'o',accountingPartnerId:partner.id,invoiceDate:'2026-02-01',amountCents:5000};const row={date:'2026-01-02',amountCents:-12000,iban:'DE123',description:'Payment'};const entries=partnerEntries(partner,{incoming:[open,paid,{...open,id:'other',accountingPartnerId:'other'}],statements:[{id:'s',rows:[row]}]});assert.deepEqual(entries.map(e=>[e.invoice.id,e.paid]),[['p',true],['o',false]]);assert.equal(entries[0].booking,row);assert.equal(entries[1].booking,null);});
