import test from 'node:test';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
const {reminderPlan,createAccountingReminder}=createRequire(import.meta.url)('../functions/accountingReminders.js');
const invoice={invoiceNumber:'2026-001',invoiceDate:'2026-01-01',year:2026,amountCents:80000,currency:'EUR',paymentStatus:'outstanding',billingEmail:'rechnung@example.de',memberName:'Test GmbH'};
test('preview combines invoice, recipient, salutation, deadline and amount',()=>{const p=reminderPlan(invoice,{billingEmail:'billing@example.de',firstName:'Klaus',lastName:'Juli'},'2026-10-06');assert.equal(p.to,'billing@example.de');assert.equal(p.paymentDeadline,'2026-10-20');assert.match(p.text,/Klaus Juli/);assert.match(p.text,/800,00/);assert.match(p.text,/2026-001/);assert.equal(p.level,1);});
test('paid, cancelled, unknown, future and not yet due invoices are blocked',()=>{for(const change of [{paymentStatus:'paid'},{paymentStatus:'cancelled'},{paymentStatus:'unrecorded'},{invoiceDate:'2027-01-01'},{invoiceDate:'2026-02-30'},{dueDate:'2026-10-07'},{billingEmail:''},{amountCents:0},{archived:true}])assert.throws(()=>reminderPlan({...invoice,...change},{},'2026-10-06'));});
test('recipient and payment changes invalidate reviewed preview',()=>{const p=reminderPlan(invoice);assert.notEqual(p.fingerprint,reminderPlan({...invoice,amountCents:18000}).fingerprint);assert.notEqual(p.fingerprint,reminderPlan(invoice,{email:'new@example.de'}).fingerprint);});
function context(){const docs=new Map([['membershipContributions/inv',structuredClone(invoice)]]);let denied=false;const ref=(collection,id)=>({key:collection+'/'+id,get:async()=>({exists:docs.has(collection+'/'+id),data:()=>structuredClone(docs.get(collection+'/'+id))})});const db={collection:collection=>({doc:id=>ref(collection,id)}),runTransaction:async work=>{const writes=[];const result=await work({get:async r=>({exists:docs.has(r.key),data:()=>structuredClone(docs.get(r.key))}),update:(r,v)=>writes.push(()=>docs.set(r.key,{...docs.get(r.key),...v})),create:(r,v)=>{assert.equal(docs.has(r.key),false);writes.push(()=>docs.set(r.key,v));}});writes.forEach(w=>w());return result;}};class HttpsError extends Error{};const files=new Map();const bucket={file:path=>({save:async bytes=>files.set(path,bytes),download:async()=>[files.get(path)]})};const call=createAccountingReminder({db,bucket,HttpsError,requireAdmin:async()=>{if(denied)throw Error('admin required');}});return {docs,bucket,call:data=>call({auth:{uid:'admin'},data:{invoiceId:'inv',...data}}),deny:()=>denied=true};}
test('saving does not send; sending queues exactly one mail and preserves history',async()=>{const c=context();const p=await c.call({action:'preview'});await c.call({action:'save',expectedFingerprint:p.fingerprint,subject:p.subject,text:p.text,paymentDeadline:p.paymentDeadline});assert.equal(c.docs.size,1);const result=await c.call({action:'send',expectedFingerprint:p.fingerprint,pdfConfirmed:true,pdfBase64:Buffer.from('%PDF-1.4 fixture').toString('base64')});assert.equal(c.docs.size,2);assert.equal(c.docs.get('mailQueue/'+result.mailId).to,invoice.billingEmail);assert.equal(c.docs.get('membershipContributions/inv').paymentStatus,'outstanding');await assert.rejects(c.call({action:'send',expectedFingerprint:p.fingerprint}));const next=await c.call({action:'preview'});assert.equal(next.history.length,1);assert.equal(next.history[0].status,'queued');assert.equal(next.level,2);});
test('payment after drafting blocks sending and non-admin is rejected',async()=>{const c=context(),p=await c.call({action:'preview'});await c.call({action:'save',expectedFingerprint:p.fingerprint,subject:p.subject,text:p.text,paymentDeadline:p.paymentDeadline});c.docs.get('membershipContributions/inv').paymentStatus='paid';await assert.rejects(c.call({action:'send',expectedFingerprint:p.fingerprint}));assert.equal(c.docs.size,1);c.deny();await assert.rejects(c.call({action:'preview'}));});
test('invalid dates and subject header injection are rejected',async()=>{const c=context(),p=await c.call({action:'preview'});for(const change of [{paymentDeadline:'2027-02-30'},{subject:'test\r\nBcc: x@example.de'},{text:''}])await assert.rejects(c.call({action:'save',expectedFingerprint:p.fingerprint,subject:p.subject,text:p.text,paymentDeadline:p.paymentDeadline,...change}));assert.equal(c.docs.size,1);});

test('reminders require a confirmed PDF and mail worker attaches the exact invoice copy',async()=>{const c=context(),p=await c.call({action:'preview'});await c.call({action:'save',expectedFingerprint:p.fingerprint,subject:p.subject,text:p.text,paymentDeadline:p.paymentDeadline});await assert.rejects(c.call({action:'send',expectedFingerprint:p.fingerprint}));await assert.rejects(c.call({action:'send',expectedFingerprint:p.fingerprint,pdfConfirmed:true,pdfBase64:Buffer.from('not PDF').toString('base64')}));assert.equal(c.docs.size,1);const pdf=Buffer.from('%PDF-1.4 fixture');const r=await c.call({action:'send',expectedFingerprint:p.fingerprint,pdfConfirmed:true,pdfBase64:pdf.toString('base64')});const {invoiceMailAttachment}=createRequire(import.meta.url)('../functions/accountingInvoiceDispatch.js');const attachments=await invoiceMailAttachment(c.docs.get('mailQueue/'+r.mailId),c.bucket);assert.deepEqual(attachments[0].content,pdf);assert.equal(attachments[0].filename,'Rechnung-2026-001.pdf');});
