import test from 'node:test';import assert from 'node:assert/strict';
import {invoicePdfMatches,invoicePdfFile} from '../src/utils/accountingInvoicePdf.js';
import {accountingFolderHandle} from '../src/utils/accountingFolders.js';
test('invoice number matches its PDF exactly without matching a longer invoice number',()=>{const names=['RECHNUNG 2026-001 MB - Bibel TV.pdf','RECHNUNG 2026-0010 MB - Andere.pdf','RECHNUNG 2026-002 MB - Channel 21.pdf'];assert.deepEqual(invoicePdfMatches(names,{invoiceNumber:'2026-001'}),[names[0]]);assert.deepEqual(invoicePdfMatches(names,{invoiceNumber:'2026-002'}),[names[2]]);});
test('special characters in invoice numbers are literal',()=>{assert.deepEqual(invoicePdfMatches(['RECHNUNG 2026X001.pdf','RECHNUNG 2026.001.pdf'],{invoiceNumber:'2026.001'}),['RECHNUNG 2026.001.pdf']);});
function folder(names){return {async *entries(){for(const name of names)yield [name,{kind:'file',getFile:async()=>({name})}];}};}
test('missing and ambiguous PDFs do not open another invoice',async()=>{await assert.rejects(invoicePdfFile(folder(['RECHNUNG 2026-002.pdf']),{invoiceNumber:'2026-001'}),/Keine PDF/);await assert.rejects(invoicePdfFile(folder(['RECHNUNG 2026-001.pdf','RECHNUNG 2026-001 Kopie.pdf']),{invoiceNumber:'2026-001'}),/Mehrere PDFs/);assert.equal((await invoicePdfFile(folder(['RECHNUNG 2026-001.pdf']),{invoiceNumber:'2026-001'})).name,'RECHNUNG 2026-001.pdf');});
test('explicit filename resolves a known invoice without guesswork',()=>{const names=['RECHNUNG 2026-001.pdf','RECHNUNG 2026-001 Kopie.pdf'];assert.deepEqual(invoicePdfMatches(names,{invoiceNumber:'2026-001',pdfFileName:names[0]}),[names[0]]);});
test('a changed central folder invalidates a stored local PDF access binding',async()=>{const handle={queryPermission:async()=> 'granted'};await assert.rejects(accountingFolderHandle('pdf-access-test','outgoing',{store:async()=>({handle,assignmentId:'old'}),central:{read:async()=>({assignmentId:'new'})}}),/Zielordner wurde geändert/);assert.equal(await accountingFolderHandle('pdf-access-test','outgoing',{store:async()=>({handle,assignmentId:'same'}),central:{read:async()=>({assignmentId:'same'})}}),handle);});
