import test from 'node:test';import assert from 'node:assert/strict';import {createRequire} from 'node:module';import {accountingLockYears} from '../src/utils/accountingYearClosure.js';
const {accountingRecordYears,assertAccountingWritable,createAccountingYearClosure,updateOpenAccountingRecord}=createRequire(import.meta.url)('../functions/accountingYearClosure.js');
class HttpsError extends Error{constructor(code,message){super(message);this.code=code;}}
function fixture(){const docs=new Map(),writes=[];const ref=(c,id)=>({key:c+'/'+id,get:async()=>({exists:docs.has(c+'/'+id),data:()=>structuredClone(docs.get(c+'/'+id))})});const db={collection:c=>({doc:id=>ref(c,id)}),runTransaction:async work=>{const pending=[];let writing=false;const result=await work({get:async r=>{assert.equal(writing,false);return r.get();},create:(r,v)=>{writing=true;if(docs.has(r.key))throw Error('exists');pending.push([r.key,v]);},delete:r=>{writing=true;pending.push([r.key,null]);},update:(r,v)=>{writing=true;pending.push([r.key,{...docs.get(r.key),...v}]);}});for(const [k,v]of pending){if(v===null)docs.delete(k);else docs.set(k,v);writes.push(k);}return result;}};return {docs,writes,db};}
test('period allocation, actual payment year and statement years are protected in UI and backend',()=>{for(const r of [{invoiceDate:'2025-12-18',accountingPeriodYear:2026,paidDate:'2026-06-25'},{year:2025,paidDate:'2026-01-02'},{periodFrom:'2025-12-01',periodTo:'2026-01-31'}])assert.equal(accountingLockYears(r),accountingRecordYears(r).join(','));assert.deepEqual(accountingRecordYears({invoiceDate:'2025-12-18',accountingPeriodYear:2026}),[2026]);});
test('closed years reject writes while other years stay writable',async()=>{const f=fixture();f.docs.set('accountingYearClosures/2025',{year:2025});await assert.rejects(assertAccountingWritable(f.db,[{year:2025}],HttpsError),e=>e.code==='failed-precondition');await assertAccountingWritable(f.db,[{year:2026}],HttpsError);assert.equal(f.writes.length,0);});
test('closing is admin only, explicitly confirmed, PIN protected and idempotent',async()=>{const f=fixture(),call=createAccountingYearClosure({db:f.db,HttpsError,requireAdmin:async r=>{if(!r.auth)throw new HttpsError('unauthenticated','Login');}});await assert.rejects(call({data:{year:2025,confirm:true}}));await assert.rejects(call({auth:{uid:'admin'},data:{year:2025}}));assert.equal(f.writes.length,0);const result=await call({auth:{uid:'admin'},data:{year:2025,confirm:true,pin:'123456'}});assert.equal(result.status,'closed');assert.equal(result.closedBy,'admin');const again=await call({auth:{uid:'admin'},data:{year:2025,confirm:true}});assert.equal(again.closedAt,result.closedAt);assert.equal(f.writes.filter(k=>k.startsWith('accountingYearClosures/')).length,1);});
test('automatic status changes cannot update a closed record',async()=>{const f=fixture(),invoice={year:2025,paymentStatus:'outstanding',amountCents:80000};f.docs.set('membershipContributions/i',invoice);f.docs.set('accountingYearClosures/2025',{year:2025});await assert.rejects(updateOpenAccountingRecord(f.db,f.db.collection('membershipContributions').doc('i'),{automaticDunningStatus:'vacant'},HttpsError));assert.deepEqual(f.docs.get('membershipContributions/i'),invoice);assert.equal(f.writes.length,0);});
test('transactional writes read the closure before changing an open record',async()=>{const f=fixture();f.docs.set('membershipContributions/i',{year:2026,paymentStatus:'outstanding'});await updateOpenAccountingRecord(f.db,f.db.collection('membershipContributions').doc('i'),{accountNumber:'2121'},HttpsError);assert.equal(f.docs.get('membershipContributions/i').accountNumber,'2121');});
import {createHash} from 'node:crypto';
const {createInvoicePdfGeneration}=createRequire(import.meta.url)('../functions/accountingInvoicePdfGeneration.js');
test('stored PDF remains readable in a closed year even when regeneration would otherwise be needed; generation is blocked',async()=>{const f=fixture(),bytes=Buffer.from('%PDF-1.4\nstored original\n%%EOF'),hash=createHash('sha256').update(bytes).digest('hex'),artifact={storagePath:'accounting-mail/'+hash+'/'+hash+'.pdf',sha256:hash,filename:'Rechnung-2025-001.pdf'},record={year:2025,invoiceNeedsRegeneration:true,invoicePdfArtifact:artifact};f.docs.set('membershipContributions/i',record);f.docs.set('accountingYearClosures/2025',{year:2025});let uploads=0;const handler=createInvoicePdfGeneration({db:f.db,HttpsError,requireAdmin:async()=>{},bucket:{file:()=>({download:async()=>[bytes],save:async()=>uploads++})}});const result=await handler({auth:{uid:'admin'},data:{invoiceId:'i',action:'read'}});assert.equal(result.pdfBase64,bytes.toString('base64'));await assert.rejects(handler({auth:{uid:'admin'},data:{invoiceId:'i',action:'generate'}}),e=>e.code==='failed-precondition');assert.equal(uploads,0);assert.equal(f.writes.length,0);assert.deepEqual(f.docs.get('membershipContributions/i'),record);});

const {createAccountingYearUnlock,createYearPinStatus,createPinRecord}=createRequire(import.meta.url)('../functions/accountingYearPin.js');
function pinContext(f,clock){return {db:f.db,HttpsError,clock,requireAdmin:async r=>{if(!r.auth)throw new HttpsError('unauthenticated','Login');}};}
test('shared PIN is salted and hashed; it never appears in closure or audit records',async()=>{const f=fixture(),call=createAccountingYearClosure(pinContext(f));await call({auth:{uid:'admin'},data:{year:2025,confirm:true,pin:'456789'}});const secret=f.docs.get('accountingYearSecurity/sharedPin');assert.equal(secret.hash.length,64);assert.equal(secret.salt.length,32);assert.equal(JSON.stringify(secret).includes('456789'),false);for(const [key,value]of f.docs)if(!key.startsWith('accountingYearSecurity/'))assert.equal(JSON.stringify(value).includes('456789'),false);const status=await createYearPinStatus(pinContext(f))({auth:{uid:'admin'}});assert.deepEqual(status,{configured:true});});
test('wrong PIN keeps closure and commits failed attempt, correct PIN opens exactly one year and keeps audit',async()=>{const f=fixture(),context=pinContext(f),close=createAccountingYearClosure(context),unlock=createAccountingYearUnlock(context);await close({auth:{uid:'admin'},data:{year:2024,confirm:true,pin:'456789'}});await close({auth:{uid:'admin'},data:{year:2025,confirm:true}});const before=f.docs.get('accountingYearClosures/2025');await assert.rejects(unlock({auth:{uid:'admin'},data:{year:2025,pin:'000000'}}),e=>e.code==='permission-denied');assert.deepEqual(f.docs.get('accountingYearClosures/2025'),before);assert.equal(f.docs.get('accountingYearSecurity/sharedPin').failedAttempts,1);await unlock({auth:{uid:'admin'},data:{year:2025,pin:'456789'}});assert.equal(f.docs.has('accountingYearClosures/2025'),false);assert.equal(f.docs.has('accountingYearClosures/2024'),true);assert.equal(f.docs.get('accountingYearSecurity/sharedPin').failedAttempts,0);assert.ok([...f.docs.values()].some(v=>v.action==='unlock'&&v.by==='admin'&&v.closure.closedAt===before.closedAt));await assertAccountingWritable(f.db,[{year:2025}],HttpsError);await close({auth:{uid:'admin'},data:{year:2025,confirm:true}});await assert.rejects(assertAccountingWritable(f.db,[{year:2025}],HttpsError));});
test('five wrong attempts block even the correct PIN for 15 minutes and do not reopen the year',async()=>{const f=fixture();let now=Date.now();const context=pinContext(f,()=>now),close=createAccountingYearClosure(context),unlock=createAccountingYearUnlock(context);await close({auth:{uid:'admin'},data:{year:2025,confirm:true,pin:'456789'}});for(let n=0;n<5;n++)await assert.rejects(unlock({auth:{uid:'admin'},data:{year:2025,pin:'000000'}}));await assert.rejects(unlock({auth:{uid:'admin'},data:{year:2025,pin:'456789'}}),e=>e.code==='resource-exhausted');assert.equal(f.docs.has('accountingYearClosures/2025'),true);now+=15*60*1000+1;await unlock({auth:{uid:'admin'},data:{year:2025,pin:'456789'}});assert.equal(f.docs.has('accountingYearClosures/2025'),false);});
test('unlock needs administrator and a numeric PIN; PIN cannot be overwritten on a later closing',async()=>{const f=fixture(),context=pinContext(f),unlock=createAccountingYearUnlock(context),close=createAccountingYearClosure(context);await assert.rejects(unlock({data:{year:2025,pin:'456789'}}),e=>e.code==='unauthenticated');await assert.rejects(unlock({auth:{uid:'admin'},data:{year:2025,pin:'123'}}),e=>e.code==='invalid-argument');await assert.rejects(close({auth:{uid:'admin'},data:{year:2025,confirm:true,pin:'123'}}));assert.equal(f.docs.size,0);await close({auth:{uid:'admin'},data:{year:2025,confirm:true,pin:'456789'}});const secret=structuredClone(f.docs.get('accountingYearSecurity/sharedPin'));await assert.rejects(close({auth:{uid:'admin'},data:{year:2024,confirm:true,pin:'999999'}}));await close({auth:{uid:'admin'},data:{year:2024,confirm:true}});assert.deepEqual(f.docs.get('accountingYearSecurity/sharedPin'),secret);});

test('a closure created before PIN support can receive the shared PIN once and be unlocked',async()=>{const {createAccountingYearPinSetup}=createRequire(import.meta.url)('../functions/accountingYearPin.js'),f=fixture(),context=pinContext(f);f.docs.set('accountingYearClosures/2025',{year:2025,closedAt:'2026-10-08T09:00:00Z',closedBy:'admin'});const setup=createAccountingYearPinSetup(context);await setup({auth:{uid:'admin'},data:{pin:'456789'}});await assert.rejects(setup({auth:{uid:'admin'},data:{pin:'999999'}}));await createAccountingYearUnlock(context)({auth:{uid:'admin'},data:{year:2025,pin:'456789'}});assert.equal(f.docs.has('accountingYearClosures/2025'),false);});

test('PIN setup cannot be used to guess or overwrite an existing PIN',async()=>{const {createAccountingYearPinSetup}=createRequire(import.meta.url)('../functions/accountingYearPin.js'),f=fixture(),context=pinContext(f),setup=createAccountingYearPinSetup(context);await setup({auth:{uid:'admin'},data:{pin:'456789'}});const before=structuredClone(f.docs.get('accountingYearSecurity/sharedPin'));const errors=[];for(const pin of ['456789','000000']){try{await setup({auth:{uid:'admin'},data:{pin}});}catch(error){errors.push({code:error.code,message:error.message});}}assert.deepEqual(errors[0],errors[1]);assert.deepEqual(f.docs.get('accountingYearSecurity/sharedPin'),before);});
test('PIN closing validates PIN with committed attempt counts and retains audit',async()=>{const f=fixture(),context=pinContext(f),close=createAccountingYearClosure(context);await close({auth:{uid:'admin'},data:{year:2024,confirm:true,pin:'456789'}});const pinClose=createAccountingYearUnlock({...context,closing:true});await assert.rejects(pinClose({auth:{uid:'admin'},data:{year:2025,confirm:true,pin:'000000'}}),e=>e.code==='permission-denied');assert.equal(f.docs.has('accountingYearClosures/2025'),false);assert.equal(f.docs.get('accountingYearSecurity/sharedPin').failedAttempts,1);const result=await pinClose({auth:{uid:'admin'},data:{year:2025,confirm:true,pin:'456789'}});assert.equal(result.status,'closed');assert.equal(f.docs.has('accountingYearClosures/2024'),true);assert.ok([...f.docs.values()].some(v=>v.action==='close'&&v.year===2025));await assert.rejects(pinClose({auth:{uid:'admin'},data:{year:2026,pin:'456789'}}),e=>e.code==='invalid-argument');});
test('current and future years cannot be closed through either endpoint',async()=>{const f=fixture(),context=pinContext(f),close=createAccountingYearClosure(context),pinClose=createAccountingYearUnlock({...context,closing:true}),current=Number(new Intl.DateTimeFormat('en',{timeZone:'Europe/Berlin',year:'numeric'}).format(new Date()));for(const year of [current,current+1]){await assert.rejects(close({auth:{uid:'admin'},data:{year,confirm:true,pin:'456789'}}),e=>e.code==='invalid-argument');await assert.rejects(pinClose({auth:{uid:'admin'},data:{year,confirm:true,pin:'456789'}}),e=>e.code==='invalid-argument');}assert.equal(f.writes.length,0);});
test('shared PIN requires exactly six digits',()=>{for(const pin of ['0123','01234','123','1234567','abcd','12 34'])assert.throws(()=>createPinRecord(pin,'admin',new Date().toISOString()));assert.equal(createPinRecord('012345','admin',new Date().toISOString()).hash.length,64);});
