import test from 'node:test';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const {annualContributionPlan,createAnnualContributions}=require('../functions/annualContributions.js');
const members=[{id:'a',name:'Alpha',membershipType:'company',email:'a@example.de'},{id:'b',name:'Beta',membershipType:'individual'},{id:'c',name:'Cancelled',membershipType:'company',membershipAccessStatus:'cancelled'}];
const input={year:2027,invoiceDate:'2027-01-01',companyCents:80000,individualCents:18000};
test('all active members have correct annual fees and consecutive invoices',()=>{const p=annualContributionPlan(members,[],input);assert.equal(p.newCount,2);assert.equal(p.totalCents,98000);assert.deepEqual(p.rows.map(r=>r.invoiceNumber),['2027-001','2027-002']);assert.ok(p.rows.every(r=>r.paymentStatus==='outstanding'));});
test('one or checkbox selected members only',()=>{const p=annualContributionPlan(members,[],{...input,memberIds:['b']});assert.equal(p.newCount,1);assert.equal(p.rows[0].memberId,'b');assert.equal(p.totalCents,18000);});
test('existing and legacy annual records are skipped; numbering continues',()=>{for(const existing of [{memberId:'a'},{memberName:'ALPHA'},{billingEmail:'A@EXAMPLE.DE'}]){const p=annualContributionPlan(members,[{...existing,year:2027,invoiceNumber:'2027-041',amountCents:80000}],input);assert.equal(p.skippedCount,1);assert.equal(p.newCount,1);assert.equal(p.rows[1].invoiceNumber,'2027-042');}});
test('prior year does not exclude and second run creates nothing',()=>{const p=annualContributionPlan(members,[{memberId:'a',year:2026}],input);assert.equal(p.newCount,2);assert.equal(annualContributionPlan(members,p.rows,input).newCount,0);});
test('invalid selections, dates and cents are rejected',()=>{for(const change of [{memberIds:[]},{memberIds:['a','a']},{memberIds:['c']},{year:0},{invoiceDate:'2027-02-30'},{individualCents:1.1}])assert.throws(()=>annualContributionPlan(members,[],{...input,...change}));});
test('preview fingerprint reflects intervening fee or member changes',()=>{const p=annualContributionPlan(members,[],input);assert.notEqual(p.fingerprint,annualContributionPlan(members,[],{...input,companyCents:80001}).fingerprint);assert.notEqual(p.fingerprint,annualContributionPlan(members.map(m=>({...m,email:'new@example.de'})),[],input).fingerprint);});
class HttpsError extends Error{constructor(code,message){super(message);this.code=code;}}
function fixture(){const writes=[];const db={collection:name=>({name,doc:id=>({name,id})}),runTransaction:async work=>work({get:async collection=>({docs:(collection.name==='members'?members:[]).map(item=>({id:item.id,data:()=>item}))}),update:()=>{},set:()=>{},create:(ref,data)=>writes.push({ref,data})})};return {writes,call:createAnnualContributions({db,requireAdmin:async request=>{if(!request.auth)throw new HttpsError('unauthenticated','Login');return {};},HttpsError})};}
test('loading preview never writes, commit requires exact preview',async()=>{const {call,writes}=fixture();const request={auth:{uid:'admin'},data:{...input,dryRun:true}};const preview=await call(request);assert.equal(writes.length,0);await assert.rejects(call({...request,data:{...input,dryRun:false,expectedFingerprint:'stale'}}),error=>error.code==='failed-precondition');assert.equal(writes.length,0);const result=await call({...request,data:{...input,dryRun:false,expectedFingerprint:preview.fingerprint}});assert.equal(result.created,2);assert.equal(writes.length,2);assert.equal(writes[0].data.createdBy,'admin');assert.equal(writes[0].data.debtorNumber,'10000');assert.equal(writes[1].data.debtorNumber,'10001');assert.equal(writes[0].data.originalImport.amountCents,80000);});
test('anonymous requests cannot read or generate',async()=>{const {call,writes}=fixture();await assert.rejects(call({data:input}),error=>error.code==='unauthenticated');assert.equal(writes.length,0);});
test('June entry starts July and costs six twelfths',()=>{const p=annualContributionPlan([{...members[1],membershipStartDate:'2027-06-10'}],[],input);const r=p.rows[0];assert.equal(r.amountCents,9000);assert.equal(r.contributionMonths,6);assert.equal(r.contributionFrom,'2027-07-01');assert.equal(r.contributionTo,'2027-12-31');});
test('companies are prorated with rounding only on final amount',()=>{const r=annualContributionPlan([{...members[0],membershipStartDate:'2027-10-15'}],[],input).rows[0];assert.equal(r.contributionMonths,2);assert.equal(r.amountCents,13333);});
test('December and future entries have no contribution in selected year',()=>{for(const date of ['2027-12-01','2028-01-01']){const p=annualContributionPlan([{...members[1],membershipStartDate:date}],[],input);assert.equal(p.newCount,0);assert.equal(p.totalCents,0);assert.equal(p.rows[0].notDue,true);assert.equal(p.rows[0].invoiceNumber,'');}});
test('older members and subsequent years pay full annual fee',()=>{const p=annualContributionPlan([{...members[1],membershipStartDate:'2026-06-10'}],[],input);assert.equal(p.totalCents,18000);assert.equal(p.rows[0].contributionMonths,12);});
test('invalid entry dates stop creation',()=>{assert.throws(()=>annualContributionPlan([{...members[1],membershipStartDate:'2027-02-30'}],[],input));});
