import test from 'node:test';import assert from 'node:assert/strict';import {createRequire} from 'node:module';import {outgoingDunningStatus} from '../src/utils/accountingDunningStatus.js';
const {automaticReminderDecision}=createRequire(import.meta.url)('../functions/automaticAccountingReminders.js');
const record={paymentStatus:'outstanding',invoiceDispatches:[{mailId:'i',queuedAt:'2026-01-01T09:00:00Z',attachment:{filename:'copy.pdf'}}]};const mails=new Map([['i',{status:'sent',sentAt:'2026-01-01T09:00:00Z'}]]);
test('first reminder after exactly 90 days from sent mail, never from invoice date',()=>{const r={...record,invoiceDate:'2025-01-01'};assert.equal(outgoingDunningStatus(r,mails,'2026-03-31').label,'Offen');assert.equal(automaticReminderDecision(r,mails,'2026-03-31').action,'skip');assert.equal(outgoingDunningStatus(r,mails,'2026-04-01').label,'Mahnstufe 1');assert.equal(automaticReminderDecision(r,mails,'2026-04-01').action,'send');assert.equal(automaticReminderDecision({...r,invoiceDispatches:[]},mails,'2027-01-01').action,'skip');});
test('subsequent reminders wait 30 days from successful previous reminder, cap at four then vacant',()=>{const r={...record,reminders:[{mailId:'r',level:1,attachment:{filename:'copy.pdf'}}]},m=new Map([...mails,['r',{status:'sent',sentAt:'2026-10-07T09:26:05Z'}]]);assert.equal(outgoingDunningStatus(r,m,'2026-10-07').label,'Mahnstufe 1');assert.equal(automaticReminderDecision(r,m,'2026-11-05').action,'skip');assert.equal(automaticReminderDecision(r,m,'2026-11-06').action,'send');const four={...r,reminders:[{mailId:'r',level:4}]};assert.equal(automaticReminderDecision(four,m,'2026-11-05').action,'skip');assert.equal(automaticReminderDecision(four,m,'2026-11-06').action,'vacant');assert.equal(outgoingDunningStatus(four,m,'2026-11-06').label,'Vakant');});
test('paid, archived, cancelled and failed or queued previous reminders never send automatically',()=>{for(const patch of [{paymentStatus:'paid'},{paymentStatus:'cancelled'},{archived:true}])assert.equal(automaticReminderDecision({...record,...patch},mails,'2027-01-01').action,'skip');for(const status of ['queued','failed','skipped']){const m=new Map([...mails,['r',{status}]]);assert.equal(automaticReminderDecision({...record,reminders:[{mailId:'r',level:1}]},m,'2027-01-01').action,'review');}assert.equal(outgoingDunningStatus({...record,paymentStatus:'paid'},mails,'2027-01-01').label,'Bezahlt');});
test('re-sending the invoice does not reset its 90-day grace period',()=>{const r={...record,invoiceDispatches:[...record.invoiceDispatches,{mailId:'new'}]},m=new Map([...mails,['new',{status:'sent',sentAt:'2026-03-31T10:00:00Z'}]]);assert.equal(automaticReminderDecision(r,m,'2026-04-01').action,'send');});
test('automatic job queues one invoice copy and repeated run does not send another reminder',async()=>{
 const {createAutomaticAccountingReminders}=createRequire(import.meta.url)('../functions/automaticAccountingReminders.js');
 const {createHash}=createRequire(import.meta.url)('node:crypto');const bytes=Buffer.from('%PDF-1.4 original');const sha=createHash('sha256').update(bytes).digest('hex');const attachment={storagePath:'accounting-mail/'+ 'a'.repeat(64)+'/'+sha+'.pdf',sha256:sha,filename:'Rechnung-2026-001.pdf'};
 const earlier=new Date(Date.now()-91*86400000).toISOString();const docs=new Map([['membershipContributions/inv',{...record,invoiceNumber:'2026-001',invoiceDate:'2025-01-01',year:2026,amountCents:18000,currency:'EUR',billingEmail:'fixture@example.de',memberName:'Fixture',invoiceDispatches:[{mailId:'original',queuedAt:earlier,attachment}]}],['mailQueue/original',{status:'sent',sentAt:earlier}]]);
 const ref=key=>({id:key.split('/').at(-1),key,update:async patch=>docs.set(key,{...docs.get(key),...patch}),get:async()=>({data:()=>docs.get(key)})});
 const db={collection:name=>({doc:id=>ref(name+'/'+id),where:()=>({get:async()=>({docs:[{id:'inv',ref:ref('membershipContributions/inv'),data:()=>docs.get('membershipContributions/inv')}]})})}),runTransaction:async work=>{const writes=[];const result=await work({get:async r=>({exists:docs.has(r.key),data:()=>structuredClone(docs.get(r.key))}),update:(r,p)=>writes.push(()=>docs.set(r.key,{...docs.get(r.key),...p})),create:(r,p)=>{assert.equal(docs.has(r.key),false);writes.push(()=>docs.set(r.key,p));}});writes.forEach(w=>w());return result;}};
 const files=new Map([[attachment.storagePath,bytes]]);const bucket={file:path=>({download:async()=>[files.get(path)],save:async b=>files.set(path,b)})};class HttpsError extends Error{};
 const run=createAutomaticAccountingReminders({db,bucket,HttpsError,FieldValue:{delete:()=>null,serverTimestamp:()=>new Date().toISOString()},logger:{error:()=>{}}});
 assert.equal((await run()).sent,1);const created=[...docs.values()].find(m=>m.template==='accounting_reminder');assert.ok(created.invoiceAttachment);assert.equal(created.to,'fixture@example.de');assert.equal((await run()).sent,0);
 const bad=docs.get('membershipContributions/inv');bad.reminders=[];bad.invoiceDispatches[0].attachment=null;assert.equal((await run()).failed,1);assert.match(docs.get('membershipContributions/inv').automaticReminderError,/anhang fehlt/i);
});
