import test from 'node:test';import assert from 'node:assert/strict';
import {parseHvbStatement,bankLedger,pdfTextLines} from '../src/utils/bankStatementParser.js';
import {bankLedgerTable,bankLedgerCsv} from '../src/utils/bankStatements.js';
const pages=['Firma 01.01.2026 - 31.01.2026\nBuchung/Wert Buchungsinformation Saldo/Umsatz\nIhr alter Kontostand per 31.12.2025: EUR 1.000,00+\n02.01. LASTSCHRIFT 12,50-\n02.01. Dienstleister GmbH\nRechnung 2026-001\n02.01. SEPA-GUTSCHRIFT 180,00+\n02.01. ECHTZEITÜBERWEISUNG\nMitglied Name\nDE59700700240886945500\nMitgliedsbeitrag\nIhr neuer Kontostand: EUR 1.167,50+'];
test('HVB booking dates and signed cents produce exact running balances',()=>{const p=parseHvbStatement(pages,'Auszug.pdf');assert.equal(p.rows.length,2);assert.equal(p.rows[0].date,'2026-01-02');assert.equal(p.rows[0].amountCents,-1250);assert.equal(p.rows[0].balanceCents,98750);assert.equal(p.rows[1].balanceCents,116750);assert.deepEqual(p.warnings,[]);assert.equal(p.rows[1].description,'Mitglied Name');assert.ok(!p.rows[1].details.includes('DE597'));});
test('opening transfer is excluded from transaction credit totals',()=>{const s=parseHvbStatement(pages,'Auszug.pdf'),l=bankLedger([s]);assert.equal(l.openingCents,100000);assert.equal(l.debitCents,-1250);assert.equal(l.creditCents,18000);assert.equal(l.closingCents,116750);});
test('a mismatched closing balance is flagged and never silently corrected',()=>{const s=parseHvbStatement([pages[0].replace('1.167,50+','1.168,50+')],'Wrong.pdf');assert.equal(s.closingCents,116850);assert.equal(s.rows.at(-1).balanceCents,116750);assert.equal(s.warnings.length,1);});
test('unsupported or scanned statements are rejected instead of guessed',()=>{assert.throws(()=>parseHvbStatement([''],'Scan.pdf'),/nicht erkannt/);});
test('missing statements and duplicate periods are flagged',()=>{const s=parseHvbStatement(pages,'Auszug.pdf');assert.ok(bankLedger([s,s]).warnings.length);assert.ok(bankLedger([s,{...s,periodFrom:'2026-02-01',periodTo:'2026-02-28',sourceName:'Feb.pdf'}]).warnings.length);});
test('PDF text lines follow page coordinates and keep amount signs',()=>{const item=(text,x,y)=>({str:text,transform:[1,0,0,1,x,y]});assert.equal(pdfTextLines([item('180,00+',120,10),item('02.01.',0,10),item('Header',0,20)]),'Header\n02.01. 180,00+');});
test('the ledger view contains the requested six columns and German dates',()=>{const s=parseHvbStatement(pages,'Auszug.pdf');const html=bankLedgerTable([s]);for(const title of ['Konto','Datum','Lieferant','Verwendungszweck','Soll/Haben','Saldo'])assert.ok(html.includes(title));assert.ok(html.includes('02.01.2026'));assert.ok(html.includes('Übertrag HVB Bank'));});
test('ledger CSV keeps German dates and decimal text cells',()=>{const csv=bankLedgerCsv([parseHvbStatement(pages,'Auszug.pdf')]);assert.ok(csv.includes('=""02.01.2026""'));assert.ok(csv.includes('=""-12,50""'));assert.ok(!csv.includes('2026-01-02'));});
import {extractIban} from '../src/utils/bankStatementParser.js';
test('IBANs retain valid account and counterparty numbers separately',()=>{const iban='DE59700700240886945500';const statement=parseHvbStatement([pages[0].replace('Firma ',`IBAN BIC\nDE59 70070024 0886945500 HYVEDEMMXXX\nFirma `)],'IBAN.pdf');assert.equal(statement.accountIban,iban);assert.equal(statement.rows[1].iban,iban);assert.equal(statement.rows[0].iban,'');const stored=JSON.parse(JSON.stringify({...statement,rows:statement.rows.map(({lines,...row})=>row)}));assert.equal(stored.rows[1].iban,iban);assert.ok(bankLedgerTable([stored]).includes('Konto-IBAN'));assert.ok(bankLedgerCsv([stored]).includes(iban));});
test('invalid IBAN checksums are not stored as identified bank accounts',()=>{assert.equal(extractIban('DE59700700240886945501'),'');assert.equal(extractIban('GB82 WEST 1234 5698 7654 32'),'GB82WEST12345698765432');});
test('different account IBANs cannot silently share a running balance',()=>{const s=parseHvbStatement(pages,'Jan.pdf');assert.ok(bankLedger([{...s,accountIban:'DE59700700240886945500'},{...s,sourceName:'Feb.pdf',accountIban:'GB82WEST12345698765432'}]).warnings.some(w=>w.includes('unterschiedlichen IBANs')));});
import {bookingInvoiceLinks} from '../src/utils/bankStatements.js';
test('expanded booking opens only the invoice matched to that exact statement row',()=>{const row={statementId:'bank1',rowIndex:2};const invoices=[{id:'right',invoiceNumber:'RG 16-2026',paymentMatch:{statementId:'bank1',rowIndex:2}},{id:'wrongRow',paymentMatch:{statementId:'bank1',rowIndex:3}},{id:'wrongStatement',paymentMatch:{statementId:'bank2',rowIndex:2}}];const html=bookingInvoiceLinks(row,invoices);assert.ok(html.includes('data-bank-invoice="right"'));assert.ok(html.includes('Rechnung öffnen'));assert.ok(!html.includes('wrongRow'));assert.ok(!html.includes('wrongStatement'));assert.equal(bookingInvoiceLinks({statementId:'bank3',rowIndex:2},invoices),'');});
test('ledger keeps source identity across statements with identical booking dates',()=>{const s=parseHvbStatement(pages,'Jan.pdf');const ledger=bankLedger([{...s,id:'first'},{...s,id:'second'}]);assert.equal(ledger.rows[0].statementId,'first');assert.equal(ledger.rows[0].rowIndex,0);assert.equal(ledger.rows[2].statementId,'second');assert.equal(ledger.rows[2].rowIndex,0);});
import {bookingIban} from '../src/utils/bankStatements.js';
test('IBAN appears only in collapsed booking details and is retained in CSV',()=>{const iban='DE59700700240886945500';const statement=parseHvbStatement(pages,'Auszug.pdf');statement.rows[0].details='Empfänger IBAN DE59\n70070024 0886945500';statement.rows[0].iban='';assert.equal(bookingIban(statement.rows[0]),iban);const html=bankLedgerTable([statement]);assert.doesNotMatch(html,/<th>IBAN<\/th>/);assert.match(html,new RegExp('<p[^>]*>IBAN: '+iban+'</p>'));assert.equal((html.match(/<th[ >]/g)||[]).length,6);assert.ok(bankLedgerCsv([statement]).includes(iban));assert.equal(extractIban('DE59\n7007 0024 0886 9455 00'),iban);assert.equal(extractIban('DE59\n7007 0024 0886 9455 01'),'');});

test('HVB transaction overview supports full dates, minus amounts and multiline IBANs',()=>{const overview=['Kontoumsätze\nIBAN DE86 1002 0890 0031 4107 97\nIm ausgewählten Zeitraum 01.10.2026 - 06.10.2026 liegen Umsätze vor.\nKontostand am 06.10.2026 30.008,45 EUR\nBuchung Valuta Verwendungszweck Betrag\n02.10.2026 02.10.2026 ÜBERWEISUNG -232,87 EUR\nDienstleister GmbH IBAN DE2220\n0400000234040400 RECHNUNG 19-2026\n02.10.2026 02.10.2026 ÜBERWEISUNG -50,10 EUR\nNotariat RE26-002\n02.10.2026 02.10.2026 ÜBERWEISUNG -27,44 EUR\nAuslagen Etiketten\nhttps://bank.example/\n06.10.2026 - 15:13 Uhr Seite 1'];const s=parseHvbStatement(overview,'Umsaetze.pdf');assert.equal(s.rows.length,3);assert.equal(s.openingCents,3031886);assert.equal(s.closingCents,3000845);assert.equal(s.openingDate,'2026-09-30');assert.equal(s.rows[0].iban,'DE22200400000234040400');assert.equal(s.rows[0].amountCents,-23287);assert.ok(!s.rows.at(-1).details.includes('https:'));assert.equal(bankLedger([s]).debitCents,-31041);assert.deepEqual(s.warnings,[]);assert.throws(()=>parseHvbStatement([overview[0].replace('Kontostand am 06.10.2026','Kontostand am 05.10.2026')],'Wrong.pdf'),/Ende/);assert.throws(()=>parseHvbStatement([overview[0].replace('-50,10 EUR','unlesbar EUR')],'Wrong.pdf'),/vollständig/);const previous={sourceName:'September.pdf',periodFrom:'2026-08-01',periodTo:'2026-09-30',openingDate:'2026-07-31',openingCents:3031886,closingCents:3031886,accountIban:s.accountIban,rows:[],warnings:[]};assert.deepEqual(bankLedger([previous,s]).warnings,[]);});

test('amount colors follow debit and credit while assigned invoices stay clickable',()=>{const s={...parseHvbStatement(pages,'Auszug.pdf'),id:'bank'};const html=bankLedgerTable([s],[{id:'notary',invoiceNumber:'RE26-002448',paymentMatch:{statementId:'bank',rowIndex:0}}]);assert.match(html,/<button[^>]*data-bank-invoice="notary"[^>]*color:#c62828/);assert.equal((html.match(/data-bank-invoice="notary"/g)||[]).length,1);assert.match(html,/<span[^>]*color:#087a45[^>]*>180/);assert.doesNotMatch(html,/Beleg zugeordnet<\/small>/);assert.doesNotMatch(html,/<th>IBAN<\/th>/);});

test('IBAN and BIC are omitted from the single-line summary and outgoing receipt amounts are clickable',()=>{const s={...parseHvbStatement(pages,'Auszug.pdf'),id:'bank'};s.rows[1].description='Mitglied Name BIC HYVEDEMMXXX/IBAN DE59700700240886945500';const html=bankLedgerTable([s],[{id:'2026-001',invoiceKind:'outgoing',invoiceNumber:'2026-001',paymentMatch:{statementId:'bank',rowIndex:1}}]);assert.match(html,/title="Mitglied Name">Mitglied Name<\/summary>/);assert.match(html,/data-bank-invoice="2026-001"[^>]*color:#087a45[^>]*>180/);});

test('summary uses bank sender and purpose uses bank text despite invoice recipient',()=>{const s={...parseHvbStatement(pages,'Auszug.pdf'),id:'bank'};const html=bankLedgerTable([s],[{id:'other',memberName:'Different invoice recipient',paymentMatch:{statementId:'bank',rowIndex:1}}]);assert.match(html,/title="Mitglied Name">Mitglied Name<\/summary>/);assert.match(html,/title="Mitgliedsbeitrag">Mitgliedsbeitrag<\/td>/);assert.doesNotMatch(html,/<summary[^>]*>Different invoice recipient/);});
