import {accountingLockYears} from '../src/utils/accountingYearClosure.js';
import {accountingAccountNumber} from '../src/utils/accountingAccountNumber.js';
import {singleFlightImport} from '../src/utils/incomingAutoImport.js';
import test from 'node:test';import assert from 'node:assert/strict';
import {invoiceCents,parseIncomingInvoice} from '../src/utils/incomingInvoiceParser.js';
import {validateIncomingInvoice,incomingInvoiceCsv,incomingInvoicesMarkup} from '../src/utils/incomingInvoices.js';
const source='Dienstleister GmbH\nPROdigitalTV e.V.\nRechnungsnummer: RG-2026-001\nRechnungsdatum: 04.02.2026\nFällig am: 18.02.2026\nGesamtbetrag: 1.234,56 EUR\nIBAN DE59 70070024 0886945500';
test('invoice extraction uses explicit totals and preserves IBAN and dates',()=>{const r=parseIncomingInvoice(source,'invoice.pdf');assert.equal(r.supplier,'Dienstleister GmbH');assert.equal(r.invoiceNumber,'RG-2026-001');assert.equal(r.invoiceDate,'2026-02-04');assert.equal(r.dueDate,'2026-02-18');assert.equal(r.amountCents,123456);assert.equal(r.iban,'DE59700700240886945500');assert.equal(r.paymentStatus,'outstanding');assert.equal(r.reviewStatus,'needs_review');});
test('ambiguous totals remain unresolved and require a correction before saving',()=>{const r=parseIncomingInvoice(source+'\nRechnungsbetrag: 1.000,00 EUR','invoice.pdf');assert.equal(r.amountCents,null);assert.throws(()=>validateIncomingInvoice(r),/ergänzen/);});
test('scanned documents stay unfilled and invalid dates are not guessed',()=>{assert.equal(parseIncomingInvoice('','scan.pdf').amountCents,null);assert.equal(parseIncomingInvoice(source.replace('04.02.2026','31.02.2026'),'bad.pdf').invoiceDate,'');});
test('foreign currencies are not interpreted as EUR',()=>assert.throws(()=>parseIncomingInvoice(source.replace('EUR','USD'),'foreign.pdf'),/Fremdwährung/));
test('exact cents, paid dates and IBAN checks prevent invalid edits',()=>{assert.equal(invoiceCents('1.234,56'),123456);assert.throws(()=>invoiceCents('-100,00'));const r=parseIncomingInvoice(source,'invoice.pdf');assert.equal(validateIncomingInvoice(r),r);assert.throws(()=>validateIncomingInvoice({...r,paymentStatus:'paid'}),/Zahlungsdatum/);assert.throws(()=>validateIncomingInvoice({...r,iban:'DE59700700240886945501'}),/IBAN/);});
test('CSV retains German dates and text invoice identifiers',()=>{const csv=incomingInvoiceCsv([parseIncomingInvoice(source,'invoice.pdf')]);assert.ok(csv.includes('04.02.2026'));assert.ok(csv.includes('1234,56'));assert.ok(!csv.includes('2026-02-04'));assert.ok(csv.includes('IBAN'));});
test('saved entries use safe JSON and are independent from contribution records',()=>{const html=incomingInvoicesMarkup([{supplier:'</script><script>bad</script>'}]);const text=html.match(/data-incoming-records>([\s\S]*?)<\/script>/)[1];assert.equal(JSON.parse(text)[0].supplier,'</script><script>bad</script>');assert.ok(!text.includes('</script>'));});
import {incomingInvoiceSummary,incomingInvoicesTable} from '../src/utils/incomingInvoices.js';
test('incoming totals separate paid, open, unknown and cancelled invoices',()=>{const records=[{amountCents:95200,paymentStatus:'paid'},{amountCents:23287,paymentStatus:'outstanding'},{amountCents:2744,paymentStatus:'outstanding'},{amountCents:1000,paymentStatus:'unrecorded'},{amountCents:500,paymentStatus:'cancelled'},{amountCents:null}];const sum=incomingInvoiceSummary(records);assert.equal(sum.totalCents,122231);assert.equal(sum.paidCents,95200);assert.equal(sum.openCents,26031);assert.equal(sum.unrecordedCents,1000);assert.equal(sum.unknownAmounts,1);});
test('requested eight-column layout exposes account and payment dates without truncation',()=>{const html=incomingInvoicesTable([{id:'r1',accountNumber:'2705',supplier:'MEN Media Entertainment Networks GmbH',invoiceNumber:'AR001-0826',invoiceDate:'2026-08-24',amountCents:505750,paymentStatus:'paid',paidDate:'2026-08-24'}]);assert.equal((html.match(/<th[ >]/g)||[]).length,8);assert.ok(html.includes('2705'));assert.ok(html.includes('24.08.2026'));assert.ok(html.includes('bezahlt'));assert.ok(html.includes('MEN Media Entertainment Networks GmbH'));});
test('account is explicit and optional invoice numbers remain blank',()=>{const r=parseIncomingInvoice(source+'\nSachkonto: 2803','test.pdf');assert.equal(r.accountNumber,'2803');assert.equal(validateIncomingInvoice({...r,invoiceNumber:''}).invoiceNumber,'');assert.throws(()=>validateIncomingInvoice({...r,accountNumber:'abcd'}),/Konto/);assert.equal(parseIncomingInvoice(source+'\nKontonummer: 12345678','test.pdf').accountNumber,'');});
import {sortIncomingInvoices} from '../src/utils/incomingInvoices.js';
test('invoice list and CSV sort by bank payment date, undated entries last',()=>{const records=[{id:'open',supplier:'Unbezahlt-Test',amountCents:100,paymentStatus:'outstanding',invoiceDate:'2026-01-01'},{id:'later',supplier:'später',amountCents:100,paymentStatus:'paid',paidDate:'2026-03-04'},{id:'earlier',supplier:'früher',amountCents:100,paymentStatus:'paid',paidDate:'2026-01-02'}];assert.deepEqual(sortIncomingInvoices(records).map(r=>r.id),['earlier','later','open']);assert.equal(records[0].id,'open');const csv=incomingInvoiceCsv(records);assert.ok(csv.indexOf('früher')<csv.indexOf('später'));assert.ok(csv.indexOf('später')<csv.indexOf('Unbezahlt-Test'));});
import {incomingPaymentDisplay} from '../src/utils/incomingInvoices.js';
test('linked scanned invoices remain identifiable and show their bank date and review status',()=>{const record={id:'scan',supplier:'',sourceName:'RG 2170 - Thorsten Lork.pdf',amountCents:null,paymentStatus:'unrecorded',paymentMatch:{bookingKey:'hash_1'},paidDate:'2026-06-02',reviewStatus:'needs_review'};const html=incomingInvoicesTable([record]);assert.match(html,/Thorsten Lork/);assert.match(html,/02\.06\.2026/);assert.equal(incomingPaymentDisplay(record),'Zugeordnet · Belegdaten prüfen');assert.equal(incomingInvoiceSummary([record]).paidCents,0);});

import fs from 'node:fs';import vm from 'node:vm';import {missingInvoiceBookings} from '../src/utils/missingInvoiceBookings.js';
test('refreshing incoming data includes newly saved bank debits and publishes them to the open assignment editor',async()=>{const nodes=new Map(),events=[];const node=key=>{if(!nodes.has(key))nodes.set(key,{textContent:key==='[data-incoming-records]'?'[]':key==='[data-incoming-bank-data]'?'{"statements":[],"claims":[]}':'',value:'',innerHTML:'',disabled:false});return nodes.get(key);};const host={querySelector:node,addEventListener(){},dispatchEvent:event=>events.push(event)};node('[data-incoming-records]').parentElement=host;const bank={id:'new',sourceName:'New.pdf',warnings:[],rows:[{date:'2026-10-02',amountCents:-2744,description:'Auslagen Etiketten',details:'Amazon'}]};const collections={accountingIncomingInvoices:[],accountingStatements:[bank],accountingPaymentMatches:[]};const mockFirebase={db:{},firestore:{collection:(_,name)=>name,getDocs:async name=>({docs:collections[name].map(row=>({id:row.id,data:()=>row}))})}};const source=fs.readFileSync('src/utils/incomingInvoices.js','utf8').replace(/^import .*;\r?\n/gm,'').replaceAll('export ','').replaceAll("await import('../firebase/firebaseClient.js?v=3')",'({getFirebaseServices:async()=>mockFirebase})');const context={accountingLockYears,accountingAccountNumber,watchOverviewBookingAccounts:async()=>{},singleFlightImport,mockFirebase,document:{querySelector:node,querySelectorAll:()=>[]},CustomEvent:class{constructor(type,options){this.type=type;this.detail=options.detail;}},Intl,Number,JSON,Object,Promise,Date,missingInvoiceBookings,escapeHtml:v=>String(v||''),germanCsvDate:v=>v,csvTextCell:v=>v,mountAccountingDropzone:()=>{},watchAccountingInvoices:async()=>{},watchAccountingCollection:async()=>{}};vm.createContext(context);vm.runInContext(source,context);const view=context.mountIncomingInvoices('admin');await view.refresh();assert.match(node('[data-incoming-table]').innerHTML,/Auslagen Etiketten/);assert.match(node('[data-incoming-table]').innerHTML,/Rechnung fehlt/);assert.equal(events.at(-1).detail.statements[0].id,'new');assert.equal(JSON.parse(node('[data-incoming-bank-data]').textContent).statements.length,1);});

test('bank transaction overviews and original statements cannot be imported as invoices',()=>{const overview='Kontoumsätze\nBuchung Valuta Verwendungszweck Betrag\nNotariat Schmiedestraße GbR\nRECHNUNG Nr. RE26-002\n448';assert.throws(()=>parseIncomingInvoice(overview,'bank.pdf'),/Kontoauszug, keine Eingangsrechnung/);assert.throws(()=>parseIncomingInvoice('Buchung/Wert Buchungsinformation\nIhr alter Kontostand per 31.12.2025\nIhr neuer Kontostand','statement.pdf'),/Kontoauszüge/);assert.equal(parseIncomingInvoice(source+'\nZahlung bitte mit Rechnungsnummer im Verwendungszweck','invoice.pdf').amountCents,123456);});
test('Dropbox receipt extracts localized date, invoice number and gross total',()=>{const text='Dropbox International Unlimited Company\nOne Park Place, Floor 6\nAn Datum Rechnungsnummer\nKlaus Juli 2. Mai 2026 08:46 GMT M3JK7YY7GN6Z\nZwischensumme 171,33 €\n+ MwSt. (19 %) 32,55 €\nInsgesamt 203,88 €\nAlle Beträge werden in EUR angezeigt.';const r=parseIncomingInvoice(text,'Dropbox.pdf');assert.equal(r.supplier,'Dropbox International Unlimited Company');assert.equal(r.invoiceNumber,'M3JK7YY7GN6Z');assert.equal(r.invoiceDate,'2026-05-02');assert.equal(r.amountCents,20388);});
test('automatic and manual import share one running task and can run again after completion',async()=>{let resolve,count=0;const run=singleFlightImport(()=>{count++;return new Promise(r=>{resolve=r;});});const a=run(),b=run();assert.equal(a,b);await Promise.resolve();assert.equal(count,1);resolve('saved');assert.equal(await a,'saved');const c=run();await Promise.resolve();assert.equal(count,2);resolve('next');await c;});
