import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {assignmentCandidates,unassignedDebitBookings,invoiceAssignmentsMarkup} from '../src/utils/invoiceAssignments.js';
import {matchIncomingPayments} from '../src/utils/invoicePaymentMatching.js';
const today='2026-10-06';
const invoice={id:'inv',supplier:'Supplier',invoiceNumber:'RG-1234',invoiceDate:'2026-01-01',amountCents:18000,paymentStatus:'outstanding',updatedAt:'original',iban:'DE59 7007 0024 0886 9455 00'};
const row={date:'2026-02-01',amountCents:-18000,iban:'DE59700700240886945500',description:'Supplier',details:'RG-1234'};
const statement={id:'hash',sourceName:'Feb.pdf',warnings:[],rows:[row]};
test('IBAN and exact amount rank before amount-only suggestions; conflicting IBAN is excluded',()=>{const statements=[{...statement,rows:[{...row,iban:''},{...row},{...row,iban:'DE89370400440532013000'},{...row,amountCents:-18001}]}];const matches=assignmentCandidates(invoice,statements,[],today);assert.deepEqual(matches.map(r=>r.bookingKey),['hash_1','hash_0']);assert.equal(matches[0].ibanMatch,true);assert.equal(matches[1].ibanMatch,false);assert.equal(invoice.paymentStatus,'outstanding');assert.equal(matchIncomingPayments([invoice],[{...statement,rows:[{...row,iban:'DE89370400440532013000'}]}],[],today)[0].status,'unmatched');});
test('already assigned, warned, future and credit bookings are absent',()=>{const statements=[{...statement,rows:[row,{...row,date:'2026-10-29'},{...row,amountCents:18000},row]},{...statement,id:'warn',warnings:['bad balance']}];assert.equal(unassignedDebitBookings(statements,[{paymentMatch:{bookingKey:'hash_0'}}],[{id:'hash_3'}],today).length,0);assert.equal(assignmentCandidates(invoice,[statement],[{id:'hash_0',invoiceId:'other'}],today).length,0);});
test('embedded data cannot close the script and survives roundtrip',()=>{const html=invoiceAssignmentsMarkup([{...invoice,supplier:'</script><img onerror=x>'}],[statement],[]);const json=html.match(/data-assignment-data>([\s\S]*?)<\/script>/)[1];assert.ok(!json.includes('</script>'));assert.equal(JSON.parse(json).invoices[0].supplier,'</script><img onerror=x>');});
function confirmationContext({iban=row.iban,claimed=false,updatedAt=invoice.updatedAt,amountCents=row.amountCents,invoiceAmount=invoice.amountCents}={}){const writes=[];const bank={...statement,rows:[{...row,iban,amountCents}]};const docs={inv:{...invoice,amountCents:invoiceAmount,reviewStatus:invoiceAmount==null?"needs_review":"reviewed",updatedAt},hash:bank,hash_0:claimed?{invoiceId:'other'}:null};const transaction={get:async ref=>({id:ref.id,exists:()=>Boolean(docs[ref.id]),data:()=>docs[ref.id]}),set:(ref,data)=>writes.push({kind:'claim',id:ref.id,data}),update:(ref,data)=>writes.push({kind:'invoice',id:ref.id,data})};const f={db:{},auth:{currentUser:{uid:'admin'}},firestore:{doc:(_,collection,id)=>({collection,id}),runTransaction:async(_,callback)=>callback(transaction)}};const source=fs.readFileSync('src/utils/invoicePaymentMatching.js','utf8').replaceAll('export ','').replaceAll("await import('../firebase/firebaseClient.js?v=3')",'({getFirebaseServices:async()=>mockFirebase})');const context={mockFirebase:f,Date,Map,Set,Number,String,Promise,Error};vm.createContext(context);vm.runInContext(source,context);return {writes,confirm:context.confirmInvoicePayment};}
test('confirmation atomically stores a single-use claim and the actual bank payment date',async()=>{const {writes,confirm}=confirmationContext();await confirm('inv','hash_0','original');assert.equal(writes.length,2);assert.equal(writes[0].data.invoiceId,'inv');assert.equal(writes[1].data.paidDate,row.date);assert.equal(writes[1].data.paymentMatch.evidence,'IBAN und Betrag · manuell bestätigt');});
test('confirmation rechecks conflicting IBAN, claimed booking and stale invoice without writing',async()=>{for(const options of [{iban:'DE89370400440532013000'},{claimed:true},{updatedAt:'changed'}]){const {writes,confirm}=confirmationContext(options);await assert.rejects(confirm('inv','hash_0','original'));assert.equal(writes.length,0);}});

test('manual pairing allows a different IBAN only after explicit acknowledgment',async()=>{const {writes,confirm}=confirmationContext({iban:'DE89370400440532013000'});await assert.rejects(confirm('inv','hash_0','original',{manual:true}));assert.equal(writes.length,0);await confirm('inv','hash_0','original',{manual:true,acceptDifferences:true});assert.equal(writes[1].data.paymentMatch.confirmedDifferences[0],'IBAN weicht ab');assert.equal(writes[1].data.paymentStatus,'paid');});
test('a manually linked smaller bank amount does not mark the whole invoice paid or change its amount',async()=>{const {writes,confirm}=confirmationContext({amountCents:-17999});await confirm('inv','hash_0','original',{manual:true,acceptDifferences:true});assert.equal(writes[1].data.paymentStatus,'outstanding');assert.equal(writes[1].data.amountCents,undefined);assert.equal(writes[1].data.paymentMatch.amountCents,-17999);});
import {mountInvoiceAssignments} from '../src/utils/invoiceAssignments.js';
test('both lists allow selection; a selected pair enables saving and deviations require acknowledgment',()=>{const nodes=new Map();const node=selector=>{if(!nodes.has(selector))nodes.set(selector,{value:'',checked:false,innerHTML:'',disabled:false});return nodes.get(selector);};const radios=new Map();const root={querySelector:node,querySelectorAll(selector){if(!selector.includes('name='))return [];const name=selector.includes('assignment-invoice')?'assignment-invoice':'assignment-booking';const html=node(name==='assignment-invoice'?'[data-assignment-invoices]':'[data-assignment-bookings]').innerHTML;const entries=[...html.matchAll(new RegExp('name="'+name+'" value="([^"]+)"','g'))].map(m=>({value:m[1]}));radios.set(name,entries);return entries;}};const data={textContent:JSON.stringify({invoices:[invoice],statements:[{...statement,rows:[row,{...row,iban:'DE89370400440532013000'}]}],claims:[]}),parentElement:root};mountInvoiceAssignments('admin',{querySelector:()=>data});assert.doesNotMatch(node('[data-assignment-bookings]').innerHTML,/disabled/);radios.get('assignment-invoice')[0].onchange();radios.get('assignment-booking')[0].onchange();assert.equal(node('[data-assignment-save]').disabled,false);radios.get('assignment-booking')[1].onchange();assert.equal(node('[data-assignment-save]').disabled,true);node('[data-assignment-accept-differences]').checked=true;node('[data-assignment-accept-differences]').onchange();assert.equal(node('[data-assignment-save]').disabled,false);});

test('a scanned invoice with no amount can be linked after acknowledgment without inventing a bill amount',async()=>{const {writes,confirm}=confirmationContext({invoiceAmount:null});await assert.rejects(confirm('inv','hash_0','original',{manual:true}));await confirm('inv','hash_0','original',{manual:true,acceptDifferences:true});assert.equal(writes[1].data.paymentStatus,'unrecorded');assert.equal(writes[1].data.amountCents,undefined);assert.equal(writes[1].data.paymentMatch.confirmedDifferences[0],'Rechnungsbetrag fehlt');assert.equal(writes[1].data.paymentMatch.bookingKey,'hash_0');});
test('archived invoices and removed assignment rows are not suggested again',()=>{assert.deepEqual(matchIncomingPayments([{...invoice,archived:true}],[statement]),[]);assert.equal(assignmentCandidates(invoice,[{...statement,excludedAssignmentRows:[0]}],[],today).length,0);assert.equal(unassignedDebitBookings([{...statement,excludedAssignmentRows:[0]}],[],[],today).length,0);});
function removalContext({claimed=false,paid=false}={}){const writes=[];const docs={inv:{...invoice,paymentStatus:paid?'paid':'outstanding'},hash:statement,hash_0:claimed?{invoiceId:'inv'}:null};const tx={get:async ref=>({exists:()=>Boolean(docs[ref.id]),data:()=>docs[ref.id]}),update:(ref,data)=>writes.push({id:ref.id,data})};const f={db:{},auth:{currentUser:{uid:'admin'}},firestore:{doc:(_,collection,id)=>({collection,id}),runTransaction:async(_,cb)=>cb(tx)}};const source=fs.readFileSync('src/utils/invoiceAssignments.js','utf8').replace(/^import .*;\r?\n/gm,'').replaceAll('export ','').replaceAll("await import('../firebase/firebaseClient.js?v=3')",'({getFirebaseServices:async()=>mockFirebase})');const context={mockFirebase:f,Date,Set,Number,Error};vm.createContext(context);vm.runInContext(source,context);return {writes,remove:context.removeAssignmentItem};}
test('remove targets the chosen invoice or booking while retaining original document values',async()=>{const a=removalContext();await a.remove('invoice',invoice);assert.equal(a.writes[0].id,'inv');assert.equal(a.writes[0].data.archived,true);assert.equal(a.writes[0].data.amountCents,undefined);const b=removalContext();await b.remove('booking',{...row,index:0,statementId:'hash',bookingKey:'hash_0'});assert.equal(b.writes[0].id,'hash');assert.deepEqual(Array.from(b.writes[0].data.excludedAssignmentRows),[0]);assert.equal(b.writes[0].data.rows,undefined);assert.equal(b.writes[0].data.closingCents,undefined);});
test('paid invoices and already linked bookings cannot be removed',async()=>{const a=removalContext({paid:true});await assert.rejects(a.remove('invoice',invoice));assert.equal(a.writes.length,0);const b=removalContext({claimed:true});await assert.rejects(b.remove('booking',{index:0,statementId:'hash',bookingKey:'hash_0'}));assert.equal(b.writes.length,0);});

test('unrelated invoice metadata updates do not block a manually reviewed unchanged pair',async()=>{const {writes,confirm}=confirmationContext({updatedAt:'metadata-new'});await confirm('inv','hash_0','original',{manual:true,expectedInvoice:invoice});assert.equal(writes.length,2);});
test('changed payment details refresh the editor and cannot be silently approved using the old preview',async()=>{const {writes,confirm}=confirmationContext({updatedAt:'financial-new',invoiceAmount:19000});await assert.rejects(confirm('inv','hash_0','original',{manual:true,expectedInvoice:invoice}),error=>error.latestInvoice.amountCents===19000);assert.equal(writes.length,0);});
