const assert = require("node:assert/strict");
const { eventLivePortrait, eventLiveBiography, eventLiveBoardRole, eventLiveCompanyLogo } = require("../functions/eventLivePortraits");
const sources = [{ id: "board-one", name: "Klaus Juli", email: "board@example.test", photoUrl: "/board.jpg", status: "active" }, { id: "speaker-one", name: "Example Speaker", email: "speaker@example.test", assetUrl: "/speaker.jpg", status: "published" }];
assert.equal(eventLivePortrait({ name: "Klaus Juli", email: "different@example.test" }, {}, sources), "/board.jpg");
assert.equal(eventLivePortrait({ email: "SPEAKER@example.test" }, {}, sources), "/speaker.jpg");
assert.equal(eventLivePortrait({}, { sourcePersonId: "board-one" }, sources), "/board.jpg");
assert.equal(eventLivePortrait({}, { firstName: "Klaus", lastName: "Juli" }, sources), "/board.jpg");
assert.equal(eventLivePortrait({ name: "Klaus Juli" }, {}, [...sources, { name: "Klaus Juli", photoUrl: "/other.jpg" }]), "");
assert.equal(eventLivePortrait({ name: "Klaus Juli" }, {}, sources.map((s) => ({ ...s, status: "archived" }))), "");
assert.equal(eventLivePortrait({ name: "Unknown" }, {}, sources), "");
console.log("Portrait fallback: explicit links, email, unique name, ambiguity and archived records passed.");
const biographies = [
  { id: "speaker", name: "Example Speaker", email: "speaker@example.test", status: "published", longBio: "Long vita", shortBio: "Short vita" },
  { id: "board", name: "Klaus Juli", status: "active", shortBio: "Board vita" }
];
assert.equal(eventLiveBiography({ email: "SPEAKER@example.test" }, {}, biographies), "Long vita");
assert.equal(eventLiveBiography({}, { sourcePersonId: "speaker" }, biographies), "Long vita");
assert.equal(eventLiveBiography({ speakerId: "speaker" }, {}, biographies), "Long vita");
assert.equal(eventLiveBiography({}, { firstName: "Klaus", lastName: "Juli" }, biographies), "Board vita");
assert.equal(eventLiveBiography({ name: "Example Speaker" }, {}, [...biographies, { ...biographies[0], id: "duplicate" }]), "");
assert.equal(eventLiveBiography({ speakerId: "speaker" }, {}, biographies.map(item => ({ ...item, status: "draft" }))), "");
assert.equal(eventLiveBiography({ speakerId: "speaker" }, {}, biographies.map(item => ({ ...item, visibility: "internal" }))), "");
assert.equal(eventLiveBiography({ speakerId: "speaker" }, {}, [{ ...biographies[0], longBio: "", vita: "Stored vita" }]), "Stored vita");
console.log("Biography fallback: existing fields, explicit links, email, unique names and privacy filters passed.");
const board = [{ id: "board-klaus", name: "Klaus Juli", status: "active", role: "Vorstand, Kassenwart" }];
assert.equal(eventLiveBoardRole({ firstName: "Klaus", lastName: "Juli" }, {}, board), "Vorstand, Kassenwart");
assert.equal(eventLiveBoardRole({ boardMemberId: "board-klaus" }, {}, board), "Vorstand, Kassenwart");
assert.equal(eventLiveBoardRole({ name: "Other" }, {}, board), "");
assert.equal(eventLiveBoardRole({ name: "Klaus Juli" }, {}, [...board, { ...board[0], id: "duplicate" }]), "");
assert.equal(eventLiveBoardRole({ name: "Klaus Juli" }, {}, [{ ...board[0], status: "inactive" }]), "");
console.log("Board display role: matching, ambiguity and inactive records passed; no access roles modified.");
const logoSource = { id: "speaker-logo", name: "Example Speaker", email: "speaker@example.test", status: "published", companyLogoUrl: "/company.png", photoUrl: "/portrait.jpg" };
assert.equal(eventLiveCompanyLogo({ speakerId: "speaker-logo" }, {}, [logoSource]), "/company.png");
assert.equal(eventLiveCompanyLogo({ email: "SPEAKER@example.test" }, {}, [logoSource]), "/company.png");
assert.equal(eventLiveCompanyLogo({}, { displayName: "Example Speaker" }, [logoSource]), "/company.png");
assert.equal(eventLiveCompanyLogo({ name: "Example Speaker" }, {}, [logoSource, { ...logoSource, id: "duplicate" }]), "");
assert.equal(eventLiveCompanyLogo({ speakerId: "speaker-logo" }, {}, [{ ...logoSource, visibility: "private" }]), "");
assert.equal(eventLiveCompanyLogo({ speakerId: "speaker-logo" }, {}, [{ ...logoSource, status: "archived" }]), "");
assert.equal(eventLiveCompanyLogo({ speakerId: "speaker-logo" }, {}, [{ ...logoSource, companyLogoUrl: "" }]), "");
console.log("Company logos: public speaker matching, ambiguity, privacy and no portrait fallback passed.");
const speakerWithoutLogo = { ...logoSource, companyLogoUrl: "" };
const topicLogo = { eventIds: ["heuking"], speakerId: logoSource.id, speakerIds: [logoSource.id, "co-speaker"], status: "active", visibility: "public", companyLogoUrl: "/talk-company.png" };
const resolveLogo = topics => eventLiveCompanyLogo({ speakerId: logoSource.id }, {}, [speakerWithoutLogo], topics, "heuking");
assert.equal(resolveLogo([topicLogo]), "/talk-company.png");
assert.equal(resolveLogo([{ ...topicLogo, eventIds: ["other-event"] }]), "");
assert.equal(resolveLogo([{ ...topicLogo, visibility: "internal" }]), "");
assert.equal(resolveLogo([{ ...topicLogo, status: "draft" }]), "");
assert.equal(resolveLogo([{ ...topicLogo, speakerId: "co-speaker" }]), "");
assert.equal(resolveLogo([{ ...topicLogo, speakerId: "", speakerIds: [logoSource.id] }]), "/talk-company.png");
assert.equal(resolveLogo([{ ...topicLogo, speakerId: "" }]), "");
assert.equal(resolveLogo([topicLogo, { ...topicLogo, companyLogoUrl: "/ambiguous.png" }]), "");
assert.equal(eventLiveCompanyLogo({ speakerId: logoSource.id }, {}, [logoSource], [topicLogo], "heuking"), "/company.png");
console.log("Talk logos: event isolation, public status, main speaker, ambiguity and direct-logo priority passed.");
