const assert = require('node:assert/strict');
const { createContactResponder, autoShareRequest, contactVCard, contactCardForMessage } = require('../functions/eventLiveContactSharing');
const docs = new Map();
const ref = (path) => ({ id: path.split('/').pop(), path, collection: name => ref(`${path}/${name}`), doc: id => ref(`${path}/${id}`), get: async () => ({ exists: docs.has(path), data: () => docs.get(path) }), where() { return this; }, limit() { return { get: async () => ({ docs: [] }) }; } });
const db = { collection: ref, runTransaction: async fn => fn({ get: r => r.get(), set: (r, value, options) => docs.set(r.path, options?.merge ? { ...docs.get(r.path), ...value } : value), update: (r, value) => docs.set(r.path, { ...docs.get(r.path), ...value }) }) };
class HttpsError extends Error { constructor(code, message) { super(message); this.code = code; } }
const deps = { db, HttpsError, FieldValue: { serverTimestamp: () => 123 }, eventLiveContactRequestId: (...values) => values.join('-'), eventLiveUser: async request => { if (!request.auth) throw new HttpsError('unauthenticated'); return { contactId: request.auth, email: `${request.auth}@example.test` }; } };
const respond = createContactResponder(deps);
const request = (id, decision = 'accepted', auth = 'bob') => ({ auth, data: { eventId: 'event', requestId: id, decision } });
const pending = id => docs.set(`eventLiveContactRequests/${id}`, { eventId: 'event', senderContactId: 'alice', receiverContactId: 'bob', status: 'pending' });
const messages = () => [...docs.entries()].filter(([key]) => key.includes('/messages/'));
(async () => {
  docs.set('contacts/bob', { firstName: 'Bob', lastName: 'Example', email: 'bob@example.test', phone: '+49123456789', company: 'Example', autoShareContactDetails: false });
  pending('one');
  await assert.rejects(() => respond(request('one', 'accepted', 'alice')), { code: 'permission-denied' });
  assert.equal(messages().length, 0);
  await respond(request('one'));
  assert.equal(messages().length, 1);
  assert.equal(messages()[0][1].contactCard.email, 'bob@example.test');
  assert.equal(messages()[0][1].receiverContactId, 'alice');
  assert.equal(docs.get('eventLiveContactRequests/one').answeredByContactId, 'bob');
  assert.equal(docs.get('eventLiveContactRequests/one').answeredByName, 'Bob Example');
  assert.equal(docs.get('eventLiveContactRequests/one').answeredAt, 123);
  assert.equal(messages()[0][1].decision, 'accepted');
  assert.match(messages()[0][1].text, /mit Ja beantwortet/);
  await respond(request('one'));
  assert.equal(messages().length, 1);
  pending('two'); await respond(request('two', 'rejected'));
  assert.equal(messages().length, 2);
  const rejection = messages().find(([, item]) => item.contactRequestId === 'two')[1];
  assert.equal(rejection.decision, 'rejected');
  assert.equal(rejection.answeredByName, 'Bob Example');
  assert.match(rejection.text, /mit Nein beantwortet/);
  assert.equal(rejection.contactCard, undefined);
  assert.equal(rejection.text.includes('bob@example.test'), false);
  await respond(request('two', 'rejected'));
  assert.equal(messages().length, 2);
  await assert.rejects(() => respond(request('two', 'accepted')), { code: 'failed-precondition' });
  pending('three'); await autoShareRequest(deps, 'three');
  assert.equal(docs.get('eventLiveContactRequests/three').status, 'pending');
  docs.get('contacts/bob').autoShareContactDetails = true;
  await autoShareRequest(deps, 'three');
  assert.equal(docs.get('eventLiveContactRequests/three').status, 'accepted');
  assert.equal(messages().length, 3);
  assert.equal(docs.get('eventLiveContactRequests/three').answerMode, 'automatic');
  const card = await contactCardForMessage(messages()[0][1]);
  assert.ok(card.qrCode.startsWith('data:image/png;base64,'));
  assert.ok(card.vcard.includes('EMAIL;TYPE=INTERNET:bob@example.test'));
  assert.equal(await contactCardForMessage({ ...messages()[0][1], deleted: true }), null);
  const escaped = contactVCard({ name: 'A\nEND:VCARD', company: 'A;B,C', firstName: 'Ä'.repeat(70) });
  assert.ok(escaped.includes('FN:A\\nEND:VCARD'));
  assert.ok(escaped.split('\r\n').every(line => Buffer.byteLength(line) <= 75));
  console.log('Contact sharing passed: authorization, consent direction, reject, retry deduplication, automatic opt-in, QR, vCard escaping, deleted cards.');
})().catch(error => { console.error(error); process.exitCode = 1; });
